export const buyerTerms = {
  key: 'buyer_terms',
  version: 'buyer-terms-v1.0',
  titleKo: 'Noblesse Piercing B2B 회원 및 견적 약관',
  titleEn: 'Noblesse Piercing B2B Member and Quote Terms',
  required: true,
  sections: [
    {
      headingKo: '제1조 B2B 회원 약관의 목적',
      headingEn: 'Article 1. Purpose Of B2B Member Terms',
      bodyKo: '본 문서는 Noblesse Piercing이 회원가 이용 회원에게 제공하는 Member Price, 시장별 가격, 최소 수량, Inquiry List, Request Quote 및 Admin Quote 운영 기준을 설명하는 B2B 회원 약관입니다.',
      bodyEn: 'This document describes the B2B Buyer standards for Member Price, market-specific pricing, 최소 수량, Inquiry List, Request Quote, and Admin Quote provided by Noblesse Piercing to Reviewed Members.',
    },
    {
      headingKo: '제2조 회원 확인 기준',
      headingEn: 'Article 2. Member Review Criteria',
      bodyKo: 'Noblesse는 회사 정보, 판매 채널, 국가, 담당자 정보, 사업자 정보, 기존 거래 가능성 및 공급 정책을 종합적으로 검토하여 회원 접근 권한을 부여할 수 있습니다.',
      bodyEn: 'Noblesse may grant buyer access after reviewing company information, sales channel, country, contact details, business information, potential trading fit, and supply policy.',
    },
    {
      headingKo: '제3조 신청 정보의 정확성',
      headingEn: 'Article 3. Accuracy Of Submitted Information',
      bodyKo: '회원는 Member Access Request 과정에서 정확하고 최신의 정보를 제출해야 합니다. 허위 정보, 타인의 정보 또는 확인이 어려운 정보를 제출한 경우 승인이 보류되거나 취소될 수 있습니다.',
      bodyEn: 'Buyers must submit accurate and up-to-date information during Member Access Request. Approval may be held or revoked if false information, another person’s information, or unverifiable information is submitted.',
    },
    {
      headingKo: '제4조 국가 및 시장별 가격',
      headingEn: 'Article 4. Country And Market Pricing',
      bodyKo: 'Noblesse 가격은 assignedMarket, currency, 공급 조건, 수출 가능 여부에 따라 다를 수 있습니다. 시장별 가격은 서로 다를 수 있으며 모든 회원에게 동일하게 표시되지 않을 수 있습니다.',
      bodyEn: 'Noblesse pricing may differ by assignedMarket, currency, supply conditions, and export availability. Market pricing may differ and may not be displayed identically to all Buyers.',
    },
    {
      headingKo: '제5조 회원가 이용 회원 가격 제공 조건',
      headingEn: 'Article 5. Member Price Conditions',
      bodyKo: 'Noblesse는 승인된 회원에게만 일부 가격 정보를 제공할 수 있습니다. 가격 정보는 내부 거래 검토를 위한 정보이며 무단 공개 또는 외부 공유가 제한됩니다.',
      bodyEn: 'Noblesse may provide selected pricing information only to Reviewed Members. Pricing information is for internal trading review and unauthorized disclosure or external sharing is restricted.',
    },
    {
      headingKo: '제6조 최소 수량',
      headingEn: 'Article 6. 최소 수량',
      bodyKo: '최소 수량는 상품, 소재, 현재 공급 상태, 국가, 시장, 생산 조건에 따라 달라질 수 있습니다. 사이트에 표시된 최소 수량는 견적 검토 기준이며 Admin Quote에서 조정될 수 있습니다.',
      bodyEn: '최소 수량 may vary by product, material, current supply status, country, market, and production conditions. 최소 수량 shown on the site is a quote review basis and may be adjusted in Admin Quote.',
    },
    {
      headingKo: '제7조 가격 변경 가능성',
      headingEn: 'Article 7. Price Changes',
      bodyKo: '원자재, 환율, 생산 비용, 공급처 조건, 물류 상황, 수출 관련 비용에 따라 가격이 변경될 수 있습니다. 화면 가격 또는 priceSnapshot은 최종 확정 금액이 아닙니다.',
      bodyEn: 'Prices may change due to raw materials, exchange rates, production costs, supplier conditions, logistics, and export-related costs. Displayed price or priceSnapshot is not a final confirmed amount.',
    },
    {
      headingKo: '제8조 Request Quote의 성격',
      headingEn: 'Article 8. Nature Of Request Quote',
      bodyKo: 'Request Quote는 회원가 상품, 옵션, 수량, 메모를 기반으로 Noblesse에 견적 검토를 요청하는 절차입니다. 이는 최종 거래 확정이 아닙니다.',
      bodyEn: 'Request Quote is a process where a Buyer asks Noblesse to review products, options, quantities, and memo for a quote. It is not a final order or transaction.',
    },
    {
      headingKo: '제9조 priceSnapshot',
      headingEn: 'Article 9. priceSnapshot',
      bodyKo: 'priceSnapshot은 회원가 Request Quote를 제출한 시점에 참고용으로 기록되는 가격입니다. priceSnapshot은 이후 Admin Quote, 재고 확인, 공급 조건 검토 결과에 따라 달라질 수 있습니다.',
      bodyEn: 'priceSnapshot is the reference price recorded when a Buyer submits Request Quote. It may differ after Admin Quote, availability review, or supply condition review.',
    },
    {
      headingKo: '제10조 Admin Quote',
      headingEn: 'Article 10. Admin Quote',
      bodyKo: 'Admin Quote는 관리자가 Request Quote 내용을 검토한 뒤 안내하는 견적 기준입니다. Admin Quote에는 확정 가능 수량, 조정 단가, 납기, 배송 조건, 관리자 메모가 포함될 수 있습니다.',
      bodyEn: 'Admin Quote is the quote basis provided after an administrator reviews Request Quote details. It may include confirmable quantities, adjusted unit prices, lead time, shipping conditions, and administrator notes.',
    },
    {
      headingKo: '제11조 최종 견적 및 거래 미확정',
      headingEn: 'Article 11. Final Quote And Non-Final Status',
      bodyKo: 'Request Quote 제출만으로 최종 거래가 성립하지 않습니다. 최종 기준은 Admin Quote 또는 Noblesse 담당자의 별도 확인을 통해 안내됩니다.',
      bodyEn: 'Submitting Request Quote alone does not complete a final transaction. The final basis is provided through Admin Quote or separate confirmation by a Noblesse representative.',
    },
    {
      headingKo: '제12조 재고, 납기, 배송 조건',
      headingEn: 'Article 12. Availability, Lead Time, And Shipping',
      bodyKo: '재고 상태, 생산 가능 여부, 납기, 포장, 배송 조건은 Request Quote 이후 별도 검토됩니다. 표시된 납기는 참고용이며 상황에 따라 변경될 수 있습니다.',
      bodyEn: 'Availability, production feasibility, lead time, packaging, and shipping conditions are reviewed after Request Quote. Displayed lead time is for reference and may change.',
    },
    {
      headingKo: '제13조 수출 및 국가 제한',
      headingEn: 'Article 13. Export And Country Limits',
      bodyKo: '일부 상품은 국가별 규정, 수출 가능 여부, 물류 조건 또는 공급 정책에 따라 제공이 제한될 수 있습니다. Noblesse는 필요한 경우 상품 제공 범위를 조정할 수 있습니다.',
      bodyEn: 'Some products may be restricted due to country regulations, export availability, logistics conditions, or supply policy. Noblesse may adjust product availability where needed.',
    },
    {
      headingKo: '제14조 견적 조정',
      headingEn: 'Article 14. Quote Adjustment',
      bodyKo: '요청 수량이 최소 수량, 생산 단위 또는 공급 가능 조건과 맞지 않는 경우 Noblesse는 수량, 옵션, 단가 또는 납기를 조정하여 안내할 수 있습니다.',
      bodyEn: 'If requested quantities do not match 최소 수량, production units, or available supply conditions, Noblesse may adjust quantities, options, unit prices, or lead time.',
    },
    {
      headingKo: '제15조 거래 제한 및 승인 취소',
      headingEn: 'Article 15. Access Limitation And Approval Revocation',
      bodyKo: '허위 정보, 무단 접근, 가격 정보 오용, 타인 계정 사용, 시스템 남용, 부정 목적 이용이 확인되면 Noblesse는 회원 확인을 취소하거나 접근을 제한할 수 있습니다.',
      bodyEn: 'If false information, unauthorized access, pricing misuse, use of another account, system abuse, or improper purpose is found, Noblesse may revoke buyer approval or restrict access.',
    },
    {
      headingKo: '제16조 데이터 오류 및 사용자 책임',
      headingEn: 'Article 16. Data Errors And Buyer Responsibility',
      bodyKo: '회원는 제출 전 상품, 옵션, 수량, 메모를 확인해야 합니다. 오입력 또는 불명확한 요청으로 인한 확인 지연은 회원 책임 범위에 포함될 수 있습니다.',
      bodyEn: 'Buyers should review products, options, quantities, and memo before submission. Delays caused by incorrect input or unclear requests may fall within Buyer responsibility.',
    },
    {
      headingKo: '제17조 오용 및 계정 제한',
      headingEn: 'Article 17. Misuse And Account Limits',
      bodyKo: '회원가 이용 회원 기능은 해당 회원의 내부 검토 목적에 한해 제공됩니다. 가격 수집, 경쟁사 전달, 자동화된 대량 조회, 무단 스크래핑, 계정 공유는 제한됩니다.',
      bodyEn: 'Reviewed Member features are provided only for internal review by the relevant Buyer. Price harvesting, competitor sharing, automated bulk lookup, unauthorized scraping, and account sharing are restricted.',
    },
    {
      headingKo: '제18조 분쟁 및 문의',
      headingEn: 'Article 18. Disputes And Inquiries',
      bodyKo: '가격, 최소 수량, 납기, 상품 상태 또는 견적 내용에 관한 문의는 Noblesse 담당 채널을 통해 접수할 수 있습니다. 분쟁은 우선 협의로 해결합니다.',
      bodyEn: 'Questions about price, 최소 수량, lead time, product status, or quote details may be submitted through the Noblesse contact channel. Disputes should first be resolved through consultation.',
    },
  ],
}
