export const privacyPolicy = {
  key: 'privacy_policy',
  version: 'privacy-policy-v1.0',
  titleKo: '귀족 개인정보 처리방침',
  titleEn: 'Noblesse Piercing Privacy Policy',
  required: false,
  sections: [
    {
      headingKo: '제1조 처리 목적',
      headingEn: 'Article 1. Processing Purpose',
      bodyKo: 'Noblesse는 도매 회원가입 신청, 도매 회원 승인 검토, 회원가 접근 권한 관리, Inquiry List, Request Quote, My Inquiries, Admin Quote 안내, 고객 문의, 서비스 운영 및 부정 이용 방지를 위해 개인정보를 처리합니다.',
      bodyEn: 'Noblesse processes personal information for wholesale member requests, approval review, member price access management, Inquiry List, Request Quote, My Inquiries, Admin Quote guidance, customer support, service operation, and misuse prevention.',
    },
    {
      headingKo: '제2조 처리하는 개인정보 항목',
      headingEn: 'Article 2. Personal Information Items',
      bodyKo: '처리 항목은 이메일, 비밀번호, 회사명, 담당자명, 국가, 선호 언어, 전화번호, 메신저 종류, 메신저 ID, 판매 채널, 사업자 정보, 요청 메모, 서비스 이용 기록, 접속 로그, 쿠키, Inquiry List 기록, Request Quote 기록, My Inquiries 기록, 회원 상태, assignedMarket, currency, discountRate, minOrderAmount입니다.',
      bodyEn: 'Processed items include email, password, company name, contact name, country, preferred language, phone, messenger type, messenger ID, sales channel, business information, request memo, service usage records, access logs, cookies, Inquiry List records, Request Quote records, My Inquiries records, review status, assignedMarket, currency, discountRate, and minOrderAmount.',
    },
    {
      headingKo: '제3조 수집 방법',
      headingEn: 'Article 3. Collection Method',
      bodyKo: '개인정보는 회원가입, 도매 회원가입 신청, 계정 정보 입력, Inquiry List 이용, Request Quote 제출, 문의, 서비스 이용 과정에서 수집될 수 있습니다.',
      bodyEn: 'Personal information may be collected through registration, wholesale member requests, account information entry, Inquiry List use, Request Quote submission, inquiries, and service use.',
    },
    {
      headingKo: '제4조 보유 및 이용 기간',
      headingEn: 'Article 4. Retention And Use Period',
      bodyKo: '개인정보는 회원 탈퇴 또는 회원 확인 요청 철회 시까지 보유될 수 있습니다. 관련 법령, 분쟁 처리, 거래 기록 보존, 부정 이용 방지 목적이 필요한 경우 일정 기간 보관될 수 있으며 실제 법정 보존 기간은 운영 전 법률 검토를 통해 확정해야 합니다.',
      bodyEn: 'Personal information may be retained until account withdrawal or member request withdrawal. It may be retained for a defined period when required by law, dispute handling, transaction record retention, or misuse prevention. Legal retention periods must be finalized before operation.',
    },
    {
      headingKo: '제5조 파기 절차 및 방법',
      headingEn: 'Article 5. Disposal Process And Method',
      bodyKo: '보유 목적이 달성되거나 보유 기간이 종료된 개인정보는 지체 없이 파기하는 것을 원칙으로 합니다. 전자 파일은 복구가 어렵도록 삭제하고, 출력물은 분쇄 또는 안전한 방식으로 폐기합니다.',
      bodyEn: 'Personal information should be disposed of without delay once the retention purpose is fulfilled or the retention period ends. Electronic files should be deleted in a way that makes recovery difficult, and printed materials should be shredded or disposed of safely.',
    },
    {
      headingKo: '제6조 제3자 제공',
      headingEn: 'Article 6. Third-Party Provision',
      bodyKo: 'Noblesse는 법령상 근거가 있거나 사용자의 별도 동의가 있는 경우를 제외하고 개인정보를 제3자에게 제공하지 않는 것을 원칙으로 합니다. 실제 운영 시 제3자 제공 항목은 별도로 확정해야 합니다.',
      bodyEn: 'Noblesse does not provide personal information to third parties unless required by law or separately consented to by the user. Any actual third-party provision details must be finalized before operation.',
    },
    {
      headingKo: '제7조 처리 위탁',
      headingEn: 'Article 7. Processing Outsourcing',
      bodyKo: '서비스 운영을 위해 호스팅, 스토리지, 이메일, 메신저, 고객 응대, 분석 도구 등 외부 서비스를 사용할 수 있습니다. 실제 위탁 업체, 업무 내용, 보관 위치는 운영 전 확정 및 고지해야 합니다.',
      bodyEn: 'External services such as hosting, storage, email, messenger, customer support, or analytics tools may be used for service operation. Actual vendors, work scope, and storage locations must be finalized and disclosed before operation.',
    },
    {
      headingKo: '제8조 국외 이전',
      headingEn: 'Article 8. Overseas Transfer',
      bodyKo: '글로벌 회원 지원 및 클라우드 서비스 이용 과정에서 개인정보가 국외에 보관 또는 처리될 수 있습니다. 국외 이전 국가, 이전 항목, 이전 시점, 보유 기간, 수탁자는 운영 전 법률 및 개인정보 검토를 통해 확정해야 합니다.',
      bodyEn: 'Personal information may be stored or processed overseas when supporting global buyers or using cloud services. Transfer countries, items, timing, retention period, and processors must be finalized through legal and privacy review before operation.',
    },
    {
      headingKo: '제9조 이용자 권리',
      headingEn: 'Article 9. User Rights',
      bodyKo: '이용자는 개인정보 열람, 정정, 삭제, 처리정지, 동의 철회를 요청할 수 있습니다. 단, 법령 또는 분쟁 처리 목적상 보존이 필요한 정보는 일정 기간 제한될 수 있습니다.',
      bodyEn: 'Users may request access, correction, deletion, suspension of processing, or withdrawal of consent. Some information may be retained for a defined period when required by law or dispute handling.',
    },
    {
      headingKo: '제10조 권리 행사 방법',
      headingEn: 'Article 10. How To Exercise Rights',
      bodyKo: '개인정보 관련 요청은 사이트 내 계정 기능, 이메일 또는 Noblesse가 안내하는 연락 채널을 통해 접수할 수 있습니다. 본인 확인이 필요한 경우 추가 확인 절차가 진행될 수 있습니다.',
      bodyEn: 'Privacy-related requests may be submitted through account features, email, or contact channels provided by Noblesse. Additional identity verification may be required.',
    },
    {
      headingKo: '제11조 쿠키 및 접속 정보',
      headingEn: 'Article 11. Cookies And Access Information',
      bodyKo: 'Noblesse는 서비스 안정화, 접속 상태 관리, 이용 패턴 확인을 위해 쿠키와 접속 로그를 사용할 수 있습니다. 사용자는 브라우저 설정을 통해 쿠키 저장을 제한할 수 있습니다.',
      bodyEn: 'Noblesse may use cookies and access logs for service stability, session management, and usage pattern review. Users may limit cookie storage through browser settings.',
    },
    {
      headingKo: '제12조 개인정보 보호 조치',
      headingEn: 'Article 12. Security Measures',
      bodyKo: 'Noblesse는 접근 권한 관리, 전송 구간 보호, 로그 관리, 최소 권한 원칙, 내부 접근 통제 등 필요한 보호 조치를 마련해야 합니다. 실제 운영 보안 정책은 서비스 공개 전 확정되어야 합니다.',
      bodyEn: 'Noblesse should prepare security measures such as access control, transmission protection, log management, least privilege, and internal access restrictions. Actual operating security policies must be finalized before launch.',
    },
    {
      headingKo: '제13조 만 14세 미만 아동',
      headingEn: 'Article 13. Children Under 14',
      bodyKo: 'Noblesse는 B2B 회원용 카탈로그 서비스로, 만 14세 미만 아동을 대상으로 하지 않습니다. 관련 신청이 확인될 경우 처리가 제한될 수 있습니다.',
      bodyEn: 'Noblesse is a B2B buyer catalog service and is not directed to children under 14. Related requests may be restricted if identified.',
    },
    {
      headingKo: '제14조 개인정보 보호책임자',
      headingEn: 'Article 14. Privacy Officer',
      bodyKo: '개인정보 보호책임자: 운영 전 확정 예정. 문의 이메일: privacy@noblesse.example. 실제 담당자명, 직책, 연락처는 운영 전 반드시 확정해야 합니다.',
      bodyEn: 'Privacy officer: to be confirmed before operation. Contact email: privacy@noblesse.example. Actual name, title, and contact details must be finalized before operation.',
    },
    {
      headingKo: '제15조 권익침해 구제',
      headingEn: 'Article 15. Remedies',
      bodyKo: '개인정보 침해 관련 상담이나 구제 절차는 관련 기관 또는 Noblesse가 안내하는 연락 채널을 통해 진행할 수 있습니다. 국가별 회원의 경우 적용 기관이 다를 수 있습니다.',
      bodyEn: 'Consultation or remedies for privacy infringement may be handled through relevant authorities or contact channels provided by Noblesse. Applicable authorities may differ by member country.',
    },
    {
      headingKo: '제16조 방침 변경',
      headingEn: 'Article 16. Policy Changes',
      bodyKo: '개인정보 처리방침은 법령, 서비스 구조, 운영 정책 변경에 따라 개정될 수 있습니다. 중요한 변경은 사이트 또는 별도 연락 채널을 통해 안내할 수 있습니다.',
      bodyEn: 'This Privacy Policy may be revised due to law, service structure, or operating policy changes. Material changes may be announced through the site or another contact channel.',
    },
    {
      headingKo: '제17조 시행일 및 검토 필요 사항',
      headingEn: 'Article 17. Effective Date And Review Items',
      bodyKo: '본 방침은 privacy-policy-v1.0 초안입니다. 실제 운영 전 사업자 정보, 개인정보 보호책임자, 위탁, 국외 이전, 법정 보존 기간, 권리 행사 절차는 최종 법률 및 개인정보 검토를 통해 확정해야 합니다.',
      bodyEn: 'This policy is draft version privacy-policy-v1.0. Before operation, business information, privacy officer, outsourcing, overseas transfer, legal retention periods, and rights request procedures must be finalized through legal and privacy review.',
    },
  ],
}
