// Draft terms for Noblesse. Legal review is required before public launch.
export const termsOfService = {
  key: 'terms_of_service',
  version: 'terms-v1.0',
  titleKo: '귀족 이용약관',
  titleEn: 'Noblesse Piercing Terms of Service',
  required: true,
  sections: [
    {
      headingKo: '제1조 목적',
      headingEn: 'Article 1. Purpose',
      bodyKo: '본 약관은 귀족이 제공하는 Noblesse Piercing 웹사이트의 상품 카탈로그 열람, 회원 가입, 도매 회원 승인 신청, 견적 리스트, 견적 요청 및 관련 서비스 이용 조건을 정합니다. 본 서비스는 피어싱 상품 정보를 확인하고 견적 절차를 진행하기 위한 B2B 카탈로그 서비스입니다.',
      bodyEn: 'These terms define use of the Noblesse Piercing B2B catalog, account, approval, Inquiry List, and Request Quote services.',
    },
    {
      headingKo: '제2조 정의',
      headingEn: 'Article 2. Definitions',
      bodyKo: '회원은 본 약관에 동의하고 계정을 만든 이용자를 말합니다. 도매 회원은 귀족의 검토를 거쳐 회원가와 MOQ 등 제한 정보를 확인할 수 있는 회원을 말합니다. 견적 리스트는 회원이 관심 상품을 모아 견적 요청을 준비하는 기능이며, 견적 요청은 최종 거래 확정이 아닌 검토 요청입니다.',
      bodyEn: 'Member, approved member, Inquiry List, and Request Quote are defined for catalog and quotation use.',
    },
    {
      headingKo: '제3조 약관 게시 및 개정',
      headingEn: 'Article 3. Posting and Revision',
      bodyKo: '귀족은 본 약관을 웹사이트에서 확인할 수 있도록 게시합니다. 서비스 운영, 법령 변경, 정책 변경이 필요한 경우 약관을 개정할 수 있으며, 중요한 변경은 적용 전 합리적인 방식으로 안내합니다. 개정 후 서비스를 계속 이용하면 변경된 약관에 동의한 것으로 볼 수 있습니다.',
      bodyEn: 'Noblesse may revise these terms and will provide reasonable notice for material changes.',
    },
    {
      headingKo: '제4조 서비스 제공',
      headingEn: 'Article 4. Service',
      bodyKo: '귀족은 상품 이미지, 상품명, 상품 정보, 카테고리, 컬렉션, 회원 상태별 접근 안내, 견적 리스트 및 견적 요청 기능을 제공합니다. 서비스 범위는 운영 상황에 따라 조정될 수 있으며, 정기 점검 또는 긴급 조치가 필요한 경우 일부 기능이 일시 중단될 수 있습니다.',
      bodyEn: 'The service provides product catalog features and quotation-related workflows, subject to operational changes.',
    },
    {
      headingKo: '제5조 회원가입 및 도매 회원 승인 신청',
      headingEn: 'Article 5. Account and Approval Request',
      bodyKo: '이용자는 이메일, 회사명, 담당자명, 국가, 연락처, 판매 채널 등 필요한 정보를 입력하여 회원가입을 신청할 수 있습니다. 가입 직후에는 승인 대기 상태가 될 수 있으며, 귀족은 제출된 정보를 바탕으로 도매 회원 승인 여부를 검토합니다.',
      bodyEn: 'Users may create an account and submit business information for wholesale access review.',
    },
    {
      headingKo: '제6조 도매 회원 승인 및 접근 권한',
      headingEn: 'Article 6. Approved Member Access',
      bodyKo: '도매 회원으로 승인된 회원은 승인된 시장, 통화, 회원 조건에 따라 회원가, MOQ, 견적 리스트 및 견적 요청 기능을 사용할 수 있습니다. 승인 권한은 계정별로 부여되며, 다른 계정이나 제3자에게 양도할 수 없습니다.',
      bodyEn: 'Approved access is account-specific and enables buyer-only price, MOQ, Inquiry List, and Request Quote features.',
    },
    {
      headingKo: '제7조 회원 탈퇴 및 자격 제한',
      headingEn: 'Article 7. Account Termination and Restriction',
      bodyKo: '회원은 서비스 내 제공되는 절차 또는 별도 문의를 통해 탈퇴를 요청할 수 있습니다. 허위 정보 제출, 계정 공유, 승인 정보 오남용, 서비스 운영 방해 등이 확인되는 경우 귀족은 이용 제한, 승인 보류, 승인 취소 등의 조치를 할 수 있습니다.',
      bodyEn: 'Accounts may be restricted or approval may be revoked for misuse, false information, or operational harm.',
    },
    {
      headingKo: '제8조 상품 정보 및 이미지 제공',
      headingEn: 'Article 8. Product Information and Images',
      bodyKo: '상품 이미지와 설명은 상품 이해를 돕기 위한 자료입니다. 화면 환경, 촬영 조건, 생산 시점에 따라 색상, 광택, 세부 형태가 실제 상품과 다르게 보일 수 있습니다. 귀족은 정확한 정보를 제공하기 위해 노력하되, 상품 정보는 운영 과정에서 변경될 수 있습니다.',
      bodyEn: 'Product images and descriptions are provided for reference and may vary by screen, production, and operation.',
    },
    {
      headingKo: '제9조 가격 정보 제한',
      headingEn: 'Article 9. Price Access',
      bodyKo: '회원가는 도매 회원 승인 후 확인할 수 있습니다. 비회원 및 승인 대기 회원에게는 가격, MOQ 세부 정보, 시장별 조건이 제한될 수 있습니다. 화면에 표시되는 금액은 견적 검토 전 참고 정보이며 최종 안내 금액과 달라질 수 있습니다.',
      bodyEn: 'Buyer-only prices are available after approval and may differ from final quotation details.',
    },
    {
      headingKo: '제10조 Inquiry List',
      headingEn: 'Article 10. Inquiry List',
      bodyKo: 'Inquiry List는 도매 회원이 관심 상품, 옵션, 수량을 모아 견적 요청을 준비하는 기능입니다. Inquiry List에 상품을 담는 행위만으로 재고 확보, 가격 확정, 거래 성립이 발생하지 않습니다.',
      bodyEn: 'The Inquiry List helps approved members prepare quotation requests and does not confirm availability or terms.',
    },
    {
      headingKo: '제11조 Request Quote',
      headingEn: 'Article 11. Request Quote',
      bodyKo: 'Request Quote는 도매 회원이 귀족에 상품, 수량, 요청 메모를 전달하여 검토를 요청하는 기능입니다. 견적 요청은 최종 거래가 아니며, 귀족은 재고, 단가, MOQ, 납기, 배송 조건, 국가별 제한 사항을 확인한 뒤 별도 안내할 수 있습니다.',
      bodyEn: 'Request Quote is a review request. Noblesse confirms availability, price, MOQ, lead time, shipping, and restrictions later.',
    },
    {
      headingKo: '제12조 Admin Quote',
      headingEn: 'Article 12. Admin Quote',
      bodyKo: 'Admin Quote는 귀족 운영자가 견적 요청을 검토한 후 안내하는 견적 결과 또는 관리용 견적 정보를 말합니다. Admin Quote에는 상품별 수량, 조정된 단가, 예상 납기, 배송 조건, 추가 확인 사항이 포함될 수 있습니다.',
      bodyEn: 'Admin Quote is the reviewed quotation information prepared by Noblesse staff.',
    },
    {
      headingKo: '제13조 거래 확정 전 고지',
      headingEn: 'Article 13. Notice Before Confirmation',
      bodyKo: '견적 요청 및 Admin Quote 안내만으로 거래가 확정되지 않습니다. 최종 거래 조건은 귀족과 회원이 별도로 확인한 조건에 따르며, 상품 준비 가능 여부와 외부 사정에 따라 변경될 수 있습니다.',
      bodyEn: 'A transaction is not confirmed until final conditions are separately confirmed by Noblesse and the member.',
    },
    {
      headingKo: '제14조 사용자의 의무',
      headingEn: 'Article 14. Member Duties',
      bodyKo: '회원은 정확한 정보를 제공하고, 계정 정보를 안전하게 관리하며, 본인 또는 소속 사업자의 정당한 업무 목적 범위에서 서비스를 이용해야 합니다. 회원은 다른 회원의 정보나 서비스 운영 정보를 무단으로 수집하거나 이용해서는 안 됩니다.',
      bodyEn: 'Members must provide accurate information, protect account access, and use the service for legitimate business purposes.',
    },
    {
      headingKo: '제15조 금지 행위',
      headingEn: 'Article 15. Prohibited Conduct',
      bodyKo: '회원은 허위 가입, 타인 계정 사용, 승인 정보 공유, 시스템 침해, 자동 수집, 상품 이미지 무단 사용, 견적 정보 외부 유출, 서비스 운영 방해 행위를 해서는 안 됩니다. 귀족은 위반이 의심되는 경우 확인을 요청하거나 이용을 제한할 수 있습니다.',
      bodyEn: 'False registration, account sharing, scraping, unauthorized image use, and operational abuse are prohibited.',
    },
    {
      headingKo: '제16조 지식재산권',
      headingEn: 'Article 16. Intellectual Property',
      bodyKo: '웹사이트에 표시되는 브랜드, 이미지, 상품 설명, 화면 구성, 데이터 구조 및 콘텐츠에 관한 권리는 귀족 또는 정당한 권리자에게 있습니다. 회원은 사전 허락 없이 콘텐츠를 복제, 배포, 판매, 공개 게시 또는 변형할 수 없습니다.',
      bodyEn: 'Brand assets, images, descriptions, layout, data, and content belong to Noblesse or rightful owners.',
    },
    {
      headingKo: '제17조 개인정보 보호',
      headingEn: 'Article 17. Privacy',
      bodyKo: '귀족은 서비스 제공과 회원 승인 검토에 필요한 범위에서 개인정보를 처리합니다. 개인정보 처리의 구체적인 내용은 개인정보 처리방침 및 개인정보 수집 이용 동의 문서에서 정합니다.',
      bodyEn: 'Personal information is handled according to the Privacy Policy and collection-use consent.',
    },
    {
      headingKo: '제18조 면책',
      headingEn: 'Article 18. Disclaimer',
      bodyKo: '귀족은 천재지변, 통신 장애, 외부 서비스 장애, 회원의 정보 입력 오류, 승인 전 정보 제한으로 인한 불편에 대하여 귀족의 고의 또는 중대한 과실이 없는 한 책임을 지지 않습니다. 상품 정보는 검토와 안내를 위한 자료이며, 실제 조건은 최종 확인 과정에서 달라질 수 있습니다.',
      bodyEn: 'Noblesse is not liable for issues outside its control or for reference information that changes during review.',
    },
    {
      headingKo: '제19조 통지',
      headingEn: 'Article 19. Notice',
      bodyKo: '귀족은 이메일, 웹사이트 공지, 계정 화면, 메신저 등 합리적인 수단으로 회원에게 필요한 사항을 안내할 수 있습니다. 회원은 연락처 변경 시 최신 정보를 유지해야 하며, 미갱신으로 인한 안내 누락은 회원의 책임입니다.',
      bodyEn: 'Notices may be provided by email, website notice, account screen, messenger, or other reasonable means.',
    },
    {
      headingKo: '제20조 분쟁 해결 및 준거법',
      headingEn: 'Article 20. Governing Law',
      bodyKo: '본 약관과 서비스 이용에 관한 사항은 대한민국 법령을 기준으로 해석합니다. 분쟁이 발생한 경우 당사자는 우선 성실하게 협의하며, 협의로 해결되지 않는 경우 관련 법령에 따른 관할 기관 또는 법원의 절차를 따릅니다.',
      bodyEn: 'These terms are governed by Korean law, and disputes should first be resolved through good-faith discussion.',
    },
    {
      headingKo: '제21조 운영 전 검토 및 시행일',
      headingEn: 'Article 21. Review and Effective Date',
      bodyKo: '본 문서는 서비스 기획과 개발을 위한 약관 초안입니다. 실제 공개 운영 전 법무 전문가 및 개인정보 보호 전문가의 검토를 거쳐 최종 문안, 시행일, 사업자 정보, 문의처를 확정해야 합니다. 시행일은 최종 고지 시 명시합니다.',
      bodyEn: 'This draft requires legal and privacy expert review before public launch. The final effective date will be announced.',
    },
  ],
}
