export const termsOfService = {
  key: 'terms_of_service',
  version: 'terms-v1.0',
  titleKo: 'Noblesse Piercing 이용약관',
  titleEn: 'Noblesse Piercing Terms of Service',
  required: true,
  sections: [
    {
      headingKo: '제1조 목적',
      headingEn: 'Article 1. Purpose',
      bodyKo: '이 약관은 Noblesse Piercing 웹사이트가 글로벌 바이어에게 제공하는 B2B 피어싱 카탈로그, Buyer Approval, Approved Buyer Price, Inquiry List, Request Quote, My Inquiries 및 Admin Quote 관련 서비스 이용 기준을 정합니다.',
      bodyEn: 'These terms define the service standards for the Noblesse Piercing B2B piercing catalog, Buyer Approval, Approved Buyer Price, Inquiry List, Request Quote, My Inquiries, and Admin Quote services for global buyers.',
    },
    {
      headingKo: '제2조 정의',
      headingEn: 'Article 2. Definitions',
      bodyKo: '사이트는 Noblesse Piercing 웹사이트를 의미합니다. 사용자는 사이트 방문자 또는 이용자를 의미합니다. 비회원은 로그인하지 않은 방문자입니다. 바이어는 거래처 접근을 신청하거나 승인받은 사업자 또는 담당자입니다. 승인 바이어는 Noblesse가 가격 및 견적 기능 접근을 허용한 바이어입니다.',
      bodyEn: 'The site means the Noblesse Piercing website. A user means a visitor or user of the site. A guest means a visitor without sign-in. A Buyer means a business or contact person requesting or receiving buyer access. An Approved Buyer means a Buyer granted pricing and quote access by Noblesse.',
    },
    {
      headingKo: '제3조 핵심 용어',
      headingEn: 'Article 3. Core Terms',
      bodyKo: '상품은 사이트에 표시되는 피어싱 및 관련 카탈로그 품목입니다. Approved Buyer Price는 승인 바이어에게만 표시되는 보호 가격입니다. Inquiry List는 바이어가 견적 검토를 위해 담아두는 상품 목록입니다. Request Quote는 견적 검토 요청이며 최종 거래 확정이 아닙니다. Admin Quote는 관리자가 재고, 단가, 납기, 배송 조건을 검토한 뒤 안내하는 최종 견적 기준입니다. priceSnapshot은 Request Quote 시점에 참고용으로 기록되는 가격입니다.',
      bodyEn: 'Products are piercing and related catalog items displayed on the site. Approved Buyer Price is protected pricing shown only to Approved Buyers. Inquiry List is a list of items kept for quote review. Request Quote is a quote review request and is not a final order or transaction. Admin Quote is the final quote basis provided by an administrator after reviewing availability, unit price, lead time, and shipping conditions. priceSnapshot is the reference price recorded at the time of Request Quote.',
    },
    {
      headingKo: '제4조 약관 게시 및 개정',
      headingEn: 'Article 4. Posting And Revision',
      bodyKo: 'Noblesse는 이 약관을 사이트 또는 가입 과정에서 확인할 수 있도록 게시할 수 있습니다. 운영 정책, 서비스 구조, 법령, 내부 기준 변경에 따라 약관을 개정할 수 있으며 중요한 변경은 사이트 또는 별도 연락 수단으로 안내할 수 있습니다.',
      bodyEn: 'Noblesse may display these terms on the site or during registration. These terms may be revised due to operating policy, service structure, law, or internal standard changes. Material revisions may be announced through the site or another contact channel.',
    },
    {
      headingKo: '제5조 회사 정보 및 공지',
      headingEn: 'Article 5. Company Information And Notices',
      bodyKo: 'Noblesse는 사이트, 이메일, 메신저, 공지 영역 등을 통해 서비스 운영 관련 정보를 안내할 수 있습니다. 실제 사업자 정보, 연락처, 개인정보 보호책임자 등 운영 필수 정보는 서비스 공개 전 최종 확정되어야 합니다.',
      bodyEn: 'Noblesse may provide service operation information through the site, email, messenger, or notice areas. Business information, contact details, and privacy officer information must be finalized before launch.',
    },
    {
      headingKo: '제6조 서비스 제공',
      headingEn: 'Article 6. Service Provision',
      bodyKo: 'Noblesse는 상품 이미지, 기본 상품 정보, 카테고리, 컬렉션, 바이어 신청, 승인 상태 안내, 승인 바이어 가격 표시, Inquiry List, Request Quote, My Inquiries 및 Admin Quote 확인 기능을 제공할 수 있습니다.',
      bodyEn: 'Noblesse may provide product images, basic product information, categories, collections, buyer application, approval status guidance, approved pricing display, Inquiry List, Request Quote, My Inquiries, and Admin Quote review features.',
    },
    {
      headingKo: '제7조 서비스 변경 및 중단',
      headingEn: 'Article 7. Service Changes And Suspension',
      bodyKo: 'Noblesse는 상품 공급 조건, 이미지 업데이트, 카탈로그 구성, 가격 표시 방식, 견적 절차, 시장별 정책, 시스템 점검 또는 운영상 필요에 따라 서비스 일부를 변경하거나 일시 중단할 수 있습니다.',
      bodyEn: 'Noblesse may change or temporarily suspend parts of the service due to product supply conditions, image updates, catalog structure, price display method, quote process, market policy, system maintenance, or operational needs.',
    },
    {
      headingKo: '제8조 가입 및 Buyer Access Request',
      headingEn: 'Article 8. Sign-Up And Buyer Access Request',
      bodyKo: '바이어는 이메일, 회사명, 담당자명, 국가, 선호 언어, 연락처, 메신저 정보, 판매 채널, 사업자 정보 및 요청 메모를 제출하여 Buyer Access Request를 진행할 수 있습니다. 제출 정보는 바이어 승인 검토의 기초 자료로 사용됩니다.',
      bodyEn: 'A Buyer may submit email, company name, contact name, country, preferred language, contact details, messenger information, sales channel, business information, and request memo for Buyer Access Request. Submitted information is used as a basis for buyer approval review.',
    },
    {
      headingKo: '제9조 Buyer Approval 및 접근 권한',
      headingEn: 'Article 9. Buyer Approval And Access Rights',
      bodyKo: 'Noblesse는 제출 정보를 검토한 뒤 승인, 보류, 차단 또는 추가 확인을 요청할 수 있습니다. 승인 바이어만 Approved Buyer Price, 시장별 가격, MOQ 상세, Inquiry List 및 Request Quote 기능을 사용할 수 있습니다.',
      bodyEn: 'Noblesse may approve, hold, block, or request additional verification after reviewing submitted information. Only Approved Buyers may access Approved Buyer Price, market-specific pricing, MOQ details, Inquiry List, and Request Quote features.',
    },
    {
      headingKo: '제10조 탈퇴 및 자격 제한',
      headingEn: 'Article 10. Withdrawal And Eligibility Limits',
      bodyKo: '바이어는 서비스 이용 중단 또는 계정 삭제를 요청할 수 있습니다. 허위 정보 제출, 무단 가격 공유, 부정 접근, 시스템 오용 또는 회사 정책 위반이 확인되는 경우 Noblesse는 접근 권한을 제한하거나 승인을 취소할 수 있습니다.',
      bodyEn: 'A Buyer may request service discontinuation or account removal. Noblesse may restrict access or revoke approval if false information, unauthorized pricing disclosure, improper access, system misuse, or policy violation is found.',
    },
    {
      headingKo: '제11조 상품 정보 및 이미지',
      headingEn: 'Article 11. Product Information And Images',
      bodyKo: '상품 이미지와 설명은 바이어의 검토를 돕기 위한 카탈로그 정보입니다. 화면 색상, 소재 표현, 사이즈 인상은 기기 환경과 촬영 조건에 따라 실제 품목과 차이가 있을 수 있습니다.',
      bodyEn: 'Product images and descriptions are catalog information to support Buyer review. Screen color, material impression, and size presentation may differ from actual items depending on device environment and photography conditions.',
    },
    {
      headingKo: '제12조 가격 정보 제한',
      headingEn: 'Article 12. Price Information Restrictions',
      bodyKo: '가격 정보는 승인 바이어에게만 표시될 수 있습니다. 비회원과 승인 대기 사용자는 Approved Buyer Price, 시장별 가격, 상세 MOQ, 견적 요청 기능에 접근할 수 없습니다.',
      bodyEn: 'Pricing information may be displayed only to Approved Buyers. Guests and pending users cannot access Approved Buyer Price, market-specific pricing, detailed MOQ, or quote request features.',
    },
    {
      headingKo: '제13조 Inquiry List',
      headingEn: 'Article 13. Inquiry List',
      bodyKo: 'Inquiry List는 승인 바이어가 견적 검토를 위해 상품, 옵션, 수량을 임시로 보관하는 기능입니다. Inquiry List에 담긴 정보는 최종 공급 가능 여부나 확정 금액을 의미하지 않습니다.',
      bodyEn: 'Inquiry List lets Approved Buyers temporarily keep products, options, and quantities for quote review. Information in Inquiry List does not mean final availability or a confirmed amount.',
    },
    {
      headingKo: '제14조 Request Quote',
      headingEn: 'Article 14. Request Quote',
      bodyKo: 'Request Quote는 바이어가 선택한 상품과 요청 수량을 기준으로 Noblesse에 견적 검토를 요청하는 절차입니다. 이 단계는 최종 거래 확정이 아니며, 화면에 표시되는 가격과 estimatedTotal은 참고용입니다.',
      bodyEn: 'Request Quote is a process where a Buyer asks Noblesse to review selected products and requested quantities. This step is not a final order or transaction, and displayed prices and estimatedTotal are for reference only.',
    },
    {
      headingKo: '제15조 Admin Quote 및 최종 견적',
      headingEn: 'Article 15. Admin Quote And Final Quotation',
      bodyKo: 'Noblesse 관리자는 Request Quote 이후 재고, 단가, MOQ, 납기, 배송 조건, 수출 가능 여부를 검토하여 Admin Quote를 안내할 수 있습니다. 최종 기준은 Admin Quote 또는 관리자 확인 내용입니다.',
      bodyEn: 'After Request Quote, a Noblesse administrator may review availability, unit price, MOQ, lead time, shipping conditions, and export availability before providing Admin Quote. The final basis is the Admin Quote or administrator confirmation.',
    },
    {
      headingKo: '제16조 거래 확인 및 안내',
      headingEn: 'Article 16. Transaction Confirmation And Notice',
      bodyKo: '최종 거래 진행 여부, 수량, 금액, 납기, 배송 조건은 관리자 확인 이후 별도 안내될 수 있습니다. 클라이언트 화면에서 계산된 가격, subtotal, estimatedTotal은 최종 확정 금액으로 보지 않습니다.',
      bodyEn: 'Whether a transaction proceeds, and its quantity, amount, lead time, and shipping conditions may be separately confirmed after administrator review. Client-side price, subtotal, and estimatedTotal values are not final confirmed amounts.',
    },
    {
      headingKo: '제17조 사용자 의무',
      headingEn: 'Article 17. User Obligations',
      bodyKo: '사용자는 정확한 정보를 제공하고, 계정 접근 권한을 안전하게 관리하며, 승인 바이어 가격과 내부 견적 정보를 외부에 무단 공유하지 않아야 합니다.',
      bodyEn: 'Users must provide accurate information, manage account access safely, and avoid unauthorized external sharing of Approved Buyer Price or internal quote information.',
    },
    {
      headingKo: '제18조 금지 행위',
      headingEn: 'Article 18. Prohibited Acts',
      bodyKo: '허위 정보 제출, 타인 계정 사용, 가격 정보 무단 배포, 시스템 접근 우회, 자동 수집, 서비스 방해, 지식재산권 침해, 불법 또는 부정 목적의 이용은 금지됩니다.',
      bodyEn: 'False information submission, use of another account, unauthorized price distribution, access bypass, automated scraping, service disruption, intellectual property infringement, and unlawful or improper use are prohibited.',
    },
    {
      headingKo: '제19조 지식재산권',
      headingEn: 'Article 19. Intellectual Property',
      bodyKo: '사이트의 로고, 이미지, 상품 사진, 문구, 화면 구성, 카탈로그 자료 및 데이터 구조에 관한 권리는 Noblesse 또는 정당한 권리자에게 있습니다. 무단 복제, 배포, 수정, 상업적 이용은 제한됩니다.',
      bodyEn: 'Rights to the site logo, images, product photos, copy, screen layout, catalog materials, and data structure belong to Noblesse or the rightful owner. Unauthorized copying, distribution, modification, or commercial use is restricted.',
    },
    {
      headingKo: '제20조 개인정보 보호',
      headingEn: 'Article 20. Privacy',
      bodyKo: 'Noblesse는 Buyer Access Request와 서비스 운영에 필요한 개인정보를 관련 정책에 따라 처리합니다. 자세한 내용은 개인정보 수집 및 이용 동의와 개인정보 처리방침에서 안내합니다.',
      bodyEn: 'Noblesse processes personal information required for Buyer Access Request and service operation according to relevant policies. Details are provided in Privacy Collection and Use Consent and the Privacy Policy.',
    },
    {
      headingKo: '제21조 면책',
      headingEn: 'Article 21. Disclaimer',
      bodyKo: 'Noblesse는 천재지변, 통신 장애, 외부 서비스 장애, 사용자 귀책 사유 또는 합리적으로 통제하기 어려운 사유로 발생한 서비스 지연이나 제한에 대해 책임이 제한될 수 있습니다.',
      bodyEn: 'Noblesse may have limited responsibility for service delay or restriction caused by force majeure, communication failure, external service failure, user fault, or circumstances that are reasonably difficult to control.',
    },
    {
      headingKo: '제22조 통지',
      headingEn: 'Article 22. Notices',
      bodyKo: 'Noblesse는 사이트 공지, 이메일, 메신저 또는 사용자가 제공한 연락처를 통해 필요한 안내를 할 수 있습니다. 사용자는 연락처 변경 시 최신 정보를 유지해야 합니다.',
      bodyEn: 'Noblesse may provide notices through site announcements, email, messenger, or contact details submitted by users. Users should keep contact information up to date.',
    },
    {
      headingKo: '제23조 분쟁 및 준거법',
      headingEn: 'Article 23. Disputes And Governing Law',
      bodyKo: '서비스 이용과 관련한 분쟁은 우선 상호 협의로 해결합니다. 최종 준거법과 관할은 실제 사업자 정보와 운영 지역을 기준으로 서비스 공개 전 법률 검토를 통해 확정되어야 합니다.',
      bodyEn: 'Disputes related to the service should first be resolved through mutual consultation. Final governing law and jurisdiction must be confirmed through legal review before launch based on the actual business entity and operating region.',
    },
    {
      headingKo: '제24조 시행일 및 개정 고지',
      headingEn: 'Article 24. Effective Date And Revision Notice',
      bodyKo: '본 약관은 terms-v1.0 버전의 초안으로 관리됩니다. 실제 운영 전 시행일, 개정 이력, 고지 방식은 최종 약관 검토 후 확정되어야 합니다.',
      bodyEn: 'These terms are managed as draft version terms-v1.0. Before operation, the effective date, revision history, and notice method must be finalized after terms review.',
    },
  ],
}
