import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'
import { createAdminQuoteSampleItems, isAdminQuoteSampleMode } from '../src/pages/admin/adminQuoteSampleItems.js'

const read = (path) => readFileSync(join(process.cwd(), path), 'utf8')

test('quote density preview creates 15 safe display-only sample items', () => {
  const items = createAdminQuoteSampleItems([{ productImage: { url: '/sample.webp', altText: 'source' } }], 'kr')
  const params = new URLSearchParams('sampleItems=15')
  const quotePage = read('src/pages/admin/AdminQuotePage.jsx')
  const adminStyles = read('src/styles/admin-console.css')

  assert.equal(items.length, 15)
  assert.equal(new Set(items.map((item) => item.id)).size, 15)
  assert.equal(new Set(items.map((item) => item.productCode)).size, 15)
  assert.ok(items.every((item) => item.productName && item.productImage?.url && item.selectedOptions.length === 3))
  assert.ok(items.some((item) => item.fulfillmentStatus === 'partial'))
  assert.ok(items.some((item) => item.fulfillmentStatus === 'cancelled'))
  assert.equal(isAdminQuoteSampleMode(params, 'noblesse--admin-quote-responsive-ux-09rxtpa7.web.app'), true)
  assert.equal(isAdminQuoteSampleMode(params, 'localhost'), true)
  assert.equal(isAdminQuoteSampleMode(params, 'noblesse.web.app'), true)
  assert.equal(isAdminQuoteSampleMode(new URLSearchParams(), 'noblesse.web.app'), false)
  assert.equal(isAdminQuoteSampleMode(new URLSearchParams('sampleItems=10'), 'noblesse.web.app'), false)
  assert.equal(isAdminQuoteSampleMode(params, 'example.com'), false)
  assert.match(quotePage, /admin-quote-workspace\$\{sampleMode \? ' is-sample-preview' : ''\}/)
  assert.match(quotePage, /const canEditDraft = canPersist \|\| sampleMode/)
  assert.match(quotePage, /const editable = canEditDraft && !legacyLocked/)
  assert.match(quotePage, /if \(!dirty \|\| sampleMode\) return undefined/)
  assert.match(quotePage, /if \(!canPersist \|\| !editable\) return null/)
  assert.match(quotePage, /\{canPersist && editable && <button className="primary-action"/)
  assert.match(adminStyles, /\.admin-quote-workspace\.is-sample-preview button:disabled \{\s*cursor: default;/)
})

test('product operations use dedicated list and editor workflows', () => {
  const list = read('src/pages/admin/AdminProductsPage.jsx')
  const editor = read('src/pages/admin/AdminProductEditorPage.jsx')
  const detail = read('src/pages/ProductDetailPage.jsx')
  const visualShell = read('src/components/AdminVisualEditorShell.jsx')
  const styles = read('src/styles/admin-console.css')

  assert.match(list, /\/admin\/products\/new/)
  assert.doesNotMatch(list, /\/admin\/catalog\/new/)
  assert.match(list, /bulkUpdateProducts/)
  assert.match(list, /duplicateProduct/)
  for (const locale of ["'kr'", "'en'", "'jp'", "'zh-TW'"]) assert.match(editor, new RegExp(locale))
  assert.match(editor, /AdminSaveBar/)
  assert.match(editor, /getReadiness/)
  assert.match(editor, /getRegistrationChecks/)
  assert.match(editor, /publishAttempted/)
  assert.match(editor, /prices\.write/)
  assert.match(editor, /ProductDetailView/)
  assert.match(editor, /editor=\{editorBridge\}/)
  assert.match(editor, /admin-product-detail-canvas/)
  assert.match(editor, /AdminVisualEditorShell/)
  assert.match(editor, /productSections/)
  assert.match(editor, /selectProductSection/)
  for (const label of [
    '카테고리·기본 정보',
    '다국어 상품명·요약',
    '상품 이미지',
    '옵션·피어싱 규격',
    'MOQ·승인 회원 가격',
    '상세 콘텐츠',
    '공개·홈 노출 설정',
    '최종 검토',
  ]) assert.match(editor, new RegExp(label))
  assert.match(editor, /missing\.length === 0 \? 'complete' : publishAttempted \? 'error' : 'warning'/)
  assert.match(editor, /focusEditorIssue\(firstIncompleteStep\?\.id \|\| 'review'\)/)
  assert.match(editor, /setPublishAttempted\(true\)/)
  assert.doesNotMatch(editor, /openInspectorGroup === 'basic'/)
  assert.doesNotMatch(editor, /openInspectorGroup === 'trade'/)
  assert.doesNotMatch(editor, /openInspectorGroup === 'operations'/)
  assert.match(editor, /inspectorGroupByField/)
  assert.match(editor, /selectEditorField/)
  assert.match(editor, /beginInline/)
  assert.match(editor, /cancelInline/)
  assert.match(editor, /disabled=\{!canWritePrices\}/)
  assert.doesNotMatch(editor, /openPopover|renderPopover|settingsOpen/)
  assert.doesNotMatch(editor, /<Check\b/)
  assert.match(editor, /activeDevice=\{previewMode\}/)
  assert.match(editor, /onDeviceChange=\{setPreviewMode\}/)
  assert.match(visualShell, /desktop: 1440/)
  assert.match(visualShell, /tablet: 1024/)
  assert.match(visualShell, /mobile: 390/)
  assert.match(visualShell, /function AdminFixedPreviewCanvas/)
  assert.match(visualShell, /section\.statusText/)
  assert.match(visualShell, /admin-visual-editor-section-state/)
  assert.match(visualShell, /new ResizeObserver\(updateLayout\)/)
  assert.doesNotMatch(visualShell, /requestAnimationFrame/)
  assert.match(visualShell, /window\.addEventListener\('resize', updateLayout\)/)
  assert.match(visualShell, /transform: `scale\(\$\{layout\.scale\}\)`/)
  assert.match(editor, /imageDraftsToPreviewSet/)
  assert.match(editor, /wearingGuide/)
  assert.match(editor, /materialInfo/)
  assert.match(editor, /careGuide/)
  assert.match(editor, /sizeGuide/)
  assert.match(editor, /wearingLocation/)
  assert.match(editor, /saleType/)
  assert.match(editor, /closureType/)
  assert.match(editor, /settingMethod/)
  assert.match(editor, /decorationSize/)
  assert.match(editor, /ProductOptionGroupsEditor/)
  assert.match(editor, /ProductDetailBlocksEditor/)
  assert.match(editor, /상세 콘텐츠 블록/)
  assert.match(detail, /export function ProductDetailView/)
  assert.match(detail, /function ProductInlineEditor/)
  assert.match(detail, /event\.key === 'Escape'/)
  assert.match(detail, /event\.ctrlKey \|\| event\.metaKey/)
  assert.match(detail, /editor\.selectField\(field, event\.currentTarget\)/)
  assert.match(detail, /editor\.selectedField === field/)
  assert.doesNotMatch(detail, /editor\.renderPopover\(field\)/)
  assert.match(styles, /\.admin-product-detail-canvas/)
  assert.match(styles, /\.admin-visual-editor-workspace/)
  assert.match(styles, /\.admin-visual-editor-inspector/)
  assert.doesNotMatch(styles, /\.admin-product-popover|\.admin-product-settings-drawer/)
})

test('visual product editor keeps both navigation and the inspector stable without bottom sheets', () => {
  const storeShell = read('src/components/StoreShell.jsx')
  const styles = read('src/styles/admin-console.css')

  assert.match(storeShell, /visual-editor-shell/)
  assert.match(styles, /\.site-shell\.visual-editor-shell > \.site-header/)
  assert.match(styles, /\.admin-console-shell[\s\S]*?align-items: start[\s\S]*?gap: 0/)
  assert.match(styles, /html:has\(\.admin-console-shell\)[\s\S]*?overflow-x: clip/)
  assert.match(styles, /\.admin-console-topbar[\s\S]*?position: relative/)
  assert.match(styles, /\.admin-console-shell\.is-visual-editor-route[\s\S]*?grid-template-columns: 68px minmax\(0, 1fr\)/)
  assert.match(styles, /\.admin-console-sidebar[\s\S]*?align-self: start[\s\S]*?height: 100dvh[\s\S]*?position: sticky[\s\S]*?top: 0/)
  assert.match(styles, /@media \(max-width: 820px\)[\s\S]*?\.admin-console-sidebar[\s\S]*?position: static/)
  assert.match(styles, /\.admin-visual-editor-workspace[\s\S]*?grid-template-columns: 200px 340px minmax\(0, 1fr\)/)
  assert.match(styles, /\.admin-visual-editor-sections,[\s\S]*?\.admin-visual-editor-inspector[\s\S]*?overflow-y: auto/)
  assert.match(styles, /\.admin-visual-editor-canvas[\s\S]*?overflow: auto/)
  assert.match(styles, /\.admin-product-detail-canvas \.pd-page[\s\S]*?gap: 32px[\s\S]*?margin: 0[\s\S]*?padding-top: 32px[\s\S]*?width: 100%/)
  assert.match(styles, /\.admin-product-detail-canvas \.pd-breadcrumb \.pd-editor-target-trigger[\s\S]*?position: static/)
  assert.match(styles, /@media \(max-width: 1279px\) and \(min-width: 821px\)[\s\S]*?\.admin-visual-editor-inspector[\s\S]*?position: fixed[\s\S]*?transform: translateX\(-110%\)/)
  assert.match(styles, /@media \(max-width: 820px\)[\s\S]*?\.admin-visual-editor-inspector[\s\S]*?width: 100vw/)
  assert.match(styles, /@media \(max-width: 820px\)[\s\S]*?\.is-visual-editor-route \.admin-console-sidebar[\s\S]*?height: 56px[\s\S]*?position: sticky/)
  assert.match(styles, /\.is-visual-editor-route \.admin-console-sidebar nav[\s\S]*?display: flex[\s\S]*?overflow-x: auto/)
  assert.doesNotMatch(styles, /bottom:\s*0;[\s\S]{0,240}\.admin-product-popover/)
  assert.match(styles, /\.admin-visual-preview-stage[\s\S]*?position: absolute[\s\S]*?transform-origin: left top/)
  assert.match(styles, /\.admin-product-detail-canvas\.is-desktop \.pd-hero[\s\S]*?grid-template-columns: minmax\(0, 1\.42fr\) minmax\(390px, 0\.78fr\)/)
  assert.match(styles, /\.admin-product-detail-canvas\.is-desktop \.pd-gallery-grid[\s\S]*?grid-template-columns: minmax\(0, 2\.05fr\) minmax\(150px, 0\.98fr\)/)
  assert.match(styles, /\.admin-product-detail-canvas\.is-desktop \.pd-detail-gallery[\s\S]*?grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(styles, /\.admin-product-detail-canvas\.is-desktop \.pd-material-care-grid[\s\S]*?grid-template-columns: minmax\(340px, 0\.8fr\) minmax\(0, 1\.2fr\)/)
  assert.match(styles, /\.admin-product-detail-canvas\.is-desktop \.pd-process-grid[\s\S]*?grid-template-columns: repeat\(3, minmax\(160px, 1fr\)\)/)
  assert.match(styles, /\.admin-product-detail-guides[\s\S]*?display: grid/)
  assert.match(styles, /\.admin-product-spec-editor[\s\S]*?display: grid/)
})

test('quote workflow separates customer documents from internal notes and direct payment', () => {
  const adminQuote = read('src/pages/admin/AdminQuotePage.jsx')
  const adminQuoteCopy = read('src/pages/admin/adminQuoteWorkflowCopy.js')
  const adminQuoteFeature = `${adminQuote}\n${adminQuoteCopy}`
  const buyerQuotes = read('src/pages/MyInquiriesPage.jsx')

  assert.match(adminQuote, /issueQuote/)
  assert.match(adminQuoteFeature, /새 버전 발행/)
  assert.match(adminQuoteFeature, /내부 메모/)
  assert.match(adminQuoteFeature, /구매자 화면과 PDF에는 표시되지 않습니다/)
  assert.match(adminQuoteFeature, /1\. 물건 확인·챙기기/)
  assert.match(adminQuoteFeature, /취소·수량 부족 품목/)
  assert.match(adminQuoteFeature, /준비 수량은 0 이상이며 원 요청 수량을 넘을 수 없습니다/)
  assert.match(adminQuoteFeature, /준비 완료/)
  assert.match(adminQuoteFeature, /사진·옵션·수량이 포함된 상품 준비 PDF/)
  assert.match(adminQuote, /item\.productImage\?\.url/)
  assert.match(adminQuote, /admin-picking-product-image/)
  assert.doesNotMatch(adminQuoteCopy, /SNS|피킹/)
  assert.match(adminQuote, /updateQuoteWorkflow/)
  assert.match(adminQuote, /quotes\.write/)
  assert.doesNotMatch(buyerQuotes, /decideInquiryQuote/)
  assert.match(buyerQuotes, /상품 준비 현황/)
  assert.match(buyerQuotes, /상품 준비 견적서에서 선택 옵션과 준비·취소 수량을 확인한 뒤/)
  assert.match(buyerQuotes, /사이트에서는 주문이나 결제가 생성되지 않습니다/)
  assert.doesNotMatch(adminQuote, /checkout|createOrder|paymentIntent/i)
})

test('admin quote preparation uses responsive work cards and one contextual action path', () => {
  const quotePage = read('src/pages/admin/AdminQuotePage.jsx')
  const adminShell = read('src/components/AdminShell.jsx')
  const storeShell = read('src/components/StoreShell.jsx')
  const appStyles = read('src/App.css')
  const adminStyles = read('src/styles/admin-console.css')

  assert.match(quotePage, /className="admin-picking-list"/)
  assert.match(quotePage, /className=\{`admin-picking-item fulfillment-/)
  assert.match(quotePage, /className="admin-picking-options"/)
  assert.match(quotePage, /const cancelled = Math\.max\(requested - prepared, 0\)/)
  assert.match(quotePage, /const needsCancellationReason = \['partial', 'cancelled'\]\.includes\(item\.fulfillmentStatus\)/)
  assert.doesNotMatch(quotePage, /className="admin-picking-table"/)
  assert.doesNotMatch(quotePage, /AdminSaveBar/)

  assert.match(quotePage, /className="admin-quote-workflow-compact"/)
  assert.match(quotePage, /className="admin-quote-additional-settings"/)
  assert.match(quotePage, /className="admin-editor-section admin-quote-history-section"/)
  assert.match(quotePage, /className="admin-quote-task-bar"/)
  assert.match(quotePage, /orderDocuments\(documents, quote\?\.currentDocumentId\)/)
  assert.match(quotePage, /groupWorkflowHistory\(history\)/)
  assert.match(quotePage, /entry\.eventType === 'workflow'/)

  assert.match(adminShell, /className="admin-mobile-appbar"/)
  assert.match(adminShell, /className="admin-mobile-bottom-nav"/)
  assert.match(storeShell, /admin-route-shell/)
  assert.match(appStyles, /\.site-shell\.admin-route-shell > \.top-marquee/)
  assert.match(appStyles, /\.site-shell\.admin-route-shell > \.site-header/)
  assert.match(adminStyles, /\.admin-picking-item \{[\s\S]*?grid-template-columns: minmax\(280px, 1\.35fr\) minmax\(280px, 0\.9fr\) minmax\(180px, 0\.55fr\)/)
  assert.match(adminStyles, /\.admin-picking-identity > code[\s\S]*?overflow-wrap: anywhere/)
  assert.match(adminStyles, /\.admin-picking-shortcuts button,[\s\S]*?min-height: 44px/)
  assert.match(adminStyles, /@media \(max-width: 820px\)[\s\S]*?\.admin-picking-item \{[\s\S]*?display: block/)
})

test('admin console uses restrained neutral styling without gradients', () => {
  const styles = read('src/styles/admin-console.css')
  assert.doesNotMatch(styles, /linear-gradient|radial-gradient/)
  assert.match(styles, /#2a234f/i)
  assert.match(styles, /#ff8fa9/i)
  assert.match(styles, /@media \(max-width: 620px\)/)
})
