import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const read = (path) => readFileSync(join(process.cwd(), path), 'utf8')

test('product operations use dedicated list and editor workflows', () => {
  const list = read('src/pages/admin/AdminProductsPage.jsx')
  const editor = read('src/pages/admin/AdminProductEditorPage.jsx')
  const detail = read('src/pages/ProductDetailPage.jsx')
  const visualShell = read('src/components/AdminVisualEditorShell.jsx')
  const styles = read('src/styles/admin-console.css')

  assert.match(list, /\/admin\/products\/new/)
  assert.doesNotMatch(list, /\/admin\/catalog\/new/)
  assert.match(list, /bulkUpdateProducts/)
  assert.match(list, /duplicateProduct/)
  for (const locale of ["'kr'", "'en'", "'jp'", "'zh-TW'"]) assert.match(editor, new RegExp(locale))
  assert.match(editor, /AdminSaveBar/)
  assert.match(editor, /getReadiness/)
  assert.match(editor, /prices\.write/)
  assert.match(editor, /ProductDetailView/)
  assert.match(editor, /editor=\{editorBridge\}/)
  assert.match(editor, /admin-product-detail-canvas/)
  assert.match(editor, /AdminVisualEditorShell/)
  assert.match(editor, /productSections/)
  assert.match(editor, /selectProductSection/)
  assert.match(editor, /inspectorGroupByField/)
  assert.match(editor, /selectEditorField/)
  assert.match(editor, /beginInline/)
  assert.match(editor, /cancelInline/)
  assert.match(editor, /disabled=\{!canWritePrices\}/)
  assert.doesNotMatch(editor, /openPopover|renderPopover|settingsOpen/)
  assert.doesNotMatch(editor, /<Check\b/)
  assert.match(editor, /activeDevice=\{previewMode\}/)
  assert.match(editor, /onDeviceChange=\{setPreviewMode\}/)
  assert.match(visualShell, /desktop: 1440/)
  assert.match(visualShell, /tablet: 1024/)
  assert.match(visualShell, /mobile: 390/)
  assert.match(visualShell, /function AdminFixedPreviewCanvas/)
  assert.match(visualShell, /new ResizeObserver\(updateLayout\)/)
  assert.doesNotMatch(visualShell, /requestAnimationFrame/)
  assert.match(visualShell, /window\.addEventListener\('resize', updateLayout\)/)
  assert.match(visualShell, /transform: `scale\(\$\{layout\.scale\}\)`/)
  assert.match(editor, /imageDraftsToPreviewSet/)
  assert.match(editor, /wearingGuide/)
  assert.match(editor, /materialInfo/)
  assert.match(editor, /careGuide/)
  assert.match(editor, /sizeGuide/)
  assert.match(editor, /wearingLocation/)
  assert.match(editor, /saleType/)
  assert.match(editor, /closureType/)
  assert.match(editor, /settingMethod/)
  assert.match(editor, /decorationSize/)
  assert.match(editor, /1번은 대표 이미지, 2~3번은 상단 보조 이미지, 4번 이후는 상세 이미지/)
  assert.match(detail, /export function ProductDetailView/)
  assert.match(detail, /function ProductInlineEditor/)
  assert.match(detail, /event\.key === 'Escape'/)
  assert.match(detail, /event\.ctrlKey \|\| event\.metaKey/)
  assert.match(detail, /editor\.selectField\(field, event\.currentTarget\)/)
  assert.match(detail, /editor\.selectedField === field/)
  assert.doesNotMatch(detail, /editor\.renderPopover\(field\)/)
  assert.match(styles, /\.admin-product-detail-canvas/)
  assert.match(styles, /\.admin-visual-editor-workspace/)
  assert.match(styles, /\.admin-visual-editor-inspector/)
  assert.doesNotMatch(styles, /\.admin-product-popover|\.admin-product-settings-drawer/)
})

test('visual product editor keeps both navigation and the inspector stable without bottom sheets', () => {
  const storeShell = read('src/components/StoreShell.jsx')
  const styles = read('src/styles/admin-console.css')

  assert.match(storeShell, /visual-editor-shell/)
  assert.match(styles, /\.site-shell\.visual-editor-shell > \.site-header/)
  assert.match(styles, /\.admin-console-shell[\s\S]*?align-items: start[\s\S]*?gap: 0/)
  assert.match(styles, /html:has\(\.admin-console-shell\)[\s\S]*?overflow-x: clip/)
  assert.match(styles, /\.admin-console-topbar[\s\S]*?position: relative/)
  assert.match(styles, /\.admin-console-shell\.is-visual-editor-route[\s\S]*?grid-template-columns: 68px minmax\(0, 1fr\)/)
  assert.match(styles, /\.admin-console-sidebar[\s\S]*?align-self: start[\s\S]*?height: 100dvh[\s\S]*?position: sticky[\s\S]*?top: 0/)
  assert.match(styles, /@media \(max-width: 820px\)[\s\S]*?\.admin-console-sidebar[\s\S]*?position: static/)
  assert.match(styles, /\.admin-visual-editor-workspace[\s\S]*?grid-template-columns: 200px 340px minmax\(0, 1fr\)/)
  assert.match(styles, /\.admin-visual-editor-sections,[\s\S]*?\.admin-visual-editor-inspector[\s\S]*?overflow-y: auto/)
  assert.match(styles, /\.admin-visual-editor-canvas[\s\S]*?overflow: auto/)
  assert.match(styles, /\.admin-product-detail-canvas \.pd-page[\s\S]*?gap: 32px[\s\S]*?margin: 0[\s\S]*?padding-top: 32px[\s\S]*?width: 100%/)
  assert.match(styles, /\.admin-product-detail-canvas \.pd-breadcrumb \.pd-editor-target-trigger[\s\S]*?position: static/)
  assert.match(styles, /@media \(max-width: 1279px\) and \(min-width: 821px\)[\s\S]*?\.admin-visual-editor-inspector[\s\S]*?position: fixed[\s\S]*?transform: translateX\(-110%\)/)
  assert.match(styles, /@media \(max-width: 820px\)[\s\S]*?\.admin-visual-editor-inspector[\s\S]*?width: 100vw/)
  assert.match(styles, /@media \(max-width: 820px\)[\s\S]*?\.is-visual-editor-route \.admin-console-sidebar[\s\S]*?height: 56px[\s\S]*?position: sticky/)
  assert.match(styles, /\.is-visual-editor-route \.admin-console-sidebar nav[\s\S]*?display: flex[\s\S]*?overflow-x: auto/)
  assert.doesNotMatch(styles, /bottom:\s*0;[\s\S]{0,240}\.admin-product-popover/)
  assert.match(styles, /\.admin-visual-preview-stage[\s\S]*?position: absolute[\s\S]*?transform-origin: left top/)
  assert.match(styles, /\.admin-product-detail-canvas\.is-desktop \.pd-hero[\s\S]*?grid-template-columns: minmax\(0, 1\.42fr\) minmax\(390px, 0\.78fr\)/)
  assert.match(styles, /\.admin-product-detail-canvas\.is-desktop \.pd-gallery-grid[\s\S]*?grid-template-columns: minmax\(0, 2\.05fr\) minmax\(150px, 0\.98fr\)/)
  assert.match(styles, /\.admin-product-detail-canvas\.is-desktop \.pd-detail-gallery[\s\S]*?grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(styles, /\.admin-product-detail-canvas\.is-desktop \.pd-material-care-grid[\s\S]*?grid-template-columns: minmax\(340px, 0\.8fr\) minmax\(0, 1\.2fr\)/)
  assert.match(styles, /\.admin-product-detail-canvas\.is-desktop \.pd-process-grid[\s\S]*?grid-template-columns: repeat\(3, minmax\(160px, 1fr\)\)/)
  assert.match(styles, /\.admin-product-detail-guides[\s\S]*?display: grid/)
  assert.match(styles, /\.admin-product-spec-editor[\s\S]*?display: grid/)
})

test('quote workflow separates customer documents from internal notes and direct payment', () => {
  const adminQuote = read('src/pages/admin/AdminQuotePage.jsx')
  const buyerQuotes = read('src/pages/MyInquiriesPage.jsx')

  assert.match(adminQuote, /issueQuote/)
  assert.match(adminQuote, /새 버전 발행/)
  assert.match(adminQuote, /내부 메모/)
  assert.match(adminQuote, /고객 화면과 PDF에는 표시되지 않습니다/)
  assert.match(adminQuote, /quotes\.write/)
  assert.match(buyerQuotes, /decideInquiryQuote/)
  assert.match(buyerQuotes, /주문이나 결제를 만들지 않으며/)
  assert.doesNotMatch(adminQuote, /checkout|createOrder|paymentIntent/i)
})

test('admin console uses restrained neutral styling without gradients', () => {
  const styles = read('src/styles/admin-console.css')
  assert.doesNotMatch(styles, /linear-gradient|radial-gradient/)
  assert.match(styles, /#2a234f/i)
  assert.match(styles, /#ff8fa9/i)
  assert.match(styles, /@media \(max-width: 620px\)/)
})
