import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

const readSource = (path) => readFileSync(join(process.cwd(), path), 'utf8')

test('product detail keeps Noblesse inquiry wording and avoids direct purchase CTA copy', () => {
  const source = readSource('src/pages/ProductDetailPage.jsx')

  assert.match(source, /Add to Inquiry List/)
  assert.match(source, /Request quote for this product/)
  assert.match(source, /이 상품으로 견적 요청/)
  assert.match(source, /商品詢價/)
  assert.doesNotMatch(source, /Buy Now|Checkout|Payment|Order Now|Add to Cart|장바구니|바로 구매|결제/)
})

test('product detail gates buyer price and MOQ behind approved buyer or admin price book state', () => {
  const source = readSource('src/pages/ProductDetailPage.jsx')

  assert.match(source, /const canUseTradeTerms = Boolean\(isApproved && price && approvedAmount !== null\)/)
  assert.match(source, /const canRequestProductQuote = Boolean\(isApproved && product\)/)
  assert.match(source, /const canViewAdminPrices = Boolean\(isAdmin && adminPriceBooks\.length > 0\)/)
  assert.match(source, /const requestMoq = canUseTradeTerms \? price\.moq : product\?\.moqDefault \|\| 1/)
  assert.match(source, /const visibleMoq = canUseTradeTerms \? price\.moq : canRequestProductQuote \? requestMoq : canViewAdminPrices \? adminPriceBooks\[0\]\?\.moq : null/)
  assert.match(source, /const openGuestLoginModal = \(\) =>/)
  assert.match(source, /new CustomEvent\('noblesse:open-login-modal'\)/)
  assert.match(source, /viewerState === 'guest'[\s\S]*?<button aria-haspopup="dialog" className="pd-secondary-action"/)
  assert.match(source, /<Link className="pd-secondary-action" to=\{toLocalePath\(accessLink\)\}>/)
})

test('shared product detail editor uses active locale values without storefront fallback', () => {
  const source = readSource('src/pages/ProductDetailPage.jsx')

  assert.match(source, /export function ProductDetailView/)
  assert.match(source, /const productName = editor \? editor\.values\.name/)
  assert.match(source, /const description = editor \? editor\.values\.summary/)
  assert.match(source, /blocks=\{detailBlocks\}/)
  assert.match(source, /editor=\{editor\}/)
  assert.match(readSource('src/components/ProductDetailBlocks.jsx'), /getLocalizedDetailBlockCopy\(block, locale, !editor\)/)
  assert.match(source, /disabled=\{Boolean\(editor\)\}/)
  assert.match(source, /if \(editor \|\| missingRequiredOptions\.length > 0\) return/)
})

test('product detail can submit a direct product inquiry through the commerce helper', () => {
  const source = readSource('src/pages/ProductDetailPage.jsx')
  const commerce = readSource('src/commerce/CommerceContext.jsx')

  assert.match(source, /submitProductInquiry/)
  assert.match(source, /submitSelectedProductInquiry/)
  assert.match(source, /requestMemo: directMemo\.trim\(\)/)
  assert.match(source, /getInquiryRoutePath\(directInquiry\)/)
  assert.match(commerce, /const submitProductInquiry = async/)
  assert.match(commerce, /buyerApi\.createInquiry/)
  assert.match(commerce, /productCode: product\.code/)
})

test('product detail records a recent product view without blocking product rendering', () => {
  const source = readSource('src/pages/ProductDetailPage.jsx')

  assert.match(source, /recordRecentProductView/)
  assert.match(source, /recordedProductCodeRef/)
  assert.match(source, /recordRecentProductView\(productCode\)\.catch/)
  assert.match(source, /if \(!productCode \|\| !isApproved \|\| isAdmin/)
})

test('product detail uses scoped pd layout and related products are selected from relevant product signals', () => {
  const source = readSource('src/pages/ProductDetailPage.jsx')
  const styles = readSource('src/App.css')

  assert.match(source, /className="content pd-page"/)
  assert.match(source, /className="pd-section-nav"/)
  assert.match(source, /id="pd-overview"/)
  assert.match(source, /id="pd-specification"/)
  assert.match(source, /id="pd-material"/)
  assert.match(source, /const detailBlocks = Array\.isArray\(product\.detailContent\?\.blocks\)/)
  assert.match(source, /<ProductDetailBlocks/)
  assert.doesNotMatch(source, /galleryImages\.slice\(3\)/)
  assert.match(source, /const structureRows =/)
  assert.match(source, /const keyFacts =/)
  assert.match(source, /className="pd-key-facts"/)
  assert.match(source, /pd-material-care-grid/)
  assert.match(source, /className="pd-shipping-note"/)
  assert.match(source, /const getRelatedProducts/)
  assert.match(source, /item\.productId !== product\.productId/)
  assert.match(source, /getProductTaxonomy\(product\)/)
  assert.match(source, /itemTaxonomy\.structures\.some/)
  assert.match(source, /score \+= 8/)
  assert.match(source, /\/products\?structure=barbell/)
  assert.doesNotMatch(source, /products\.slice\(0, 4\)/)
  assert.match(styles, /\.pd-hero/)
  assert.match(styles, /\.pd-editorial/)
  assert.match(styles, /\.pd-mobile-action/)
  assert.match(styles, /\.pd-direct-inquiry-form/)
  assert.match(styles, /\.pd-detail-gallery/)
  assert.match(styles, /\.pd-content-blocks/)
  assert.match(styles, /\.pd-content-image-text/)
  assert.match(styles, /\.pd-material-care-grid/)
  assert.match(styles, /\.pd-process-grid[\s\S]*?repeat\(3,/)
})

test('product detail offers desktop mouse hover magnification without changing touch or editor behavior', () => {
  const source = readSource('src/pages/ProductDetailPage.jsx')
  const styles = readSource('src/App.css')

  assert.match(source, /createProductImageMagnifierFrame/)
  assert.match(source, /const canMagnify = Boolean\(!editor && selectedImage\?\.zoomSrc\)/)
  assert.match(source, /onMouseEnter=\{updateMagnifier\}/)
  assert.match(source, /onMouseMove=\{updateMagnifier\}/)
  assert.match(source, /className="pd-image-magnifier-lens"/)
  assert.match(source, /className="pd-image-zoom-panel"/)
  assert.match(source, /magnifierLensRef/)
  assert.match(source, /magnifierRectRef\.current \|\| event\.currentTarget\.getBoundingClientRect\(\)/)
  assert.match(source, /lens\.style\.transform = `translate3d/)
  assert.match(source, /stage\.style\.transform = `translate3d/)
  assert.match(source, /height: `\$\{frame\.render\.height\}px`/)
  assert.match(source, /width: `\$\{frame\.render\.width\}px`/)
  assert.doesNotMatch(source, /setMagnifierFrame/)
  assert.match(source, /selectedImage\.zoomSrc/)
  assert.match(source, /onMouseLeave=\{stopMagnifier\}/)
  assert.match(styles, /@media \(min-width: 1181px\) and \(hover: hover\) and \(pointer: fine\)/)
  assert.match(styles, /\.pd-image-zoom-panel[\s\S]*?position: fixed/)
  assert.match(styles, /\.pd-image-zoom-panel\.is-active[\s\S]*?display: block/)
  assert.match(styles, /\.pd-image-magnifier-lens,[\s\S]*?\.pd-image-zoom-panel[\s\S]*?display: none/)
})

test('product gallery uses one square hero image with thumbnails below', () => {
  const source = readSource('src/pages/ProductDetailPage.jsx')
  const styles = readSource('src/App.css')
  const adminStyles = readSource('src/styles/admin-console.css')

  assert.match(source, /className="pd-gallery is-single"/)
  assert.doesNotMatch(source, /secondaryImages|className="pd-side-images"/)
  assert.match(source, /className="pd-thumbs"/)
  assert.match(source, /editor\?\.selectImage\?\.\(image\.id\)/)
  assert.match(styles, /\.pd-main-image \{[\s\S]*?aspect-ratio: 1;[\s\S]*?min-height: 0;/)
  assert.match(styles, /\.pd-main-image img \{[\s\S]*?min-height: 0;/)
  assert.match(adminStyles, /\.admin-product-detail-canvas\.is-desktop \.pd-main-image \{[\s\S]*?aspect-ratio: 1;[\s\S]*?min-height: 0;/)
})

test('legacy product photos are distributed beside overview, specification, and care copy', () => {
  const source = readSource('src/pages/ProductDetailPage.jsx')
  const blocks = readSource('src/components/ProductDetailBlocks.jsx')
  const styles = readSource('src/App.css')
  const adminStyles = readSource('src/styles/admin-console.css')

  assert.match(source, /includeOverview: visibleDetailBlocks\.length === 0/)
  assert.match(source, /reservedImageIds: reservedDetailImageIds/)
  assert.match(source, /failedContextImageKeys/)
  assert.match(source, /legacyOverviewImage=\{detailImageSlots\.overview\}/)
  assert.match(source, /additionalImages=\{detailImageSlots\.additional\}/)
  assert.match(source, /onLegacyOverviewImageError=\{handleContextImageError\}/)
  assert.match(source, /className="pd-spec-image" image=\{detailImageSlots\.specification\}/)
  assert.match(source, /className="pd-material-context-image" image=\{detailImageSlots\.material\}/)
  assert.match(blocks, /is-imageLeft is-legacy-story/)
  assert.match(blocks, /function AdaptiveDetailGallery/)
  assert.match(blocks, /pd-story-gallery/)
  assert.match(blocks, /NOBLESSE DETAILS/)
  assert.match(blocks, /PHOTO STORY/)
  assert.match(blocks, /pd-story-image-number/)
  assert.doesNotMatch(blocks, /pd-story-gallery[\s\S]*is-featured/)
  assert.doesNotMatch(blocks, /is-legacy-gallery|galleryImages\.slice\(1\)/)
  assert.match(styles, /\.pd-story-gallery-heading/)
  assert.match(styles, /\.pd-story-gallery\.is-pair figure:nth-child\(2\)/)
  assert.match(styles, /\.pd-spec-layout\.has-context-image/)
  assert.match(styles, /\.pd-material-care-grid\.has-context-image/)
  assert.match(adminStyles, /\.admin-product-detail-canvas\.is-mobile \.pd-content-image-text/)
  assert.match(adminStyles, /\.admin-product-detail-canvas\.is-mobile \.pd-story-gallery/)
})

test('product detail uses premium section framing without changing the B2B flow', () => {
  const source = readSource('src/pages/ProductDetailPage.jsx')
  const blocks = readSource('src/components/ProductDetailBlocks.jsx')
  const styles = readSource('src/App.css')

  assert.match(source, /pd-detail-story" data-section="01"/)
  assert.match(source, /pd-specification-section" data-section="02"/)
  assert.match(source, /pd-material-care-section" data-section="03"/)
  assert.match(source, /pd-delivery-section" data-section=/)
  assert.match(source, /pd-process-layout/)
  assert.match(source, /pd-process-list/)
  assert.doesNotMatch(source, /quoteWorkflowLead: ['"`][^\n]*(?:B2B|b2b)/)
  assert.match(blocks, /className="pd-story-ornament"/)
  assert.match(styles, /\.pd-editorial\[data-section\]::before/)
  assert.match(styles, /\.pd-delivery-section \{/)
  assert.match(styles, /\.site-shell:not\(\.admin-route-shell\) \.pd-delivery-section \{[\s\S]*background: #f7f2ee;/)
  assert.match(styles, /\.site-shell:not\(\.admin-route-shell\) \.pd-delivery-section \.pd-process-grid::before/)
  assert.match(styles, /\.site-shell:not\(\.admin-route-shell\) \.pd-delivery-section \.pd-process-grid strong \{[\s\S]*border-radius: 50%;/)
  assert.match(styles, /\.site-shell:not\(\.admin-route-shell\) \.pd-delivery-section \.pd-process-layout \{[\s\S]*grid-template-columns:/)
  assert.match(styles, /\.site-shell:not\(\.admin-route-shell\) \.pd-delivery-section \.pd-process-list li \{[\s\S]*grid-template-columns:/)
  assert.match(styles, /\.pd-key-facts dl > div::before/)
  assert.doesNotMatch(source, /buy now|checkout|payment/i)
})

test('product detail exposes piercing-specific structure without fixed promotional filler', () => {
  const source = readSource('src/pages/ProductDetailPage.jsx')

  for (const field of ['gauge', 'barLength', 'postLength', 'innerDiameter', 'barThickness', 'stoneType', 'closureType', 'settingMethod', 'plating', 'finish']) {
    assert.match(source, new RegExp(`productSpecs\\.${field}`))
  }
  assert.match(source, /productTaxonomy\.wearingLocation/)
  assert.match(source, /productTaxonomy\.saleType/)
  assert.match(source, /productDetailContent\.wearingGuide/)
  assert.match(source, /productDetailContent\.materialInfo/)
  assert.match(source, /productDetailContent\.careGuide/)
  assert.match(source, /productDetailContent\.sizeGuide/)
  assert.doesNotMatch(source, /className="pd-assurance-strip"/)
  assert.doesNotMatch(source, /className="pd-buyer-points"/)
})
