export const delegableAdminPermissions = [
  'dashboard.read',
  'buyers.read',
  'buyers.sensitive.read',
  'buyers.review',
  'buyers.suspend',
  'inquiries.read',
  'inquiries.manage',
  'catalog.read',
  'catalog.write',
  'catalog.publish',
  'prices.read',
  'prices.write',
  'quotes.read',
  'quotes.write',
  'analytics.read',
  'admins.read',
  'audit.read',
]

export const adminPermissionLabels = {
  kr: {
    'dashboard.read': '대시보드 보기',
    'buyers.read': '거래처 보기',
    'buyers.sensitive.read': '거래처 민감 정보 보기',
    'buyers.review': '거래처 심사',
    'buyers.suspend': '거래처 정지',
    'inquiries.read': '문의 보기',
    'inquiries.manage': '문의 관리',
    'catalog.read': '카탈로그 보기',
    'catalog.write': '카탈로그 작성',
    'catalog.publish': '카탈로그 공개',
    'prices.read': '가격 보기',
    'prices.write': '가격 작성',
    'quotes.read': '견적 보기',
    'quotes.write': '견적 작성',
    'analytics.read': '분석 보기',
    'admins.read': '관리자 보기',
    'audit.read': '감사 로그 보기',
  },
  en: {
    'dashboard.read': 'View dashboard',
    'buyers.read': 'View buyers',
    'buyers.sensitive.read': 'View sensitive buyer info',
    'buyers.review': 'Review buyers',
    'buyers.suspend': 'Suspend buyers',
    'inquiries.read': 'View inquiries',
    'inquiries.manage': 'Manage inquiries',
    'catalog.read': 'View catalog',
    'catalog.write': 'Edit catalog',
    'catalog.publish': 'Publish catalog',
    'prices.read': 'View prices',
    'prices.write': 'Edit prices',
    'quotes.read': 'View quotes',
    'quotes.write': 'Edit quotes',
    'analytics.read': 'View analytics',
    'admins.read': 'View admins',
    'audit.read': 'View audit logs',
  },
  jp: {
    'dashboard.read': 'ダッシュボード表示',
    'buyers.read': '取引先表示',
    'buyers.sensitive.read': '取引先の機密情報表示',
    'buyers.review': '取引先審査',
    'buyers.suspend': '取引先停止',
    'inquiries.read': 'お問い合わせ表示',
    'inquiries.manage': 'お問い合わせ管理',
    'catalog.read': 'カタログ表示',
    'catalog.write': 'カタログ編集',
    'catalog.publish': 'カタログ公開',
    'prices.read': '価格表示',
    'prices.write': '価格編集',
    'quotes.read': '見積もり表示',
    'quotes.write': '見積もり編集',
    'analytics.read': '分析表示',
    'admins.read': '管理者表示',
    'audit.read': '監査ログ表示',
  },
  cn: {
    'dashboard.read': '查看仪表板',
    'buyers.read': '查看客户',
    'buyers.sensitive.read': '查看客户敏感信息',
    'buyers.review': '审核客户',
    'buyers.suspend': '停用客户',
    'inquiries.read': '查看询价',
    'inquiries.manage': '管理询价',
    'catalog.read': '查看目录',
    'catalog.write': '编辑目录',
    'catalog.publish': '发布目录',
    'prices.read': '查看价格',
    'prices.write': '编辑价格',
    'quotes.read': '查看报价',
    'quotes.write': '编辑报价',
    'analytics.read': '查看分析',
    'admins.read': '查看管理员',
    'audit.read': '查看审计日志',
  },
}

export function getAdminPermissionLabel(permissionKey, locale = 'en') {
  return adminPermissionLabels[locale]?.[permissionKey] || adminPermissionLabels.en[permissionKey] || permissionKey
}
