import { FilePlus2, Minus, Plus, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useCommerce } from '../commerce/commerceStore'
import { formatMoney } from '../utils/commerce'

export function InquiryListPage() {
  const { buyer, estimatedTotal, inquiryRows, isApproved, removeInquiryItem, totalQuantity, updateInquiryQuantity } = useCommerce()
  if (!isApproved) return <main className="content"><div className="approval-page"><FilePlus2 size={25} /><h1>Inquiry List is available after Buyer Approval.</h1><p>Browse the catalog while your wholesale access is being reviewed.</p></div></main>
  return <main className="content"><div className="page-title"><div><p>INQUIRY LIST</p><h1>Selected jewelry</h1></div><span>{inquiryRows.length} items / {totalQuantity} pcs</span></div><section className="inquiry-layout"><div className="inquiry-items">{inquiryRows.map((row) => <article className="inquiry-row" key={row.product.productId}><div className={`mini-image tone-${row.product.tone}`} /><div><strong>{row.product.nameEn}</strong><span>{row.product.code} / MOQ {row.price.moq}</span></div><div className="quantity"><button type="button" aria-label="Decrease quantity" onClick={() => updateInquiryQuantity(row.product.productId, row.quantity - row.price.moq)}><Minus size={14} /></button><input value={row.quantity} type="number" onChange={(event) => updateInquiryQuantity(row.product.productId, event.target.value)} /><button type="button" aria-label="Increase quantity" onClick={() => updateInquiryQuantity(row.product.productId, row.quantity + row.price.moq)}><Plus size={14} /></button></div><b>{formatMoney(row.subtotal, buyer.currency)}</b><button className="remove" type="button" aria-label="Remove item" onClick={() => removeInquiryItem(row.product.productId)}><Trash2 size={16} /></button></article>)}</div><aside className="inquiry-summary"><h2>Inquiry summary</h2><span>Estimated total</span><strong>{formatMoney(estimatedTotal, buyer.currency)}</strong><small>Final availability and pricing will be confirmed by Noblesse.</small><Link to={inquiryRows.length ? '/request-quote' : '/inquiry-list'} className={inquiryRows.length ? '' : 'disabled'}>Request Quote</Link></aside></section></main>
}
