const archiveNameTerms = [
  ['부자재', 'Parts', 'パーツ', '配件'],
  ['C자나뭇가지', 'C-Shaped Branch', 'C字型ブランチ', 'C字型樹枝'],
  ['화이트오팔네잎', 'White Opal Four-Leaf', 'ホワイトオパール四つ葉', '白色蛋白石四葉'],
  ['블루오팔네잎', 'Blue Opal Four-Leaf', 'ブルーオパール四つ葉', '藍色蛋白石四葉'],
  ['자주도마뱀', 'Purple Lizard', 'パープルリザード', '紫色蜥蜴'],
  ['실타레소', 'Small Thread Spool', 'スモール糸巻き', '小線軸'],
  ['클로버만', 'Clover Only', 'クローバー単品', '四葉草單款'],
  ['한레드큐', 'Single Red Cubic Zirconia', 'シングルレッドキュービックジルコニア', '單顆紅色鋯石'],
  ['한ab큐', 'Single AB Cubic Zirconia', 'シングルABキュービックジルコニア', '單顆AB鋯石'],
  ['블오초', 'Blue Orange Green', 'ブルー・オレンジ・グリーン', '藍橘綠'],
  ['핑오', 'Pink Orange', 'ピンク・オレンジ', '粉橘'],
  ['문스타', 'Moon Star', 'ムーンスター', '月亮星星'],
  ['별밤', 'Starry Night', '星空', '星夜'],
  ['크리스탈', 'Crystal', 'クリスタル', '水晶'],
  ['해바라기', 'Sunflower', 'ひまわり', '向日葵'],
  ['초미니', 'Extra-Mini', '極小', '超迷你'],
  ['찐눈꽃', 'Snowflake', 'スノーフレーク', '雪花'],
  ['양쪽날개', 'Double Wings', 'ダブルウィング', '雙翼'],
  ['엔젤윙', 'Angel Wings', 'エンジェルウィング', '天使翅膀'],
  ['자붂음', 'Straight Bundle', 'ストレート束', '直桿組'],
  ['반접', 'Half-Fold', 'ハーフフォールド', '半折'],
  ['실타레', 'Thread Spool', '糸巻き', '線軸'],
  ['완두콩', 'Pea Pod', 'エンドウ豆', '豌豆莢'],
  ['코뚜레', 'Nose Ring', 'ノーズリング', '鼻環'],
  ['프레첼', 'Pretzel', 'プレッツェル', '蝴蝶脆餅'],
  ['꽈베기', 'Twist', 'ツイスト', '麻花扭紋'],
  ['나뭇가지', 'Branch', 'ブランチ', '樹枝'],
  ['투톤', 'Two-Tone', 'ツートーン', '雙色'],
  ['매듭', 'Knot', 'ノット', '繩結'],
  ['뾰족', 'Pointed', 'ポインテッド', '尖頭'],
  ['한방', 'Single Stone', '一粒石', '單石'],
  ['삼색', 'Three-Color', 'スリーカラー', '三色'],
  ['크로바', 'Clover', 'クローバー', '四葉草'],
  ['트윈', 'Twin', 'ツイン', '雙款'],
  ['마르게리타', 'Daisy', 'マーガレット', '雛菊'],
  ['엮음', 'Braided', 'ブレイド', '編織'],
  ['텝', 'Threaded Tab', 'スレッドタブ', '螺紋接頭'],
  ['번', 'No.', '番', '號'],
  ['다이아', 'Diamond', 'ダイヤモンド', '鑽石'],
  ['귀족', 'Noblesse', 'ノブレス', '貴族'],
  ['은하', 'Galaxy', 'ギャラクシー', '銀河'],
  ['아쿠아', 'Aqua', 'アクア', '水藍'],
  ['타원', 'Oval', 'オーバル', '橢圓'],
  ['토성', 'Saturn', '土星', '土星'],
  ['티아라', 'Tiara', 'ティアラ', '皇冠頭飾'],
  ['이슬', 'Dewdrop', 'しずく', '露珠'],
  ['방울', 'Drop', 'ドロップ', '吊墜'],
  ['연꽃', 'Lotus', 'ロータス', '蓮花'],
  ['뽀드', 'Soft', 'ソフト', '柔和'],
  ['웨이브', 'Wave', 'ウェーブ', '波浪'],
  ['바다', 'Sea', 'シー', '海洋'],
  ['속빈', 'Hollow', 'ホロー', '鏤空'],
  ['초승', 'Crescent', 'クレセント', '新月'],
  ['클립', 'Clip', 'クリップ', '夾扣'],
  ['도마뱀', 'Lizard', 'リザード', '蜥蜴'],
  ['중심', 'Center', 'センター', '中心'],
  ['샤인', 'Shine', 'シャイン', '閃耀'],
  ['피어싱', 'Piercing', 'ピアス', '穿孔飾品'],
  ['밧줄', 'Rope', 'ロープ', '繩索'],
  ['납작', 'Flat', 'フラット', '扁平'],
  ['입술', 'Lips', 'リップ', '嘴唇'],
  ['고양이', 'Cat', 'キャット', '貓咪'],
  ['우산', 'Umbrella', 'アンブレラ', '雨傘'],
  ['해골', 'Skull', 'スカル', '骷髏'],
  ['덤벨', 'Dumbbell', 'ダンベル', '啞鈴'],
  ['네잎', 'Four-Leaf', '四つ葉', '四葉'],
  ['두발', 'Two-Prong', '二本爪', '雙爪'],
  ['두잎', 'Two-Leaf', '二つ葉', '雙葉'],
  ['가지', 'Assorted', 'アソート', '多款'],
  ['멀티', 'Multi', 'マルチ', '多色'],
  ['보라', 'Purple', 'パープル', '紫色'],
  ['래드', 'Red', 'レッド', '紅色'],
  ['문', 'Moon', 'ムーン', '月亮'],
  ['좌', 'Left', '左', '左'],
  ['우', 'Right', '右', '右'],
  ['여러', 'Mixed', 'ミックス', '混合'],
  ['자주', 'Purple', 'パープル', '紫色'],
  ['다섯', 'Five', 'ファイブ', '五'],
  ['중', 'Medium', 'ミディアム', '中'],
  ['콩', 'Bean', 'ビーンズ', '豆'],
  ['로즈', 'Rose', 'ローズ', '玫瑰'],
  ['금', 'Gold', 'ゴールド', '金色'],
  ['블루', 'Blue', 'ブルー', '藍色'],
  ['지문', 'Fingerprint', 'フィンガープリント', '指紋'],
  ['한큐', 'Single Cubic Zirconia', 'シングルキュービックジルコニア', '單顆鋯石'],
  ['점', 'Dot', 'ドット', '圓點'],
  ['폭', 'Wide', 'ワイド', '寬版'],
  ['세', 'Three', 'スリー', '三'],
  ['들', 'Set', 'セット', '組'],
  ['클리', 'Crystal', 'クリスタル', '水晶'],
  ['잼', 'Gem', 'ジェム', '寶石'],
  ['그리', 'Green', 'グリーン', '綠色'],
  ['핑', 'Pink', 'ピンク', '粉紅色'],
  ['꽂', 'Flower', 'フラワー', '花朵'],
  ['킐', 'Crystal', 'クリスタル', '水晶'],
  ['씰', 'Seal', 'シール', '印章'],
  ['트리', 'Tree', 'ツリー', '樹'],
  ['속', 'Inner', 'インナー', '內層'],
  ['틀', 'Frame', 'フレーム', '框架'],
  ['대', 'Large', 'ラージ', '大'],
  ['소', 'Small', 'スモール', '小'],
  ['검', 'Black', 'ブラック', '黑色'],
  ['한', 'Single', 'シングル', '單款'],
  ['두', 'Two', 'ツー', '雙'],
  ['인', 'Inset', 'インセット', '嵌入'],
  ['타', 'Oval', 'オーバル', '橢圓'],
  ['자', 'Shaped', '字型', '字型'],
  ['다', 'Sea', 'シー', '海洋'],
  ['만', 'Only', 'のみ', '單款'],
  ['골', 'Skull', 'スカル', '骷髏'],
  ['인터널용', 'Internal-Thread', 'インターナル用', '內螺紋用'],
  ['인터널', 'Internal-Thread', 'インターナル', '內螺紋'],
  ['스와로브스키', 'Swarovski', 'スワロフスキー', '施華洛世奇'],
  ['평스톤헤드', 'Flat Stone Head', 'フラットストーンヘッド', '平底寶石頭'],
  ['원큐빅헤드', 'Round Cubic Head', 'ラウンドキュービックヘッド', '圓形鋯石頭'],
  ['별큐빅헤드', 'Star Cubic Head', 'スターキュービックヘッド', '星形鋯石頭'],
  ['사각큐빅헤드', 'Square Cubic Head', 'スクエアキュービックヘッド', '方形鋯石頭'],
  ['귀걸이용', 'Earring', 'ピアス用', '耳環用'],
  ['교체용', 'Replacement', '交換用', '替換用'],
  ['스텐클리치', 'Stainless Clutch', 'ステンレスキャッチ', '不鏽鋼耳堵'],
  ['라블렛바', 'Labret Bar', 'ラブレットバー', '唇釘桿'],
  ['라블랫바', 'Labret Bar', 'ラブレットバー', '唇釘桿'],
  ['투명피어싱', 'Clear Piercing', '透明ピアス', '透明穿刺飾品'],
  ['원볼링', 'One-Ball Ring', 'ワンボールリング', '單珠環'],
  ['휘어쓰는', 'Bendable', '曲げて使う', '可彎式'],
  ['일자바', 'Straight Bar', 'ストレートバー', '直桿'],
  ['바나나바', 'Banana Bar', 'バナナバー', '香蕉桿'],
  ['나비넥타이', 'Bow Tie', '蝶ネクタイ', '領結'],
  ['네잎클로버', 'Four-Leaf Clover', '四つ葉クローバー', '四葉草'],
  ['쁘띠클로버', 'Petite Clover', 'プチクローバー', '迷你四葉草'],
  ['클로버', 'Clover', 'クローバー', '四葉草'],
  ['속빈미니하트', 'Mini Hollow Heart', 'ミニ中空ハート', '迷你鏤空愛心'],
  ['속빈하트', 'Hollow Heart', '中空ハート', '鏤空愛心'],
  ['타오르는하트', 'Flame Heart', 'フレームハート', '火焰愛心'],
  ['흐르는하트', 'Flowing Heart', 'フローハート', '流線愛心'],
  ['하트체인', 'Heart Chain', 'ハートチェーン', '愛心鏈條'],
  ['하트리본', 'Heart Ribbon', 'ハートリボン', '愛心蝴蝶結'],
  ['발렌타인하트', 'Valentine Heart', 'バレンタインハート', '情人節愛心'],
  ['진주자개꽃', 'Pearl Shell Flower', 'パールシェルフラワー', '珍珠貝殼花'],
  ['담수진주', 'Freshwater Pearl', '淡水パール', '淡水珍珠'],
  ['반진주', 'Half Pearl', 'ハーフパール', '半圓珍珠'],
  ['미러볼', 'Mirror Ball', 'ミラーボール', '鏡面球'],
  ['물방울', 'Teardrop', 'ドロップ', '水滴'],
  ['정육면체', 'Cube', 'キューブ', '立方體'],
  ['마름모', 'Diamond Shape', 'ひし形', '菱形'],
  ['불가사리', 'Starfish', 'ヒトデ', '海星'],
  ['초승달', 'Crescent Moon', '三日月', '新月'],
  ['발바닥', 'Paw Print', '肉球', '腳掌'],
  ['눈결정', 'Snow Crystal', '雪の結晶', '雪花結晶'],
  ['눈사람', 'Snowman', '雪だるま', '雪人'],
  ['눈꽃', 'Snowflake', '雪の花', '雪花'],
  ['십자가', 'Cross', 'クロス', '十字架'],
  ['테디베어', 'Teddy Bear', 'テディベア', '泰迪熊'],
  ['루돌프', 'Rudolph', 'ルドルフ', '麋鹿'],
  ['흔들목마', 'Rocking Horse', '木馬', '搖搖馬'],
  ['나뭇잎', 'Leaf', 'リーフ', '葉片'],
  ['한쪽날개', 'Single Wing', '片翼', '單翼'],
  ['큐빅', 'Cubic Zirconia', 'キュービックジルコニア', '鋯石'],
  ['잼스톤', 'Gemstone', 'ジェムストーン', '寶石'],
  ['일반점토', 'Standard Clay', 'スタンダードクレイ', '一般黏土'],
  ['나비중앙', 'Butterfly Center', 'バタフライセンター', '蝴蝶中心'],
  ['유화', 'Enamel', 'エナメル', '琺瑯'],
  ['클레이', 'Clay', 'クレイ', '黏土'],
  ['클래이', 'Clay', 'クレイ', '黏土'],
  ['에폭', 'Epoxy', 'エポキシ', '環氧樹脂'],
  ['애폭', 'Epoxy', 'エポキシ', '環氧樹脂'],
  ['코팅', 'Coated', 'コーティング', '鍍層'],
  ['민자', 'Plain', 'プレーン', '素面'],
  ['써지컬', 'Surgical Steel', 'サージカルステンレス', '醫療鋼'],
  ['티탄', 'Titanium', 'チタン', '鈦'],
  ['아크릴', 'Acrylic', 'アクリル', '壓克力'],
  ['귀걸이', 'Earring', 'ピアス', '耳環'],
  ['팬던트', 'Pendant', 'ペンダント', '吊飾'],
  ['스파클', 'Sparkle', 'スパークル', '閃耀'],
  ['스파크', 'Spark', 'スパーク', '閃光'],
  ['컷팅', 'Cut', 'カット', '切割'],
  ['물림', 'Prong-Set', '爪留め', '爪鑲'],
  ['오팔', 'Opal', 'オパール', '蛋白石'],
  ['오로라', 'Aurora', 'オーロラ', '極光'],
  ['재트', 'Jet', 'ジェット', '黑玉'],
  ['크리', 'Crystal', 'クリスタル', '水晶'],
  ['사파', 'Sapphire', 'サファイア', '藍寶石'],
  ['루비', 'Ruby', 'ルビー', '紅寶石'],
  ['터키', 'Turquoise', 'ターコイズ', '綠松石'],
  ['펄', 'Pearl', 'パール', '珍珠'],
  ['자개', 'Mother-of-Pearl', 'シェル', '貝殼'],
  ['진주', 'Pearl', 'パール', '珍珠'],
  ['스톤', 'Stone', 'ストーン', '寶石'],
  ['점토', 'Clay', 'クレイ', '黏土'],
  ['알록달록', 'Multicolor', 'マルチカラー', '彩色'],
  ['라벤더', 'Lavender', 'ラベンダー', '薰衣草色'],
  ['라벤다', 'Lavender', 'ラベンダー', '薰衣草色'],
  ['라밴더', 'Lavender', 'ラベンダー', '薰衣草色'],
  ['에메', 'Emerald', 'エメラルド', '祖母綠'],
  ['검정', 'Black', 'ブラック', '黑色'],
  ['블랙', 'Black', 'ブラック', '黑色'],
  ['화이트', 'White', 'ホワイト', '白色'],
  ['흰색', 'White', 'ホワイト', '白色'],
  ['초록', 'Green', 'グリーン', '綠色'],
  ['녹색', 'Green', 'グリーン', '綠色'],
  ['파랑', 'Blue', 'ブルー', '藍色'],
  ['노랑', 'Yellow', 'イエロー', '黃色'],
  ['주황', 'Orange', 'オレンジ', '橘色'],
  ['핑크', 'Pink', 'ピンク', '粉紅色'],
  ['레드', 'Red', 'レッド', '紅色'],
  ['골드', 'Gold', 'ゴールド', '金色'],
  ['실버', 'Silver', 'シルバー', '銀色'],
  ['유색', 'Colored', 'カラー', '彩色'],
  ['투명', 'Clear', 'クリア', '透明'],
  ['화이트폭', 'White', 'ホワイト', '白色'],
  ['나비', 'Butterfly', 'バタフライ', '蝴蝶'],
  ['리본', 'Ribbon', 'リボン', '蝴蝶結'],
  ['왕관', 'Crown', 'クラウン', '皇冠'],
  ['하트', 'Heart', 'ハート', '愛心'],
  ['별사탕', 'Star Candy', 'スターキャンディ', '星星糖'],
  ['별', 'Star', 'スター', '星星'],
  ['달', 'Moon', 'ムーン', '月亮'],
  ['행성', 'Planet', 'プラネット', '行星'],
  ['위성', 'Satellite', 'サテライト', '衛星'],
  ['꽃', 'Flower', 'フラワー', '花朵'],
  ['잎', 'Petal', '花びら', '花瓣'],
  ['리프', 'Leaf', 'リーフ', '葉片'],
  ['장미', 'Rose', 'ローズ', '玫瑰'],
  ['조개', 'Shell', 'シェル', '貝殼'],
  ['토끼', 'Rabbit', 'うさぎ', '兔子'],
  ['버니', 'Bunny', 'バニー', '兔子'],
  ['거북', 'Turtle', 'カメ', '烏龜'],
  ['코끼리', 'Elephant', 'ゾウ', '大象'],
  ['꿀벌', 'Bee', 'ハチ', '蜜蜂'],
  ['해마', 'Seahorse', 'タツノオトシゴ', '海馬'],
  ['고래', 'Whale', 'クジラ', '鯨魚'],
  ['축구', 'Soccer Ball', 'サッカーボール', '足球'],
  ['스마일', 'Smile', 'スマイル', '笑臉'],
  ['포션', 'Potion', 'ポーション', '魔法藥水'],
  ['팅커벨', 'Tinker Bell', 'ティンカーベル', '小仙女'],
  ['새싹', 'Sprout', 'スプラウト', '嫩芽'],
  ['작살', 'Harpoon', 'ハープーン', '魚叉'],
  ['선물', 'Gift', 'ギフト', '禮物'],
  ['발래드', 'Ballad', 'バラード', '敘事曲'],
  ['오망성', 'Pentagram', '五芒星', '五芒星'],
  ['엑스', 'X', 'X', 'X'],
  ['마름빛', 'Diamond Spark', 'ダイヤスパーク', '菱形閃光'],
  ['원', 'Round', 'ラウンド', '圓形'],
  ['삼각', 'Triangle', 'トライアングル', '三角形'],
  ['사각', 'Square', 'スクエア', '方形'],
  ['네모', 'Square', 'スクエア', '方形'],
  ['반원', 'Half-Round', '半円', '半圓'],
  ['동글', 'Round', 'ラウンド', '圓形'],
  ['구', 'Sphere', 'スフィア', '球形'],
  ['콘', 'Cone', 'コーン', '錐形'],
  ['덤밸', 'Dumbbell', 'ダンベル', '啞鈴'],
  ['아령', 'Dumbbell', 'ダンベル', '啞鈴'],
  ['ㄷ자', 'ㄷ-Shaped', 'ㄷ字型', 'ㄷ字型'],
  ['체인', 'Chain', 'チェーン', '鏈條'],
  ['라인', 'Line', 'ライン', '線條'],
  ['헤드', 'Head', 'ヘッド', '頭'],
  ['라블렛', 'Labret', 'ラブレット', '唇釘'],
  ['링', 'Ring', 'リング', '環'],
  ['볼', 'Ball', 'ボール', '球'],
  ['침', 'Post', 'ポスト', '耳針'],
  ['바벨', 'Barbell', 'バーベル', '穿刺桿'],
  ['바', 'Bar', 'バー', '桿'],
  ['메인', 'Main', 'メイン', '主石'],
  ['서브', 'Accent', 'サブ', '副石'],
  ['쁘띠', 'Petite', 'プチ', '迷你'],
  ['미니', 'Mini', 'ミニ', '迷你'],
  ['작은', 'Small', 'スモール', '小'],
  ['큰', 'Large', 'ラージ', '大'],
  ['오른', 'Right', '右', '右'],
  ['왼', 'Left', '左', '左'],
  ['한발', 'Single-Prong', 'シングル爪', '單爪'],
  ['무발', 'Bezel', '覆輪', '包鑲'],
  ['평', 'Flat', 'フラット', '平面'],
  ['롱', 'Long', 'ロング', '長款'],
  ['일반', 'Standard', 'スタンダード', '一般'],
  ['가지색', 'Colors', 'カラー', '種顏色'],
  ['선별', 'Assorted', 'アソート', '混款'],
  ['발', 'Prong', '爪', '爪'],
  ['큐', 'Cubic Zirconia', 'キュービックジルコニア', '鋯石'],
  ['흰', 'White', 'ホワイト', '白色'],
  ['해', 'Sun', 'サン', '太陽'],
  ['빛', 'Spark', 'スパーク', '光芒'],
  ['개', 'Pieces', '個', '個'],
]

const localizedTermIndex = { en: 1, ja: 2, zhTw: 3 }
const sortedArchiveNameTerms = [...archiveNameTerms].sort((a, b) => b[0].length - a[0].length)
const hangulInitials = ['g', 'kk', 'n', 'd', 'tt', 'r', 'm', 'b', 'pp', 's', 'ss', '', 'j', 'jj', 'ch', 'k', 't', 'p', 'h']
const hangulVowels = ['a', 'ae', 'ya', 'yae', 'eo', 'e', 'yeo', 'ye', 'o', 'wa', 'wae', 'oe', 'yo', 'u', 'wo', 'we', 'wi', 'yu', 'eu', 'ui', 'i']
const hangulFinals = ['', 'k', 'k', 'ks', 'n', 'nj', 'nh', 't', 'l', 'lk', 'lm', 'lb', 'ls', 'lt', 'lp', 'lh', 'm', 'p', 'ps', 't', 't', 'ng', 't', 't', 'k', 't', 'p', 'h']

function romanizeHangul(value) {
  return [...String(value)].map((char) => {
    const code = char.charCodeAt(0) - 0xac00
    if (code < 0 || code > 11171) return char
    const initial = Math.floor(code / 588)
    const vowel = Math.floor((code % 588) / 28)
    const final = code % 28
    return `${hangulInitials[initial]}${hangulVowels[vowel]}${hangulFinals[final]}`
  }).join('')
}

function cleanLocalizedName(value) {
  return String(value)
    .replace(/\s*,\s*/g, ', ')
    .replace(/\s*\/\s*/g, ' / ')
    .replace(/\(\s+/g, '(')
    .replace(/\s+\)/g, ')')
    .replace(/\s+/g, ' ')
    .trim()
}

function titleCaseRomanizedFallback(value) {
  return String(value).replace(/\b[a-z][a-z0-9-]*/g, (word) => `${word[0].toUpperCase()}${word.slice(1)}`)
}

export function localizeArchiveProductName(nameKo, locale) {
  if (!localizedTermIndex[locale]) return String(nameKo || '').trim()

  const index = localizedTermIndex[locale]
  const stoneUnit = locale === 'en' ? 'Stone' : '石'
  const pieceUnit = locale === 'en' ? 'pcs' : locale === 'ja' ? '個' : '個'
  let localized = String(nameKo || '')
    .replace(/([0-9n]+)\s*방/gi, (_, count) => ` ${count}${locale === 'en' ? '-' : ''}${stoneUnit} `)
    .replace(/(\d+)\s*개/g, (_, count) => ` ${count} ${pieceUnit} `)

  for (const term of sortedArchiveNameTerms) {
    localized = localized.split(term[0]).join(` ${term[index]} `)
  }

  localized = localized.replace(/\p{Script=Hangul}+/gu, (word) => word === 'ㄷ' ? word : ` ${romanizeHangul(word)} `)
  localized = cleanLocalizedName(localized)
  return locale === 'en' ? titleCaseRomanizedFallback(localized) : localized
}

export function createArchiveProductLocalization(nameKo) {
  const nameEn = localizeArchiveProductName(nameKo, 'en')
  const nameJa = localizeArchiveProductName(nameKo, 'ja')
  const nameZhTw = localizeArchiveProductName(nameKo, 'zhTw')
  return {
    nameEn,
    nameJa,
    nameZhTw,
    descriptionEn: `${nameEn} for wholesale catalog inquiries.`,
    descriptionJa: `${nameJa}。B2B卸売カタログ向けの商品です。`,
    descriptionZhTw: `${nameZhTw}，適用於 B2B 批發目錄詢價。`,
  }
}

export function shouldGenerateArchiveLocalization(product, productId) {
  return String(productId || product?.code || '').startsWith('NPI-')
    || product?.taxonomy?.importSource === 'piercing-archive'
}
