import { resolveLocaleCopy, useLocalePath } from '../../utils/locale.js'

const copy = {
  kr: {
    list: {
      title: '견적',
      description: '요청받은 상품을 확인하고 준비·취소 수량, 입금, 발송 상태를 관리합니다.',
      startPicking: '견적 요청에서 물건 확인 시작',
      inquiryRequests: '문의 요청',
      quotations: '견적서',
      searchLabel: '견적 검색',
      searchPlaceholder: '견적 번호, 문의 번호, 거래처',
      searchAria: '검색',
      workflowStage: '운영 단계',
      emptyTitle: '조건에 맞는 견적이 없습니다.',
      emptyDescription: '문의 요청을 열어 첫 견적 초안을 만들어보세요.',
      viewRequests: '문의 요청 보기',
      all: '전체',
      draft: '초안',
      columns: {
        request: '견적 요청',
        company: '거래처',
        stage: '운영 단계',
        preparedTotal: '준비 금액',
        validUntil: '유효기간',
        pdf: 'PDF',
        updatedAt: '수정일',
      },
    },
    workflow: {
      received: '견적 접수',
      picking: '물건 확인·챙기기',
      receipt_sent: '준비 완료',
      payment_confirmed: '입금 확인',
      shipped: '발송 완료',
      completed: '거래 종료',
      cancelled: '전체 취소',
    },
    fulfillment: {
      pending: '미확인',
      ready: '준비 완료',
      partial: '일부 취소',
      cancelled: '전체 취소',
    },
    cancellationReasons: {
      out_of_stock: '재고 없음',
      quantity_shortage: '수량 부족',
      quality_issue: '품질 확인 불가',
      discontinued: '취급 종료',
      other: '기타',
    },
    nextActions: {
      received: '물건 확인 시작',
      picking: '준비 완료',
      receipt_sent: '입금 확인',
      payment_confirmed: '발송 완료',
      shipped: '거래 종료',
    },
    documentLanguages: {
      kr: '한국어',
      en: 'English',
      jp: '日本語',
      'zh-TW': '繁體中文',
    },
    detail: {
      notFound: '견적을 찾을 수 없습니다.',
      quotesList: '견적 목록',
      saved: '상품 준비 결과와 견적 초안을 저장했습니다.',
      saveFailed: '견적을 저장하지 못했습니다.',
      validUntilRequired: '견적 유효기간을 입력해 주세요.',
      issueSuccess: '준비 결과 PDF v{revision}를 발행했습니다.',
      issueFailed: '견적서를 발행하지 못했습니다.',
      saveBeforeReceipt: '변경 내용을 저장하고 사진·옵션·수량이 포함된 상품 준비 PDF를 다시 발행한 뒤 준비 완료로 변경해 주세요.',
      cancellationNoteRequired: '전체 취소 사유를 운영 메모에 입력해 주세요.',
      workflowChanged: "운영 상태를 '{status}'로 변경했습니다.",
      workflowFailed: '운영 상태를 변경하지 못했습니다.',
      downloadFailed: 'PDF를 내려받지 못했습니다.',
      issueNewTitle: '새 버전으로 발행할까요?',
      issueTitle: '준비 결과 견적서를 발행할까요?',
      issueDescription: '상품 사진, 선택 옵션, 원 요청 수량, 준비·취소 수량을 함께 표시한 상품 준비 PDF가 생성됩니다. 준비 완료 전까지 내용을 수정하고 새 버전으로 재발행할 수 있습니다.',
      reissue: '재발행',
      issue: '발행',
      eyebrow: '견적 상품 준비',
      fallbackTitle: '견적 요청',
      companyFallback: '거래처',
      list: '목록',
      sourceRequest: '원본 요청',
      pdfReissue: 'PDF 재발행',
      pdfIssue: 'PDF 발행',
      workflowAria: '견적 처리 단계',
      operationTitle: '고객이 보낸 견적 품목을 확인하고 챙기는 화면입니다.',
      operationBody: '웹이나 모바일에서 사진·옵션·수량을 확인하고, 있는 수량만 준비하며 없는 수량은 취소 사유와 함께 기록합니다. 사이트 결제는 없습니다.',
      readOnlyTitle: '조회 전용 견적입니다.',
      readOnlyBody: '상품 준비와 상태 변경에는 견적 작성 권한이 필요합니다.',
      legacyTitle: '기존 방식으로 종료된 견적입니다.',
      legacyBody: '과거 기록은 그대로 보존되며 새 상품 준비 흐름으로 수정할 수 없습니다.',
      prepareTitle: '1. 물건 확인·챙기기',
      prepareBody: '원 요청 수량은 바뀌지 않습니다. 실제로 챙긴 수량만 입력하면 취소 수량이 자동 계산됩니다.',
      prepareAll: '모든 품목 준비',
      columns: {
        product: '상품·옵션',
        requested: '요청',
        prepared: '준비',
        cancelled: '취소',
        result: '처리 결과',
        unitPrice: '단가',
        amount: '금액',
      },
      preparedQuantityAria: '{code} 준비 수량',
      prepareItemAll: '전부 준비',
      outOfStock: '품절',
      cancellationReasonAria: '{code} 취소 사유',
      selectReason: '사유 선택',
      cancellationNoteAria: '{code} 취소 메모',
      cancellationNotePlaceholder: '구매자에게 보일 추가 설명',
      unitPriceAria: '{code} 단가',
      unresolvedTitle: '아직 확인하지 않은 품목이 {count}개 있습니다.',
      unresolvedBody: '각 품목을 준비 완료, 일부 취소 또는 전체 취소로 정리해야 PDF를 발행할 수 있습니다.',
      missingReasonTitle: '취소 사유가 필요한 품목이 {count}개 있습니다.',
      missingReasonBody: '일부 또는 전체 취소 품목의 사유를 선택해야 준비 결과 PDF를 발행할 수 있습니다.',
      invalidQuantityTitle: '준비 수량을 확인해야 하는 품목이 {count}개 있습니다.',
      invalidQuantityBody: '준비 수량은 0 이상이며 원 요청 수량을 넘을 수 없습니다.',
      exceptionsTitle: '취소·수량 부족 품목',
      exceptionsBody: '원 견적 요청과 분리해 구매자에게 그대로 표시됩니다.',
      exceptionCounts: '요청 {requested} / 준비 {prepared} / 취소 {cancelled}',
      reasonMissing: '사유 미입력',
      resultTitle: '2. 준비 결과 견적',
      resultBody: '준비된 수량만 합산하고 취소 품목은 수량과 사유를 함께 문서에 남깁니다.',
      validUntil: '유효기간',
      documentLanguage: '문서 언어',
      leadTime: '납기',
      leadTimePlaceholder: '영업일 기준 7-10일',
      shippingTerms: '배송 조건',
      shippingPlaceholder: '택배 / 운임 별도',
      buyerNote: '구매자 안내',
      internalMemoTitle: '내부 메모',
      internalMemoBody: '관리자만 볼 수 있으며 구매자 화면과 PDF에는 표시되지 않습니다.',
      documentsTitle: '발행 문서',
      documentsBody: '각 버전은 수정되지 않으며 당시의 준비·취소 결과를 보존합니다.',
      version: '버전 {revision}',
      downloadAria: '버전 {revision} PDF 내려받기',
      downloadTitle: 'PDF 내려받기',
      historyTitle: '처리 이력',
      historyBody: '문서 발행과 운영 상태 변경을 시간순으로 기록합니다.',
      summaryTitle: '운영 요약',
      currentStage: '현재 단계',
      requestedItems: '원 요청 품목',
      exceptions: '취소·부족',
      preparedTotal: '준비 금액',
      pdfVersion: 'PDF 버전',
      saving: '저장 중...',
      saveResult: '준비 결과 저장',
      issueNewVersion: 'PDF 새 버전 발행',
      issueResult: '준비 결과 PDF 발행',
      revertPicking: '물건 확인으로 되돌리기',
      workflowNote: '운영 메모 / 전체 취소 사유',
      cancelAll: '견적 전체 취소',
      unsavedChanges: '저장하지 않은 변경사항이 있습니다.',
      discard: '되돌리기',
      save: '저장',
      saveBarAria: '변경사항 저장',
      processing: '처리 중...',
      cancel: '취소',
      closeToast: '알림 닫기',
    },
  },
  en: {
    list: {
      title: 'Quotes',
      description: 'Check requested products and track prepared or cancelled quantities, payment, and shipping.',
      startPicking: 'Start checking a quote request',
      inquiryRequests: 'Inquiry requests',
      quotations: 'Quotations',
      searchLabel: 'Search quotes',
      searchPlaceholder: 'Quote number, inquiry number, or company',
      searchAria: 'Search',
      workflowStage: 'Workflow stage',
      emptyTitle: 'No quotes match these filters.',
      emptyDescription: 'Open an inquiry request to create the first quote draft.',
      viewRequests: 'View inquiry requests',
      all: 'All',
      draft: 'Draft',
      columns: {
        request: 'Quote request',
        company: 'Company',
        stage: 'Workflow stage',
        preparedTotal: 'Prepared total',
        validUntil: 'Valid until',
        pdf: 'PDF',
        updatedAt: 'Updated',
      },
    },
    workflow: {
      received: 'Quote received',
      picking: 'Check and pack',
      receipt_sent: 'Preparation complete',
      payment_confirmed: 'Payment confirmed',
      shipped: 'Shipped',
      completed: 'Completed',
      cancelled: 'Fully cancelled',
    },
    fulfillment: {
      pending: 'Not checked',
      ready: 'Ready',
      partial: 'Partially cancelled',
      cancelled: 'Fully cancelled',
    },
    cancellationReasons: {
      out_of_stock: 'Out of stock',
      quantity_shortage: 'Quantity shortage',
      quality_issue: 'Quality check failed',
      discontinued: 'Discontinued',
      other: 'Other',
    },
    nextActions: {
      received: 'Start checking',
      picking: 'Complete preparation',
      receipt_sent: 'Confirm payment',
      payment_confirmed: 'Mark as shipped',
      shipped: 'Complete transaction',
    },
    documentLanguages: {
      kr: 'Korean',
      en: 'English',
      jp: 'Japanese',
      'zh-TW': 'Traditional Chinese',
    },
    detail: {
      notFound: 'Quote not found.',
      quotesList: 'Quote list',
      saved: 'Preparation results and the quote draft were saved.',
      saveFailed: 'Unable to save the quote.',
      validUntilRequired: 'Enter the quote validity date.',
      issueSuccess: 'Preparation PDF v{revision} was issued.',
      issueFailed: 'Unable to issue the quotation.',
      saveBeforeReceipt: 'Save the changes and reissue the product preparation PDF with images, options, and quantities before completing preparation.',
      cancellationNoteRequired: 'Enter the full cancellation reason in the operations note.',
      workflowChanged: "Workflow status changed to '{status}'.",
      workflowFailed: 'Unable to change the workflow status.',
      downloadFailed: 'Unable to download the PDF.',
      issueNewTitle: 'Issue a new version?',
      issueTitle: 'Issue the preparation quotation?',
      issueDescription: 'The product preparation PDF will show product images, selected options, and requested, prepared, and cancelled quantities. You can revise and reissue it until preparation is complete.',
      reissue: 'Reissue',
      issue: 'Issue',
      eyebrow: 'Quote preparation',
      fallbackTitle: 'Quote request',
      companyFallback: 'Company',
      list: 'List',
      sourceRequest: 'Source request',
      pdfReissue: 'Reissue PDF',
      pdfIssue: 'Issue PDF',
      workflowAria: 'Quote workflow stages',
      operationTitle: 'Use this screen to prepare items requested by a signed-in buyer.',
      operationBody: 'Check photos, options, and quantities on web or mobile. Prepare available quantities and record unavailable quantities with a cancellation reason. There is no online checkout.',
      readOnlyTitle: 'This quote is read-only.',
      readOnlyBody: 'Quote write permission is required to prepare items or change workflow status.',
      legacyTitle: 'This quote was closed under the previous workflow.',
      legacyBody: 'The historical record is preserved and cannot be edited in the new preparation workflow.',
      prepareTitle: '1. Check and pack items',
      prepareBody: 'The original requested quantity does not change. Enter the quantity actually prepared and the cancelled quantity is calculated automatically.',
      prepareAll: 'Prepare all items',
      columns: {
        product: 'Product and options',
        requested: 'Requested',
        prepared: 'Prepared',
        cancelled: 'Cancelled',
        result: 'Result',
        unitPrice: 'Unit price',
        amount: 'Amount',
      },
      preparedQuantityAria: '{code} prepared quantity',
      prepareItemAll: 'Prepare all',
      outOfStock: 'Out of stock',
      cancellationReasonAria: '{code} cancellation reason',
      selectReason: 'Select a reason',
      cancellationNoteAria: '{code} cancellation note',
      cancellationNotePlaceholder: 'Additional explanation shown to the buyer',
      unitPriceAria: '{code} unit price',
      unresolvedTitle: '{count} item(s) have not been checked.',
      unresolvedBody: 'Mark every item as ready, partially cancelled, or fully cancelled before issuing the PDF.',
      missingReasonTitle: '{count} item(s) require a cancellation reason.',
      missingReasonBody: 'Select a reason for every partially or fully cancelled item before issuing the preparation PDF.',
      invalidQuantityTitle: '{count} item(s) have an invalid prepared quantity.',
      invalidQuantityBody: 'Prepared quantity must be zero or greater and cannot exceed the original requested quantity.',
      exceptionsTitle: 'Cancelled or short items',
      exceptionsBody: 'These items are shown separately from the original quote request on the buyer screen.',
      exceptionCounts: 'Requested {requested} / Prepared {prepared} / Cancelled {cancelled}',
      reasonMissing: 'No reason entered',
      resultTitle: '2. Preparation quotation',
      resultBody: 'Only prepared quantities are included in the total. Cancelled items remain in the document with their quantities and reasons.',
      validUntil: 'Valid until',
      documentLanguage: 'Document language',
      leadTime: 'Lead time',
      leadTimePlaceholder: '7-10 business days',
      shippingTerms: 'Shipping terms',
      shippingPlaceholder: 'Courier / freight separate',
      buyerNote: 'Buyer note',
      internalMemoTitle: 'Internal memo',
      internalMemoBody: 'Only administrators can see this. It is not shown to the buyer or included in the PDF.',
      documentsTitle: 'Issued documents',
      documentsBody: 'Each version is immutable and preserves the preparation and cancellation result at issue time.',
      version: 'Version {revision}',
      downloadAria: 'Download version {revision} PDF',
      downloadTitle: 'Download PDF',
      historyTitle: 'Processing history',
      historyBody: 'Document issues and workflow changes are recorded chronologically.',
      summaryTitle: 'Operations summary',
      currentStage: 'Current stage',
      requestedItems: 'Requested items',
      exceptions: 'Cancelled or short',
      preparedTotal: 'Prepared total',
      pdfVersion: 'PDF version',
      saving: 'Saving...',
      saveResult: 'Save preparation result',
      issueNewVersion: 'Issue new PDF version',
      issueResult: 'Issue preparation PDF',
      revertPicking: 'Return to item checking',
      workflowNote: 'Operations note / full cancellation reason',
      cancelAll: 'Cancel entire quote',
      unsavedChanges: 'You have unsaved changes.',
      discard: 'Discard changes',
      save: 'Save',
      saveBarAria: 'Save changes',
      processing: 'Processing...',
      cancel: 'Cancel',
      closeToast: 'Close notification',
    },
  },
  jp: {
    list: {
      title: '見積もり',
      description: '依頼商品を確認し、準備・取消数量、入金、発送状況を管理します。',
      startPicking: '見積依頼の商品確認を開始',
      inquiryRequests: 'お問い合わせ依頼',
      quotations: '見積書',
      searchLabel: '見積もり検索',
      searchPlaceholder: '見積番号、お問い合わせ番号、取引先',
      searchAria: '検索',
      workflowStage: '運用段階',
      emptyTitle: '条件に一致する見積もりがありません。',
      emptyDescription: 'お問い合わせ依頼を開いて最初の見積もり下書きを作成してください。',
      viewRequests: 'お問い合わせ依頼を見る',
      all: 'すべて',
      draft: '下書き',
      columns: {
        request: '見積依頼',
        company: '取引先',
        stage: '運用段階',
        preparedTotal: '準備金額',
        validUntil: '有効期限',
        pdf: 'PDF',
        updatedAt: '更新日',
      },
    },
    workflow: {
      received: '見積受付',
      picking: '商品確認・準備',
      receipt_sent: '準備完了',
      payment_confirmed: '入金確認',
      shipped: '発送完了',
      completed: '取引終了',
      cancelled: '全体取消',
    },
    fulfillment: {
      pending: '未確認',
      ready: '準備完了',
      partial: '一部取消',
      cancelled: '全体取消',
    },
    cancellationReasons: {
      out_of_stock: '在庫なし',
      quantity_shortage: '数量不足',
      quality_issue: '品質確認不可',
      discontinued: '取扱終了',
      other: 'その他',
    },
    nextActions: {
      received: '商品確認開始',
      picking: '準備完了',
      receipt_sent: '入金確認',
      payment_confirmed: '発送完了',
      shipped: '取引終了',
    },
    documentLanguages: {
      kr: '韓国語',
      en: '英語',
      jp: '日本語',
      'zh-TW': '繁体字中国語',
    },
    detail: {
      notFound: '見積もりが見つかりません。',
      quotesList: '見積もり一覧',
      saved: '商品準備結果と見積もり下書きを保存しました。',
      saveFailed: '見積もりを保存できませんでした。',
      validUntilRequired: '見積もりの有効期限を入力してください。',
      issueSuccess: '準備結果PDF v{revision}を発行しました。',
      issueFailed: '見積書を発行できませんでした。',
      saveBeforeReceipt: '変更を保存し、画像・オプション・数量を含む商品準備PDFを再発行してから、準備完了に変更してください。',
      cancellationNoteRequired: '全体取消理由を運用メモに入力してください。',
      workflowChanged: "運用状態を「{status}」に変更しました。",
      workflowFailed: '運用状態を変更できませんでした。',
      downloadFailed: 'PDFをダウンロードできませんでした。',
      issueNewTitle: '新しいバージョンを発行しますか？',
      issueTitle: '準備結果見積書を発行しますか？',
      issueDescription: '商品画像、選択オプション、依頼・準備・取消数量を併記した商品準備PDFを作成します。準備完了前であれば修正して再発行できます。',
      reissue: '再発行',
      issue: '発行',
      eyebrow: '見積商品準備',
      fallbackTitle: '見積依頼',
      companyFallback: '取引先',
      list: '一覧',
      sourceRequest: '元の依頼',
      pdfReissue: 'PDF再発行',
      pdfIssue: 'PDF発行',
      workflowAria: '見積もり処理段階',
      operationTitle: 'ログイン済み購入者の見積依頼商品を店舗で準備する画面です。',
      operationBody: 'Webまたはモバイルで画像・オプション・数量を確認し、用意できる数量を準備します。用意できない数量は取消理由とともに記録します。サイト決済はありません。',
      readOnlyTitle: '読み取り専用の見積もりです。',
      readOnlyBody: '商品準備と状態変更には見積もり作成権限が必要です。',
      legacyTitle: '以前の方式で終了した見積もりです。',
      legacyBody: '過去の記録はそのまま保持され、新しい商品準備フローでは編集できません。',
      prepareTitle: '1. 商品確認・準備',
      prepareBody: '元の依頼数量は変わりません。実際に準備した数量を入力すると、取消数量が自動計算されます。',
      prepareAll: 'すべての商品を準備',
      columns: {
        product: '商品・オプション',
        requested: '依頼',
        prepared: '準備',
        cancelled: '取消',
        result: '処理結果',
        unitPrice: '単価',
        amount: '金額',
      },
      preparedQuantityAria: '{code} 準備数量',
      prepareItemAll: '全数準備',
      outOfStock: '在庫切れ',
      cancellationReasonAria: '{code} 取消理由',
      selectReason: '理由を選択',
      cancellationNoteAria: '{code} 取消メモ',
      cancellationNotePlaceholder: '購入者に表示する追加説明',
      unitPriceAria: '{code} 単価',
      unresolvedTitle: '未確認の商品が{count}件あります。',
      unresolvedBody: 'PDFを発行する前に、各商品を準備完了、一部取消、または全体取消に整理してください。',
      missingReasonTitle: '取消理由が必要な商品が{count}件あります。',
      missingReasonBody: '準備結果PDFを発行する前に、一部または全体取消商品の理由を選択してください。',
      invalidQuantityTitle: '準備数量の確認が必要な商品が{count}件あります。',
      invalidQuantityBody: '準備数量は0以上で、元の依頼数量を超えることはできません。',
      exceptionsTitle: '取消・数量不足商品',
      exceptionsBody: '元の見積依頼とは分けて購入者にそのまま表示されます。',
      exceptionCounts: '依頼 {requested} / 準備 {prepared} / 取消 {cancelled}',
      reasonMissing: '理由未入力',
      resultTitle: '2. 準備結果見積もり',
      resultBody: '準備済み数量のみを合計し、取消商品は数量と理由を文書に残します。',
      validUntil: '有効期限',
      documentLanguage: '文書言語',
      leadTime: '納期',
      leadTimePlaceholder: '営業日基準7～10日',
      shippingTerms: '配送条件',
      shippingPlaceholder: '宅配便 / 送料別',
      buyerNote: '購入者案内',
      internalMemoTitle: '内部メモ',
      internalMemoBody: '管理者のみ閲覧でき、購入者画面とPDFには表示されません。',
      documentsTitle: '発行文書',
      documentsBody: '各バージョンは変更されず、発行時の準備・取消結果を保持します。',
      version: 'バージョン {revision}',
      downloadAria: 'バージョン {revision} のPDFをダウンロード',
      downloadTitle: 'PDFをダウンロード',
      historyTitle: '処理履歴',
      historyBody: '文書発行と運用状態変更を時系列で記録します。',
      summaryTitle: '運用概要',
      currentStage: '現在の段階',
      requestedItems: '元の依頼商品',
      exceptions: '取消・不足',
      preparedTotal: '準備金額',
      pdfVersion: 'PDFバージョン',
      saving: '保存中...',
      saveResult: '準備結果を保存',
      issueNewVersion: 'PDF新バージョン発行',
      issueResult: '準備結果PDF発行',
      revertPicking: '商品確認に戻す',
      workflowNote: '運用メモ / 全体取消理由',
      cancelAll: '見積もり全体を取消',
      unsavedChanges: '保存していない変更があります。',
      discard: '変更を破棄',
      save: '保存',
      saveBarAria: '変更を保存',
      processing: '処理中...',
      cancel: 'キャンセル',
      closeToast: '通知を閉じる',
    },
  },
  'zh-TW': {
    list: {
      title: '報價',
      description: '確認客戶需求商品，並管理備妥、取消數量、匯款與出貨狀態。',
      startPicking: '開始確認報價商品',
      inquiryRequests: '詢價請求',
      quotations: '報價單',
      searchLabel: '搜尋報價',
      searchPlaceholder: '報價編號、詢價編號或客戶',
      searchAria: '搜尋',
      workflowStage: '作業階段',
      emptyTitle: '沒有符合條件的報價。',
      emptyDescription: '請開啟詢價請求以建立第一份報價草稿。',
      viewRequests: '查看詢價請求',
      all: '全部',
      draft: '草稿',
      columns: {
        request: '報價請求',
        company: '客戶',
        stage: '作業階段',
        preparedTotal: '備貨金額',
        validUntil: '有效期限',
        pdf: 'PDF',
        updatedAt: '更新日期',
      },
    },
    workflow: {
      received: '報價已受理',
      picking: '確認與備貨',
      receipt_sent: '備貨完成',
      payment_confirmed: '已確認匯款',
      shipped: '已出貨',
      completed: '交易完成',
      cancelled: '全部取消',
    },
    fulfillment: {
      pending: '未確認',
      ready: '備貨完成',
      partial: '部分取消',
      cancelled: '全部取消',
    },
    cancellationReasons: {
      out_of_stock: '缺貨',
      quantity_shortage: '數量不足',
      quality_issue: '無法通過品質確認',
      discontinued: '停止供應',
      other: '其他',
    },
    nextActions: {
      received: '開始確認商品',
      picking: '完成備貨',
      receipt_sent: '確認匯款',
      payment_confirmed: '標記已出貨',
      shipped: '完成交易',
    },
    documentLanguages: {
      kr: '韓文',
      en: '英文',
      jp: '日文',
      'zh-TW': '繁體中文',
    },
    detail: {
      notFound: '找不到報價。',
      quotesList: '報價列表',
      saved: '已儲存商品備貨結果與報價草稿。',
      saveFailed: '無法儲存報價。',
      validUntilRequired: '請輸入報價有效期限。',
      issueSuccess: '已發行備貨結果 PDF v{revision}。',
      issueFailed: '無法發行報價單。',
      saveBeforeReceipt: '請先儲存變更並重新發行含圖片、規格與數量的商品備貨 PDF，再標記備貨完成。',
      cancellationNoteRequired: '請在作業備註中輸入全部取消原因。',
      workflowChanged: "作業狀態已變更為「{status}」。",
      workflowFailed: '無法變更作業狀態。',
      downloadFailed: '無法下載 PDF。',
      issueNewTitle: '要發行新版本嗎？',
      issueTitle: '要發行備貨結果報價單嗎？',
      issueDescription: '商品備貨 PDF 會顯示商品圖片、所選規格，以及需求、備妥與取消數量。備貨完成前仍可修改並重新發行。',
      reissue: '重新發行',
      issue: '發行',
      eyebrow: '報價備貨',
      fallbackTitle: '報價請求',
      companyFallback: '客戶',
      list: '列表',
      sourceRequest: '原始詢價',
      pdfReissue: '重新發行 PDF',
      pdfIssue: '發行 PDF',
      workflowAria: '報價處理階段',
      operationTitle: '此畫面用於準備已登入買家所請求的商品。',
      operationBody: '請在網頁或行動裝置確認圖片、規格與數量，只準備可供應的數量，無法供應的數量則記錄取消原因。網站不提供線上結帳。',
      readOnlyTitle: '此報價僅供檢視。',
      readOnlyBody: '準備商品或變更作業狀態需要報價寫入權限。',
      legacyTitle: '此報價已依舊流程結束。',
      legacyBody: '歷史記錄會保留，且無法在新的備貨流程中編輯。',
      prepareTitle: '1. 確認與備貨',
      prepareBody: '原需求數量不會變更。輸入實際備妥數量後，系統會自動計算取消數量。',
      prepareAll: '備妥全部品項',
      columns: {
        product: '商品與選項',
        requested: '需求',
        prepared: '備妥',
        cancelled: '取消',
        result: '處理結果',
        unitPrice: '單價',
        amount: '金額',
      },
      preparedQuantityAria: '{code} 備妥數量',
      prepareItemAll: '全部備妥',
      outOfStock: '缺貨',
      cancellationReasonAria: '{code} 取消原因',
      selectReason: '選擇原因',
      cancellationNoteAria: '{code} 取消備註',
      cancellationNotePlaceholder: '向買家顯示的補充說明',
      unitPriceAria: '{code} 單價',
      unresolvedTitle: '尚有 {count} 個品項未確認。',
      unresolvedBody: '發行 PDF 前，請將每個品項整理為備貨完成、部分取消或全部取消。',
      missingReasonTitle: '有 {count} 個品項需要取消原因。',
      missingReasonBody: '發行備貨結果 PDF 前，請為部分或全部取消的品項選擇原因。',
      invalidQuantityTitle: '有 {count} 個品項的備妥數量需要確認。',
      invalidQuantityBody: '備妥數量必須大於或等於 0，且不得超過原需求數量。',
      exceptionsTitle: '取消或數量不足品項',
      exceptionsBody: '這些品項會與原報價請求分開顯示給買家。',
      exceptionCounts: '需求 {requested} / 備妥 {prepared} / 取消 {cancelled}',
      reasonMissing: '未輸入原因',
      resultTitle: '2. 備貨結果報價',
      resultBody: '合計僅包含備妥數量，取消品項仍會連同數量與原因保留在文件中。',
      validUntil: '有效期限',
      documentLanguage: '文件語言',
      leadTime: '交期',
      leadTimePlaceholder: '7-10 個工作天',
      shippingTerms: '運送條件',
      shippingPlaceholder: '快遞 / 運費另計',
      buyerNote: '買家說明',
      internalMemoTitle: '內部備註',
      internalMemoBody: '僅管理員可見，不會顯示在買家畫面或 PDF 中。',
      documentsTitle: '已發行文件',
      documentsBody: '各版本不可變更，並保留發行當時的備貨與取消結果。',
      version: '版本 {revision}',
      downloadAria: '下載版本 {revision} PDF',
      downloadTitle: '下載 PDF',
      historyTitle: '處理記錄',
      historyBody: '文件發行與作業狀態變更會依時間順序記錄。',
      summaryTitle: '作業摘要',
      currentStage: '目前階段',
      requestedItems: '原需求品項',
      exceptions: '取消或不足',
      preparedTotal: '備貨金額',
      pdfVersion: 'PDF 版本',
      saving: '儲存中...',
      saveResult: '儲存備貨結果',
      issueNewVersion: '發行新 PDF 版本',
      issueResult: '發行備貨結果 PDF',
      revertPicking: '返回備貨',
      workflowNote: '作業備註 / 全部取消原因',
      cancelAll: '取消整份報價',
      unsavedChanges: '尚有未儲存的變更。',
      discard: '捨棄變更',
      save: '儲存',
      saveBarAria: '儲存變更',
      processing: '處理中...',
      cancel: '取消',
      closeToast: '關閉通知',
    },
  },
}

export function getAdminQuoteWorkflowCopy(locale) {
  return resolveLocaleCopy(copy, locale, 'en')
}

export function useAdminQuoteWorkflowCopy() {
  const { locale } = useLocalePath()
  return getAdminQuoteWorkflowCopy(locale)
}

export function getAdminQuoteDateLocale(locale) {
  return {
    kr: 'ko-KR',
    en: 'en-US',
    jp: 'ja-JP',
    'zh-TW': 'zh-TW',
  }[locale] || 'en-US'
}
