import { resolveLocaleCopy, supportedLocales, taiwanLocale, toTaiwanTraditional, useLocalePath } from '../../utils/locale.js'

const copy = {
  kr: {
    shell: {
      aria: '관리자 내비게이션',
      brand: '노블레스 관리자',
      serverVerified: {
        production: '서버에서 검증된 운영 API',
        staging: '서버에서 검증된 스테이징 API',
        development: '개발 관리자 미리보기',
      },
      badge: {
        production: '운영 API',
        staging: '스테이징 API',
        development: '개발 모드',
      },
      nav: {
        dashboard: '관리자 대시보드',
        buyers: '거래처',
        products: '상품',
        categories: '카테고리',
        prices: '가격',
        inquiries: '문의',
        quotes: '견적',
        analytics: '분석',
      },
      backToCatalog: '카탈로그로 돌아가기',
    },
    route: {
      checkingEyebrow: '관리자 API',
      checkingTitle: '관리자 세션 확인 중',
      checkingBody: '서버 관리자 권한 확인 전에 Firebase 인증을 확인하고 있습니다.',
      previewEyebrow: '관리자 미리보기',
      requiredEyebrow: '관리자 API 필요',
      requiredTitle: '관리자 권한이 필요합니다',
      missingConfig: '관리자가 서버 권한 확인으로 로그인하려면 Firebase 클라이언트 설정이 필요합니다.',
      previewBody: '관리자 미리보기는 명시적인 개발 모드에서만 사용할 수 있습니다.',
      releaseBody: '운영 모드는 프론트엔드 상태를 신뢰하지 않습니다. 승인된 관리자 계정으로 로그인하면 서버가 권한을 확인합니다.',
      login: '관리자 로그인',
      productList: '상품 목록',
      account: '계정',
    },
    apiState: {
      loading: '관리자 API 데이터를 불러오는 중입니다...',
      errorEyebrow: '관리자 API 오류',
      errorTitle: '관리자 데이터를 불러올 수 없습니다',
      configError: '관리자 API 접근에는 Firebase 클라이언트 설정이 필요합니다.',
      requestFailed: '관리자 API 요청에 실패했습니다.',
    },
    common: {
      adminApi: '관리자 API',
      all: '전체',
      actions: '작업',
      active: '활성',
      inactive: '비활성',
      visible: '공개',
      hidden: '비공개',
      yes: '예',
      no: '아니오',
      available: '가능',
      unavailable: '불가',
      previous: '이전',
      next: '다음',
      count: '수량',
      status: '상태',
      search: '검색',
      createdAt: '생성일',
      view: '보기',
      show: '표시',
      hide: '숨김',
      set: '설정',
      current: '현재',
      save: '저장',
      saving: '저장 중...',
      back: '돌아가기',
      appendUpdate: '업데이트 추가',
      activate: '활성화',
      deactivate: '비활성화',
      adjustPlusOne: '+1 조정',
    },
    statuses: {
      inquiry: {
        requested: '요청됨',
        checking: '확인 중',
        quoted: '견적 완료',
        confirmed: '확정',
        cancelled: '취소',
      },
      buyer: {
        pending: '대기',
        approved: '승인',
        rejected: '반려',
        suspended: '중지',
        active: '활성',
        withdrawn: '탈퇴',
        blocked: '강퇴',
      },
      quote: {
        draft: '초안',
        sent: '발송',
        accepted: '수락',
        cancelled: '취소',
      },
      visibility: {
        visible: '공개',
        hidden: '비공개',
      },
    },
    dashboard: {
      title: '관리자 대시보드',
      description: '서버 권한 검증 API로 확인한 운영 관리자 요약입니다.',
      viewInquiries: '문의 보기',
      pendingBuyers: '대기 거래처',
      requestedInquiries: '요청된 문의',
      visibleProducts: '공개 상품',
      manualFollowUp: '수동 확인',
      inquiryStatus: '문의 상태',
    },
    buyers: {
      title: '거래처 승인',
      description: 'B2B 거래처 계정을 검토하고 신뢰된 백엔드 API로 승인 상태를 관리합니다.',
      note: '이 화면의 버튼으로 거래처 심사와 로그인 상태를 서버 관리자 API에 바로 반영할 수 있습니다. 권한이 없으면 필요한 권한이 안내됩니다.',
      searchLabel: '거래처 검색',
      searchPlaceholder: '회사, 담당자, 국가 또는 시장',
      setStatus: '{status}',
      reviewStatus: '거래처 심사',
      loginStatus: '로그인',
      statusActions: {
        pending: '대기로 변경',
        approved: '승인하기',
        rejected: '반려하기',
        suspended: '중지하기',
        active: '활성',
        blocked: '강퇴',
      },
      updated: '거래처 상태가 {status}(으)로 변경되었습니다.',
      updateFailed: '거래처 상태를 변경할 수 없습니다.',
      empty: '거래처가 없습니다.',
      notFound: '거래처를 찾을 수 없습니다',
      notFoundDescription: '선택한 거래처 계정을 불러올 수 없습니다.',
      backToBuyers: '거래처로 돌아가기',
      buyerAccount: '거래처 계정',
      detailDescription: '거래처 프로필, 약관 기록, 최근 문의, 승인 상태를 백엔드 API로 확인합니다.',
      detailNote: '거래처 승인은 서버에서 적용됩니다. 프론트엔드 상태와 로컬 저장소는 관리자 권한을 부여하지 않습니다.',
      approvalChecklist: '승인 체크리스트',
      checklist: ['회사 정보 확인', '연락 채널 확인', '시장 배정', '약관 동의 확인', '가격 접근 준비'],
      companyProfile: '회사 프로필',
      accessSetting: '접근 설정',
      contactInformation: '연락처 정보',
      agreementSummary: '약관 요약',
      recentInquiries: '최근 문의',
      noAgreements: '약관 기록이 없습니다.',
      noRecentInquiries: '최근 문의가 없습니다.',
      accepted: '동의',
      notAccepted: '미동의',
    },
    products: {
      title: '상품 관리',
      description: '카탈로그 메타데이터를 확인하고 신뢰된 백엔드 API로 공개 여부를 관리합니다.',
      note: '상품 편집, 가격 변경, 이미지 워크플로, 삭제 작업은 이번 릴리스 범위 밖입니다.',
      code: '상품 코드',
      name: '상품명',
      categoryKey: '카테고리 키',
      material: '재질',
      moq: 'MOQ',
      create: '상품 생성',
      created: '상품이 생성되었습니다.',
      createFailed: '상품을 생성할 수 없습니다.',
      visibleNow: '상품이 공개되었습니다.',
      hiddenNow: '상품이 비공개되었습니다.',
      updateFailed: '상품을 수정할 수 없습니다.',
      nameUpdated: '상품명이 수정되었습니다.',
      searchLabel: '상품 검색',
      searchPlaceholder: 'NB-001 또는 상품명',
      empty: '상품이 없습니다.',
      exportAvailable: '수출 가능',
      isNew: '신규',
      isBest: '베스트',
      viewProduct: '상품 보기',
    },
    categories: {
      title: '카테고리 관리',
      description: '보호된 관리자 API 쓰기로 카탈로그 카테고리를 생성, 확인, 비활성화합니다.',
      note: '카테고리는 공개 여부를 끄는 방식으로 비활성화합니다. 이 화면에서는 삭제 작업을 실행하지 않습니다.',
      key: '카테고리 키',
      englishName: '영문명',
      slug: '슬러그',
      sort: '정렬',
      create: '카테고리 생성',
      created: '카테고리가 생성되었습니다.',
      createFailed: '카테고리를 생성할 수 없습니다.',
      updateFailed: '카테고리를 수정할 수 없습니다.',
      hidden: '카테고리가 비공개되었습니다.',
      visible: '카테고리가 공개되었습니다.',
      nameUpdated: '카테고리명이 수정되었습니다.',
      searchLabel: '카테고리 검색',
      searchPlaceholder: '카테고리 키 또는 이름',
      empty: '카테고리가 없습니다.',
    },
    prices: {
      title: '가격 관리',
      description: '백엔드의 시장별 가격 행을 확인합니다. 공개 카탈로그 메타데이터와 승인 거래처 가격은 분리됩니다.',
      note: '가격 행은 보호된 관리자 API 쓰기로 관리됩니다. 공개 카탈로그 조회에서는 승인 거래처 가격을 노출하지 않습니다.',
      productCode: '상품 코드',
      market: '시장',
      currency: '통화',
      wholesale: '도매가',
      retail: '소매가',
      minRequestAmount: '최소 요청 금액',
      visibleTo: '노출 대상',
      create: '가격 생성',
      created: '가격 행이 생성되었습니다.',
      createFailed: '가격 행을 생성할 수 없습니다.',
      updateFailed: '가격 행을 수정할 수 없습니다.',
      deactivated: '가격 행이 비활성화되었습니다.',
      activated: '가격 행이 활성화되었습니다.',
      adjusted: '도매가가 조정되었습니다.',
      searchLabel: '가격 검색',
      searchPlaceholder: '상품 코드 또는 상품명',
      activeOnly: '활성만',
      empty: '가격 행이 없습니다.',
    },
    inquiries: {
      title: '문의 관리',
      description: '관리자 API에서 확인한 운영 견적 요청 기록입니다.',
      searchLabel: '문의 검색',
      searchPlaceholder: '문의, 회사, 시장 또는 통화',
      inquiryNumber: '문의 번호',
      buyerCompany: '거래처 회사',
      market: '시장',
      currency: '통화',
      totalItems: '상품 수',
      totalQuantity: '총 수량',
      estimatedTotal: '예상 합계',
      backToInquiries: '문의로 돌아가기',
      detailDescription: '관리자 API에서 확인한 운영 문의 상세입니다.',
      buyerInfo: '거래처 정보',
      inquiryStatus: '문의 상태',
      adminMemo: '관리자 메모',
      memoSaved: '관리자 메모가 저장되었습니다.',
      memoFailed: '관리자 메모를 저장할 수 없습니다.',
      statusUpdated: '문의 상태가 {status}(으)로 변경되었습니다.',
      statusFailed: '문의 상태를 변경할 수 없습니다.',
      itemSnapshot: '상품 스냅샷',
      priceSnapshot: '가격 스냅샷',
      subtotal: '소계',
    },
    quotes: {
      title: '견적 관리',
      description: '견적 요청 기록에서 생성한 견적 초안을 확인합니다.',
      note: '견적 초안은 서버에서 문의 스냅샷을 기반으로 생성됩니다. 상태 추적은 가능하며, 외부 발송과 직접 가격 편집은 이번 릴리스에서 수동으로 유지됩니다.',
      searchLabel: '견적 검색',
      searchPlaceholder: '문의 번호 또는 거래처 회사',
      createFromInquiry: '문의 ID로 생성',
      createPlaceholder: '문의 UUID',
      createDraft: '초안 생성',
      draftCreated: '문의 스냅샷에서 견적 초안이 생성되었습니다.',
      createFailed: '견적 초안을 생성할 수 없습니다.',
      inquiryNumber: '문의 번호',
      buyerCompany: '거래처 회사',
      requestedTotal: '요청 합계',
      confirmedTotal: '확정 합계',
      leadTime: '납기',
      viewInquiry: '문의 보기',
      openQuote: '견적 열기',
      empty: '견적 초안이 없습니다.',
      notFound: '견적을 찾을 수 없습니다',
      notFoundDescription: '선택한 견적을 불러올 수 없습니다.',
      backToQuotes: '견적으로 돌아가기',
      backToInquiry: '문의로 돌아가기',
      detailTitle: '관리자 견적',
      detailDescription: '문의 스냅샷에서 생성된 견적 초안 값을 확인합니다.',
      detailNote: '견적 상태 변경은 관리자 추적용으로 사용할 수 있습니다. 외부 발송과 가격 편집은 별도 운영 워크플로 승인 전까지 수동입니다.',
      quoteStatus: '견적 상태',
      statusHelp: '견적 상태 변경은 보호된 관리자 API 쓰기이며 감사 로그를 생성합니다.',
      statusUpdated: '견적 상태가 {status}(으)로 변경되었습니다.',
      statusFailed: '견적 상태를 변경할 수 없습니다.',
      quoteInfo: '견적 정보',
      quoteConditions: '견적 조건',
      shippingNote: '배송 메모',
      quoteItems: '관리자 견적 상품',
      requestedQuantity: '요청 수량',
      confirmedQuantity: '확정 수량',
      requestedPriceSnapshot: '요청 가격 스냅샷',
      confirmedUnitPrice: '확정 단가',
      confirmedSubtotal: '확정 소계',
      noItems: '견적 상품이 없습니다.',
      internalMemo: '내부 메모',
    },
    analytics: {
      title: '분석',
      description: '보호된 관리자 API 응답을 기반으로 한 읽기 전용 운영 요약입니다.',
      note: '분석은 기존 관리자 읽기 endpoint를 사용합니다. 브라우저에서 직접 DB 접근이나 쓰기 작업을 실행하지 않습니다.',
      inquiries: '문의',
      buyers: '거래처',
      products: '상품',
      estimatedTotal: '예상 합계',
      totalRequestRecords: '전체 요청 기록',
      tradeAccounts: '거래처 계정',
      catalogRecords: '카탈로그 기록',
      mixedCurrency: '혼합 통화 참고용',
      inquiryStatus: '문의 상태',
      markets: '시장',
      buyerStatus: '거래처 상태',
      productVisibility: '상품 공개 상태',
      visibility: '공개 상태',
    },
    fields: {
      key: '키',
      name: '이름',
      companyName: '회사명',
      contactName: '담당자',
      company: '회사',
      contact: '연락처',
      email: '이메일',
      country: '국가',
      language: '언어',
      market: '시장',
      currency: '통화',
      created: '생성일',
      salesChannel: '판매 채널',
      businessNumber: '사업자 번호',
      assignedMarket: '배정 시장',
      discountRate: '할인율',
      phone: '전화',
      messenger: '메신저',
      agreement: '약관',
      productName: '상품명',
      productCode: '상품 코드',
      category: '카테고리',
      material: '재질',
      colors: '색상',
      sizes: '사이즈',
      moqDefault: '기본 MOQ',
      slug: '슬러그',
      sort: '정렬',
      inquiry: '문의',
      buyer: '거래처',
      color: '색상',
      size: '사이즈',
      quantity: '수량',
    },
  },
  en: null,
  jp: null,
  cn: null,
}

copy.en = {
  ...copy.kr,
  shell: {
    aria: 'Admin navigation',
    brand: 'Noblesse Admin',
    serverVerified: {
      production: 'Server-verified Production API',
      staging: 'Server-verified Staging API',
      development: 'Development admin preview',
    },
    badge: {
      production: 'Production API',
      staging: 'Staging API',
      development: 'Development mode',
    },
    nav: {
      dashboard: 'Admin Dashboard',
      buyers: 'Buyers',
      products: 'Products',
      categories: 'Categories',
      prices: 'Prices',
      inquiries: 'Inquiries',
      quotes: 'Quotes',
      analytics: 'Analytics',
    },
    backToCatalog: 'Back to Catalog',
  },
  route: {
    checkingEyebrow: 'Admin API',
    checkingTitle: 'Checking admin session',
    checkingBody: 'Firebase authentication is being verified before the server-side admin role check runs.',
    previewEyebrow: 'Admin Preview',
    requiredEyebrow: 'Admin API Required',
    requiredTitle: 'Admin access required',
    missingConfig: 'Firebase client configuration is required before an admin can sign in for the server-side role check.',
    previewBody: 'Admin preview is available only in explicit development mode.',
    releaseBody: 'Release mode does not trust frontend viewer state. Sign in with an approved admin account so the backend can verify the role server-side.',
    login: 'Admin Login',
    productList: 'Product List',
    account: 'Account',
  },
  apiState: {
    loading: 'Loading admin API data...',
    errorEyebrow: 'Admin API Error',
    errorTitle: 'Unable to load admin data',
    configError: 'Firebase client configuration is required for admin API access.',
    requestFailed: 'Admin API request failed.',
  },
  common: {
    adminApi: 'Admin API',
    all: 'All',
    actions: 'Actions',
    active: 'Active',
    inactive: 'Inactive',
    visible: 'Visible',
    hidden: 'Hidden',
    yes: 'Yes',
    no: 'No',
    available: 'Available',
    unavailable: 'Unavailable',
    previous: 'Previous',
    next: 'Next',
    count: 'Count',
    status: 'Status',
    search: 'Search',
    createdAt: 'Created At',
    view: 'View',
    show: 'Show',
    hide: 'Hide',
    set: 'Set',
    current: 'current',
    save: 'Save',
    saving: 'Saving...',
    back: 'Back',
    appendUpdate: 'Append Update',
    activate: 'Activate',
    deactivate: 'Deactivate',
    adjustPlusOne: 'Adjust +1',
  },
  statuses: {
    inquiry: {
      requested: 'Requested',
      checking: 'Checking',
      quoted: 'Quoted',
      confirmed: 'Confirmed',
      cancelled: 'Cancelled',
    },
    buyer: {
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      suspended: 'Suspended',
      active: 'Active',
      withdrawn: 'Withdrawn',
      blocked: 'Expelled',
    },
    quote: {
      draft: 'Draft',
      sent: 'Sent',
      accepted: 'Accepted',
      cancelled: 'Cancelled',
    },
    visibility: {
      visible: 'Visible',
      hidden: 'Hidden',
    },
  },
  dashboard: {
    title: 'Admin Dashboard',
    description: 'Production admin summary from server-side role-verified API.',
    viewInquiries: 'View Inquiries',
    pendingBuyers: 'Pending Buyers',
    requestedInquiries: 'Requested Inquiries',
    visibleProducts: 'Visible Products',
    manualFollowUp: 'Manual Follow-up',
    inquiryStatus: 'Inquiry Status',
  },
  buyers: {
    title: 'Buyer Approval',
    description: 'Review B2B buyer accounts and update approval state through the trusted backend API.',
    note: 'Use the buttons on this page to update buyer review and login status through the server admin API. If access is missing, the required permission is shown.',
    searchLabel: 'Search buyers',
    searchPlaceholder: 'Company, contact, country, or market',
    setStatus: '{status}',
    reviewStatus: 'Buyer Review',
    loginStatus: 'Login',
    statusActions: {
      pending: 'Set Pending',
      approved: 'Approve',
      rejected: 'Reject',
      suspended: 'Suspend Review',
      active: 'Active',
      blocked: 'Expel',
    },
    updated: 'Buyer status updated to {status}.',
    updateFailed: 'Unable to update buyer status.',
    empty: 'No buyers found.',
    notFound: 'Buyer not found',
    notFoundDescription: 'The selected buyer account could not be loaded.',
    backToBuyers: 'Back to Buyers',
    buyerAccount: 'Buyer account',
    detailDescription: 'Review buyer profile, agreement records, recent inquiries, and approval status through the backend API.',
    detailNote: 'Buyer approval is enforced server-side. Frontend state and local storage do not grant admin access.',
    approvalChecklist: 'Approval Checklist',
    checklist: ['Company information reviewed', 'Contact channel reviewed', 'Market assigned', 'Agreement consent checked', 'Price access ready'],
    companyProfile: 'Company Profile',
    accessSetting: 'Access Setting',
    contactInformation: 'Contact Information',
    agreementSummary: 'Agreement Summary',
    recentInquiries: 'Recent Inquiries',
    noAgreements: 'No agreement records found.',
    noRecentInquiries: 'No recent inquiries found.',
    accepted: 'Accepted',
    notAccepted: 'Not accepted',
  },
  products: {
    title: 'Product Management',
    description: 'Review catalog metadata and control public visibility through the trusted backend API.',
    note: 'Product editing, price updates, image workflow, and destructive actions remain out of scope for this release.',
    code: 'Code',
    name: 'Name',
    categoryKey: 'Category Key',
    material: 'Material',
    moq: 'MOQ',
    create: 'Create Product',
    created: 'Product created.',
    createFailed: 'Unable to create product.',
    visibleNow: 'Product is now visible.',
    hiddenNow: 'Product is now hidden.',
    updateFailed: 'Unable to update product.',
    nameUpdated: 'Product name updated.',
    searchLabel: 'Product Search',
    searchPlaceholder: 'NB-001 or product name',
    empty: 'No products found.',
    exportAvailable: 'Export Available',
    isNew: 'New',
    isBest: 'Best',
    viewProduct: 'View Product',
  },
  categories: {
    title: 'Category Management',
    description: 'Create, review, and deactivate catalog categories through protected admin API writes.',
    note: 'Categories are deactivated by setting visibility off. No destructive delete runs from this screen.',
    key: 'Category Key',
    englishName: 'English Name',
    slug: 'Slug',
    sort: 'Sort',
    create: 'Create Category',
    created: 'Category created.',
    createFailed: 'Unable to create category.',
    updateFailed: 'Unable to update category.',
    hidden: 'Category hidden.',
    visible: 'Category visible.',
    nameUpdated: 'Category name updated.',
    searchLabel: 'Search Categories',
    searchPlaceholder: 'category key or name',
    empty: 'No categories found.',
  },
  prices: {
    title: 'Price Management',
    description: 'Review market price rows from the backend. Public catalog metadata remains separate from approved buyer pricing.',
    note: 'Price rows are managed through protected admin API writes. Public catalog reads still never expose approved buyer prices.',
    productCode: 'Product Code',
    market: 'Market',
    currency: 'Currency',
    wholesale: 'Wholesale',
    retail: 'Retail Price',
    minRequestAmount: 'Min Request Amount',
    visibleTo: 'Visible To',
    create: 'Create Price',
    created: 'Price row created.',
    createFailed: 'Unable to create price row.',
    updateFailed: 'Unable to update price row.',
    deactivated: 'Price row deactivated.',
    activated: 'Price row activated.',
    adjusted: 'Wholesale price adjusted.',
    searchLabel: 'Search prices',
    searchPlaceholder: 'Product code or name',
    activeOnly: 'Active only',
    empty: 'No price rows found.',
  },
  inquiries: {
    title: 'Inquiry Management',
    description: 'Production Request Quote records from the admin API.',
    searchLabel: 'Search inquiries',
    searchPlaceholder: 'Inquiry, company, market, or currency',
    inquiryNumber: 'Inquiry Number',
    buyerCompany: 'Buyer Company',
    market: 'Market',
    currency: 'Currency',
    totalItems: 'Total Items',
    totalQuantity: 'Total Quantity',
    estimatedTotal: 'Estimated Total',
    backToInquiries: 'Back to Inquiries',
    detailDescription: 'Production inquiry detail from the admin API.',
    buyerInfo: 'Buyer Info',
    inquiryStatus: 'Inquiry Status',
    adminMemo: 'Admin Memo',
    memoSaved: 'Admin memo saved.',
    memoFailed: 'Unable to save admin memo.',
    statusUpdated: 'Inquiry status updated to {status}.',
    statusFailed: 'Unable to update inquiry status.',
    itemSnapshot: 'Item Snapshot',
    priceSnapshot: 'priceSnapshot',
    subtotal: 'Subtotal',
  },
  quotes: {
    title: 'Admin Quotes',
    description: 'Review quote drafts created from Request Quote records.',
    note: 'Quote drafts are generated server-side from inquiry snapshots. Status tracking is available; external sending and direct price editing remain manual for this release.',
    searchLabel: 'Search quotes',
    searchPlaceholder: 'Inquiry number or buyer company',
    createFromInquiry: 'Create from inquiry ID',
    createPlaceholder: 'Inquiry UUID',
    createDraft: 'Create Draft',
    draftCreated: 'Quote draft created from inquiry snapshot.',
    createFailed: 'Unable to create quote draft.',
    inquiryNumber: 'Inquiry Number',
    buyerCompany: 'Buyer Company',
    requestedTotal: 'Requested Total',
    confirmedTotal: 'Confirmed Total',
    leadTime: 'Lead Time',
    viewInquiry: 'View Inquiry',
    openQuote: 'Open Quote',
    empty: 'No quote drafts found.',
    notFound: 'Quote not found',
    notFoundDescription: 'The selected quote could not be loaded.',
    backToQuotes: 'Back to Quotes',
    backToInquiry: 'Back to Inquiry',
    detailTitle: 'Admin Quote',
    detailDescription: 'Review quote draft values generated from an inquiry snapshot.',
    detailNote: 'Quote status changes are available for admin tracking. External sending and price editing remain manual until a separate production workflow is approved.',
    quoteStatus: 'Quote Status',
    statusHelp: 'Changing quote status is a protected admin API write and creates an audit log entry.',
    statusUpdated: 'Quote status updated to {status}.',
    statusFailed: 'Unable to update quote status.',
    quoteInfo: 'Quote Info',
    quoteConditions: 'Quote Conditions',
    shippingNote: 'Shipping Note',
    quoteItems: 'Admin Quote Items',
    requestedQuantity: 'Requested Quantity',
    confirmedQuantity: 'Confirmed Quantity',
    requestedPriceSnapshot: 'Requested priceSnapshot',
    confirmedUnitPrice: 'Confirmed Unit Price',
    confirmedSubtotal: 'Confirmed Subtotal',
    noItems: 'No quote items found.',
    internalMemo: 'Internal Memo',
  },
  analytics: {
    title: 'Analytics',
    description: 'Read-only operational summary based on protected Admin API responses.',
    note: 'Analytics uses existing admin read endpoints. No browser direct database access or write operation runs here.',
    inquiries: 'Inquiries',
    buyers: 'Buyers',
    products: 'Products',
    estimatedTotal: 'Estimated Total',
    totalRequestRecords: 'Total request records',
    tradeAccounts: 'Trade accounts',
    catalogRecords: 'Catalog records',
    mixedCurrency: 'Mixed-currency reference only',
    inquiryStatus: 'Inquiry Status',
    markets: 'Markets',
    buyerStatus: 'Buyer Status',
    productVisibility: 'Product Visibility',
    visibility: 'Visibility',
  },
  fields: {
    key: 'Key',
    name: 'Name',
    companyName: 'Company Name',
    contactName: 'Contact Name',
    company: 'Company',
    contact: 'Contact',
    email: 'Email',
    country: 'Country',
    language: 'Language',
    market: 'Market',
    currency: 'Currency',
    created: 'Created',
    salesChannel: 'Sales Channel',
    businessNumber: 'Business Number',
    assignedMarket: 'Assigned Market',
    discountRate: 'Discount Rate',
    phone: 'Phone',
    messenger: 'Messenger',
    agreement: 'Agreement',
    productName: 'Product Name',
    productCode: 'Product Code',
    category: 'Category',
    material: 'Material',
    colors: 'Colors',
    sizes: 'Sizes',
    moqDefault: 'MOQ Default',
    slug: 'Slug',
    sort: 'Sort',
    inquiry: 'Inquiry',
    buyer: 'Buyer',
    color: 'Color',
    size: 'Size',
    quantity: 'Quantity',
  },
}

copy.jp = {
  ...copy.en,
  shell: {
    aria: '管理ナビゲーション',
    brand: 'Noblesse 管理',
    serverVerified: {
      production: 'サーバー検証済み本番API',
      staging: 'サーバー検証済みステージングAPI',
      development: '開発用管理プレビュー',
    },
    badge: {
      production: '本番API',
      staging: 'ステージングAPI',
      development: '開発モード',
    },
    nav: {
      dashboard: '管理ダッシュボード',
      buyers: '取引先',
      products: '商品',
      categories: 'カテゴリー',
      prices: '価格',
      inquiries: 'お問い合わせ',
      quotes: '見積もり',
      analytics: '分析',
    },
    backToCatalog: 'カタログに戻る',
  },
  route: {
    checkingEyebrow: '管理API',
    checkingTitle: '管理者セッション確認中',
    checkingBody: 'サーバー側の管理者権限確認前に Firebase 認証を確認しています。',
    previewEyebrow: '管理プレビュー',
    requiredEyebrow: '管理APIが必要です',
    requiredTitle: '管理者権限が必要です',
    missingConfig: '管理者がサーバー側の権限確認でログインするには Firebase クライアント設定が必要です。',
    previewBody: '管理プレビューは明示的な開発モードでのみ使用できます。',
    releaseBody: '本番モードではフロントエンド状態を信頼しません。承認済み管理者アカウントでログインすると、バックエンドがサーバー側で権限を確認します。',
    login: '管理者ログイン',
    productList: '商品一覧',
    account: 'アカウント',
  },
  apiState: {
    loading: '管理APIデータを読み込み中です...',
    errorEyebrow: '管理APIエラー',
    errorTitle: '管理データを読み込めません',
    configError: '管理APIアクセスには Firebase クライアント設定が必要です。',
    requestFailed: '管理APIリクエストに失敗しました。',
  },
  common: {
    adminApi: '管理API',
    all: 'すべて',
    actions: '操作',
    active: '有効',
    inactive: '無効',
    visible: '公開',
    hidden: '非公開',
    yes: 'はい',
    no: 'いいえ',
    available: '可能',
    unavailable: '不可',
    previous: '前へ',
    next: '次へ',
    count: '件数',
    status: '状態',
    search: '検索',
    createdAt: '作成日',
    view: '表示',
    show: '表示',
    hide: '非表示',
    set: '設定',
    current: '現在',
    save: '保存',
    saving: '保存中...',
    back: '戻る',
    appendUpdate: '更新を追加',
    activate: '有効化',
    deactivate: '無効化',
    adjustPlusOne: '+1調整',
  },
  statuses: {
    inquiry: {
      requested: '依頼済み',
      checking: '確認中',
      quoted: '見積済み',
      confirmed: '確定',
      cancelled: '取消',
    },
    buyer: {
      pending: '保留',
      approved: '承認済み',
      rejected: '否認',
      suspended: '停止',
      active: '有効',
      withdrawn: '退会',
      blocked: '強制退会',
    },
    quote: {
      draft: '下書き',
      sent: '送信済み',
      accepted: '承認済み',
      cancelled: '取消',
    },
    visibility: {
      visible: '公開',
      hidden: '非公開',
    },
  },
  dashboard: {
    title: '管理ダッシュボード',
    description: 'サーバー側の権限検証APIで確認した本番管理サマリーです。',
    viewInquiries: 'お問い合わせを見る',
    pendingBuyers: '保留中の取引先',
    requestedInquiries: '依頼されたお問い合わせ',
    visibleProducts: '公開商品',
    manualFollowUp: '手動確認',
    inquiryStatus: 'お問い合わせ状態',
  },
  buyers: {
    title: '取引先承認',
    description: 'B2B取引先アカウントを確認し、信頼済みバックエンドAPIで承認状態を管理します。',
    note: 'この画面のボタンから、取引先審査とログイン状態をサーバー管理APIに反映できます。権限がない場合は必要な権限を表示します。',
    searchLabel: '取引先検索',
    searchPlaceholder: '会社、担当者、国、または市場',
    setStatus: '{status}',
    reviewStatus: '取引先審査',
    loginStatus: 'ログイン',
    statusActions: {
      pending: '保留に戻す',
      approved: '承認する',
      rejected: '否認する',
      suspended: '停止する',
      active: '有効',
      blocked: '強制退会',
    },
    updated: '取引先状態を {status} に変更しました。',
    updateFailed: '取引先状態を変更できません。',
    empty: '取引先がありません。',
    notFound: '取引先が見つかりません',
    notFoundDescription: '選択した取引先アカウントを読み込めませんでした。',
    backToBuyers: '取引先に戻る',
    buyerAccount: '取引先アカウント',
    detailDescription: '取引先プロフィール、同意記録、最近のお問い合わせ、承認状態をバックエンドAPIで確認します。',
    detailNote: '取引先承認はサーバー側で適用されます。フロントエンド状態とローカルストレージは管理権限を付与しません。',
    approvalChecklist: '承認チェックリスト',
    checklist: ['会社情報確認', '連絡先確認', '市場割当', '同意確認', '価格アクセス準備'],
    companyProfile: '会社プロフィール',
    accessSetting: 'アクセス設定',
    contactInformation: '連絡先情報',
    agreementSummary: '同意サマリー',
    recentInquiries: '最近のお問い合わせ',
    noAgreements: '同意記録がありません。',
    noRecentInquiries: '最近のお問い合わせはありません。',
    accepted: '同意済み',
    notAccepted: '未同意',
  },
  products: {
    title: '商品管理',
    description: 'カタログメタデータを確認し、信頼済みバックエンドAPIで公開状態を管理します。',
    note: '商品編集、価格更新、画像ワークフロー、削除操作は今回のリリース範囲外です。',
    code: '商品コード',
    name: '商品名',
    categoryKey: 'カテゴリーキー',
    material: '素材',
    moq: 'MOQ',
    create: '商品作成',
    created: '商品を作成しました。',
    createFailed: '商品を作成できません。',
    visibleNow: '商品を公開しました。',
    hiddenNow: '商品を非公開にしました。',
    updateFailed: '商品を更新できません。',
    nameUpdated: '商品名を更新しました。',
    searchLabel: '商品検索',
    searchPlaceholder: 'NB-001 または商品名',
    empty: '商品がありません。',
    exportAvailable: '輸出可',
    isNew: '新着',
    isBest: 'ベスト',
    viewProduct: '商品を見る',
  },
  categories: {
    title: 'カテゴリー管理',
    description: '保護された管理API書き込みでカタログカテゴリーを作成、確認、無効化します。',
    note: 'カテゴリーは公開状態をオフにして無効化します。この画面では削除操作は行いません。',
    key: 'カテゴリーキー',
    englishName: '英語名',
    slug: 'スラッグ',
    sort: '並び順',
    create: 'カテゴリー作成',
    created: 'カテゴリーを作成しました。',
    createFailed: 'カテゴリーを作成できません。',
    updateFailed: 'カテゴリーを更新できません。',
    hidden: 'カテゴリーを非公開にしました。',
    visible: 'カテゴリーを公開しました。',
    nameUpdated: 'カテゴリー名を更新しました。',
    searchLabel: 'カテゴリー検索',
    searchPlaceholder: 'カテゴリーキーまたは名前',
    empty: 'カテゴリーがありません。',
  },
  prices: {
    title: '価格管理',
    description: 'バックエンドの市場別価格行を確認します。公開カタログメタデータと承認済み取引先価格は分離されます。',
    note: '価格行は保護された管理API書き込みで管理します。公開カタログ読み取りでは承認済み取引先価格を公開しません。',
    productCode: '商品コード',
    market: '市場',
    currency: '通貨',
    wholesale: '卸価格',
    retail: '小売価格',
    minRequestAmount: '最小依頼金額',
    visibleTo: '表示対象',
    create: '価格作成',
    created: '価格行を作成しました。',
    createFailed: '価格行を作成できません。',
    updateFailed: '価格行を更新できません。',
    deactivated: '価格行を無効化しました。',
    activated: '価格行を有効化しました。',
    adjusted: '卸価格を調整しました。',
    searchLabel: '価格検索',
    searchPlaceholder: '商品コードまたは商品名',
    activeOnly: '有効のみ',
    empty: '価格行がありません。',
  },
  inquiries: {
    title: 'お問い合わせ管理',
    description: '管理APIから確認した本番見積依頼記録です。',
    searchLabel: 'お問い合わせ検索',
    searchPlaceholder: 'お問い合わせ、会社、市場、または通貨',
    inquiryNumber: 'お問い合わせ番号',
    buyerCompany: '取引先会社',
    market: '市場',
    currency: '通貨',
    totalItems: '商品数',
    totalQuantity: '合計数量',
    estimatedTotal: '見積合計',
    backToInquiries: 'お問い合わせに戻る',
    detailDescription: '管理APIから確認した本番お問い合わせ詳細です。',
    buyerInfo: '取引先情報',
    inquiryStatus: 'お問い合わせ状態',
    adminMemo: '管理メモ',
    memoSaved: '管理メモを保存しました。',
    memoFailed: '管理メモを保存できません。',
    statusUpdated: 'お問い合わせ状態を {status} に変更しました。',
    statusFailed: 'お問い合わせ状態を変更できません。',
    itemSnapshot: '商品スナップショット',
    priceSnapshot: '価格スナップショット',
    subtotal: '小計',
  },
  quotes: {
    title: '見積もり管理',
    description: '見積依頼記録から作成された見積もり下書きを確認します。',
    note: '見積もり下書きはサーバー側でお問い合わせスナップショットから生成されます。状態追跡は可能で、外部送信と直接価格編集は今回のリリースでは手動です。',
    searchLabel: '見積もり検索',
    searchPlaceholder: 'お問い合わせ番号または取引先会社',
    createFromInquiry: 'お問い合わせIDから作成',
    createPlaceholder: 'お問い合わせUUID',
    createDraft: '下書き作成',
    draftCreated: 'お問い合わせスナップショットから見積もり下書きを作成しました。',
    createFailed: '見積もり下書きを作成できません。',
    inquiryNumber: 'お問い合わせ番号',
    buyerCompany: '取引先会社',
    requestedTotal: '依頼合計',
    confirmedTotal: '確定合計',
    leadTime: '納期',
    viewInquiry: 'お問い合わせを見る',
    openQuote: '見積もりを開く',
    empty: '見積もり下書きがありません。',
    notFound: '見積もりが見つかりません',
    notFoundDescription: '選択した見積もりを読み込めませんでした。',
    backToQuotes: '見積もりに戻る',
    backToInquiry: 'お問い合わせに戻る',
    detailTitle: '管理見積もり',
    detailDescription: 'お問い合わせスナップショットから生成された見積もり下書き値を確認します。',
    detailNote: '見積もり状態変更は管理追跡に利用できます。外部送信と価格編集は別途本番ワークフロー承認まで手動です。',
    quoteStatus: '見積もり状態',
    statusHelp: '見積もり状態変更は保護された管理API書き込みで、監査ログを作成します。',
    statusUpdated: '見積もり状態を {status} に変更しました。',
    statusFailed: '見積もり状態を変更できません。',
    quoteInfo: '見積もり情報',
    quoteConditions: '見積条件',
    shippingNote: '配送メモ',
    quoteItems: '管理見積もり商品',
    requestedQuantity: '依頼数量',
    confirmedQuantity: '確定数量',
    requestedPriceSnapshot: '依頼価格スナップショット',
    confirmedUnitPrice: '確定単価',
    confirmedSubtotal: '確定小計',
    noItems: '見積もり商品がありません。',
    internalMemo: '内部メモ',
  },
  analytics: {
    title: '分析',
    description: '保護された管理API応答に基づく読み取り専用の運用サマリーです。',
    note: '分析は既存の管理読み取りエンドポイントを使用します。ブラウザから直接DBアクセスや書き込み操作は行いません。',
    inquiries: 'お問い合わせ',
    buyers: '取引先',
    products: '商品',
    estimatedTotal: '見積合計',
    totalRequestRecords: '全依頼記録',
    tradeAccounts: '取引先アカウント',
    catalogRecords: 'カタログ記録',
    mixedCurrency: '混合通貨の参考値',
    inquiryStatus: 'お問い合わせ状態',
    markets: '市場',
    buyerStatus: '取引先状態',
    productVisibility: '商品公開状態',
    visibility: '公開状態',
  },
  fields: {
    key: 'キー',
    name: '名前',
    companyName: '会社名',
    contactName: '担当者名',
    company: '会社',
    contact: '担当者',
    email: 'メール',
    country: '国',
    language: '言語',
    market: '市場',
    currency: '通貨',
    created: '作成日',
    salesChannel: '販売チャネル',
    businessNumber: '事業者番号',
    assignedMarket: '割当市場',
    discountRate: '割引率',
    phone: '電話',
    messenger: 'メッセンジャー',
    agreement: '同意',
    productName: '商品名',
    productCode: '商品コード',
    category: 'カテゴリー',
    material: '素材',
    colors: '色',
    sizes: 'サイズ',
    moqDefault: '基本MOQ',
    slug: 'スラッグ',
    sort: '並び順',
    inquiry: 'お問い合わせ',
    buyer: '取引先',
    color: '色',
    size: 'サイズ',
    quantity: '数量',
  },
}

copy.cn = {
  ...copy.en,
  shell: {
    aria: '管理员导航',
    brand: 'Noblesse 管理',
    serverVerified: {
      production: '服务器验证的生产环境 API',
      staging: '服务器验证的预发布 API',
      development: '开发管理员预览',
    },
    badge: {
      production: '生产环境 API',
      staging: '预发布 API',
      development: '开发模式',
    },
    nav: {
      dashboard: '管理仪表板',
      buyers: '客户',
      products: '产品',
      categories: '分类',
      prices: '价格',
      inquiries: '询价',
      quotes: '报价',
      analytics: '分析',
    },
    backToCatalog: '返回目录',
  },
  route: {
    checkingEyebrow: '管理员 API',
    checkingTitle: '正在检查管理员会话',
    checkingBody: '在服务器端管理员权限检查前，正在验证 Firebase 身份认证。',
    previewEyebrow: '管理员预览',
    requiredEyebrow: '需要管理员 API',
    requiredTitle: '需要管理员权限',
    missingConfig: '管理员通过服务器权限检查登录前，需要 Firebase 客户端配置。',
    previewBody: '管理员预览仅在明确的开发模式下可用。',
    releaseBody: '生产模式不会信任前端状态。请使用已批准的管理员账号登录，由后端在服务器端验证权限。',
    login: '管理员登录',
    productList: '产品列表',
    account: '账户',
  },
  apiState: {
    loading: '正在加载管理员 API 数据...',
    errorEyebrow: '管理员 API 错误',
    errorTitle: '无法加载管理员数据',
    configError: '访问管理员 API 需要 Firebase 客户端配置。',
    requestFailed: '管理员 API 请求失败。',
  },
  common: {
    adminApi: '管理员 API',
    all: '全部',
    actions: '操作',
    active: '启用',
    inactive: '停用',
    visible: '公开',
    hidden: '隐藏',
    yes: '是',
    no: '否',
    available: '可用',
    unavailable: '不可用',
    previous: '上一页',
    next: '下一页',
    count: '数量',
    status: '状态',
    search: '搜索',
    createdAt: '创建时间',
    view: '查看',
    show: '显示',
    hide: '隐藏',
    set: '设置',
    current: '当前',
    save: '保存',
    saving: '保存中...',
    back: '返回',
    appendUpdate: '追加更新',
    activate: '启用',
    deactivate: '停用',
    adjustPlusOne: '+1 调整',
  },
  statuses: {
    inquiry: {
      requested: '已请求',
      checking: '确认中',
      quoted: '已报价',
      confirmed: '已确认',
      cancelled: '已取消',
    },
    buyer: {
      pending: '待审核',
      approved: '已批准',
      rejected: '已拒绝',
      suspended: '已暂停',
      active: '启用',
      withdrawn: '退出',
      blocked: '强制移除',
    },
    quote: {
      draft: '草稿',
      sent: '已发送',
      accepted: '已接受',
      cancelled: '已取消',
    },
    visibility: {
      visible: '公开',
      hidden: '隐藏',
    },
  },
  dashboard: {
    title: '管理仪表板',
    description: '通过服务器权限验证 API 确认的生产环境管理摘要。',
    viewInquiries: '查看询价',
    pendingBuyers: '待审核客户',
    requestedInquiries: '已请求询价',
    visibleProducts: '公开产品',
    manualFollowUp: '人工跟进',
    inquiryStatus: '询价状态',
  },
  buyers: {
    title: '客户审批',
    description: '查看 B2B 客户账户，并通过可信后端 API 更新审批状态。',
    note: '可使用本页按钮通过服务器管理员 API 更新客户审核和登录状态。权限不足时会显示所需权限。',
    searchLabel: '搜索客户',
    searchPlaceholder: '公司、联系人、国家或市场',
    setStatus: '{status}',
    reviewStatus: '客户审核',
    loginStatus: '登录',
    statusActions: {
      pending: '改为待审核',
      approved: '批准',
      rejected: '拒绝',
      suspended: '暂停',
      active: '启用',
      blocked: '强制移除',
    },
    updated: '客户状态已更新为 {status}。',
    updateFailed: '无法更新客户状态。',
    empty: '没有客户。',
    notFound: '未找到客户',
    notFoundDescription: '无法加载所选客户账户。',
    backToBuyers: '返回客户',
    buyerAccount: '客户账户',
    detailDescription: '通过后端 API 查看客户资料、协议记录、最近询价和审批状态。',
    detailNote: '客户审批在服务器端执行。前端状态和本地存储不会授予管理员权限。',
    approvalChecklist: '审批检查表',
    checklist: ['公司信息已确认', '联系渠道已确认', '市场已分配', '协议同意已确认', '价格访问已准备'],
    companyProfile: '公司资料',
    accessSetting: '访问设置',
    contactInformation: '联系信息',
    agreementSummary: '协议摘要',
    recentInquiries: '最近询价',
    noAgreements: '没有协议记录。',
    noRecentInquiries: '没有最近询价。',
    accepted: '已同意',
    notAccepted: '未同意',
  },
  products: {
    title: '产品管理',
    description: '查看目录元数据，并通过可信后端 API 控制公开状态。',
    note: '产品编辑、价格更新、图片流程和删除操作不在本次发布范围内。',
    code: '产品代码',
    name: '产品名称',
    categoryKey: '分类键',
    material: '材质',
    moq: 'MOQ',
    create: '创建产品',
    created: '产品已创建。',
    createFailed: '无法创建产品。',
    visibleNow: '产品已公开。',
    hiddenNow: '产品已隐藏。',
    updateFailed: '无法更新产品。',
    nameUpdated: '产品名称已更新。',
    searchLabel: '产品搜索',
    searchPlaceholder: 'NB-001 或产品名称',
    empty: '没有产品。',
    exportAvailable: '可出口',
    isNew: '新品',
    isBest: '热销',
    viewProduct: '查看产品',
  },
  categories: {
    title: '分类管理',
    description: '通过受保护的管理员 API 写入创建、查看和停用目录分类。',
    note: '分类通过关闭公开状态停用。本页面不会执行删除操作。',
    key: '分类键',
    englishName: '英文名称',
    slug: 'Slug',
    sort: '排序',
    create: '创建分类',
    created: '分类已创建。',
    createFailed: '无法创建分类。',
    updateFailed: '无法更新分类。',
    hidden: '分类已隐藏。',
    visible: '分类已公开。',
    nameUpdated: '分类名称已更新。',
    searchLabel: '搜索分类',
    searchPlaceholder: '分类键或名称',
    empty: '没有分类。',
  },
  prices: {
    title: '价格管理',
    description: '查看后端中的市场价格行。公开目录元数据与已批准客户价格保持分离。',
    note: '价格行通过受保护的管理员 API 写入管理。公开目录读取不会暴露已批准客户价格。',
    productCode: '产品代码',
    market: '市场',
    currency: '货币',
    wholesale: '批发价',
    retail: '零售价',
    minRequestAmount: '最低请求金额',
    visibleTo: '可见对象',
    create: '创建价格',
    created: '价格行已创建。',
    createFailed: '无法创建价格行。',
    updateFailed: '无法更新价格行。',
    deactivated: '价格行已停用。',
    activated: '价格行已启用。',
    adjusted: '批发价已调整。',
    searchLabel: '搜索价格',
    searchPlaceholder: '产品代码或产品名称',
    activeOnly: '仅启用',
    empty: '没有价格行。',
  },
  inquiries: {
    title: '询价管理',
    description: '从管理员 API 查看生产环境报价请求记录。',
    searchLabel: '搜索询价',
    searchPlaceholder: '询价、公司、市场或货币',
    inquiryNumber: '询价编号',
    buyerCompany: '客户公司',
    market: '市场',
    currency: '货币',
    totalItems: '产品数',
    totalQuantity: '总数量',
    estimatedTotal: '预计合计',
    backToInquiries: '返回询价',
    detailDescription: '从管理员 API 查看生产环境询价详情。',
    buyerInfo: '客户信息',
    inquiryStatus: '询价状态',
    adminMemo: '管理员备注',
    memoSaved: '管理员备注已保存。',
    memoFailed: '无法保存管理员备注。',
    statusUpdated: '询价状态已更新为 {status}。',
    statusFailed: '无法更新询价状态。',
    itemSnapshot: '产品快照',
    priceSnapshot: '价格快照',
    subtotal: '小计',
  },
  quotes: {
    title: '报价管理',
    description: '查看从报价请求记录创建的报价草稿。',
    note: '报价草稿由服务器根据询价快照生成。状态跟踪可用；外部发送和直接价格编辑在本次发布中仍为手动。',
    searchLabel: '搜索报价',
    searchPlaceholder: '询价编号或客户公司',
    createFromInquiry: '从询价 ID 创建',
    createPlaceholder: '询价 UUID',
    createDraft: '创建草稿',
    draftCreated: '已从询价快照创建报价草稿。',
    createFailed: '无法创建报价草稿。',
    inquiryNumber: '询价编号',
    buyerCompany: '客户公司',
    requestedTotal: '请求合计',
    confirmedTotal: '确认合计',
    leadTime: '交期',
    viewInquiry: '查看询价',
    openQuote: '打开报价',
    empty: '没有报价草稿。',
    notFound: '未找到报价',
    notFoundDescription: '无法加载所选报价。',
    backToQuotes: '返回报价',
    backToInquiry: '返回询价',
    detailTitle: '管理员报价',
    detailDescription: '查看从询价快照生成的报价草稿值。',
    detailNote: '报价状态变更可用于管理员跟踪。外部发送和价格编辑在单独生产流程批准前保持手动。',
    quoteStatus: '报价状态',
    statusHelp: '更改报价状态是受保护的管理员 API 写入，并会创建审计日志。',
    statusUpdated: '报价状态已更新为 {status}。',
    statusFailed: '无法更新报价状态。',
    quoteInfo: '报价信息',
    quoteConditions: '报价条件',
    shippingNote: '配送备注',
    quoteItems: '管理员报价产品',
    requestedQuantity: '请求数量',
    confirmedQuantity: '确认数量',
    requestedPriceSnapshot: '请求价格快照',
    confirmedUnitPrice: '确认单价',
    confirmedSubtotal: '确认小计',
    noItems: '没有报价产品。',
    internalMemo: '内部备注',
  },
  analytics: {
    title: '分析',
    description: '基于受保护管理员 API 响应的只读运营摘要。',
    note: '分析使用现有管理员读取端点。浏览器不会直接访问数据库或执行写入操作。',
    inquiries: '询价',
    buyers: '客户',
    products: '产品',
    estimatedTotal: '预计合计',
    totalRequestRecords: '全部请求记录',
    tradeAccounts: '客户账户',
    catalogRecords: '目录记录',
    mixedCurrency: '混合货币仅供参考',
    inquiryStatus: '询价状态',
    markets: '市场',
    buyerStatus: '客户状态',
    productVisibility: '产品公开状态',
    visibility: '公开状态',
  },
  fields: {
    key: '键',
    name: '名称',
    companyName: '公司名称',
    contactName: '联系人',
    company: '公司',
    contact: '联系人',
    email: '邮箱',
    country: '国家',
    language: '语言',
    market: '市场',
    currency: '货币',
    created: '创建时间',
    salesChannel: '销售渠道',
    businessNumber: '营业编号',
    assignedMarket: '分配市场',
    discountRate: '折扣率',
    phone: '电话',
    messenger: '通讯工具',
    agreement: '协议',
    productName: '产品名称',
    productCode: '产品代码',
    category: '分类',
    material: '材质',
    colors: '颜色',
    sizes: '尺寸',
    moqDefault: '默认 MOQ',
    slug: 'Slug',
    sort: '排序',
    inquiry: '询价',
    buyer: '客户',
    color: '颜色',
    size: '尺寸',
    quantity: '数量',
  },
}

const catalogEntryCopy = {
  kr: {
    navLabel: '새 상품 등록',
    title: '새 상품 등록',
    description: '카테고리, 상품, 가격을 한 화면에서 순서대로 등록합니다.',
    note: '실제 운영 데이터가 저장됩니다. 입력값을 확인한 뒤 저장하세요.',
    progressLabel: '상품 등록 단계',
    steps: {
      category: '카테고리',
      product: '상품 정보',
      price: '가격',
      confirm: '확인 및 저장',
    },
    category: {
      title: '1단계 — 카테고리',
      resource: '카테고리',
      useExisting: '기존 카테고리 선택',
      createNew: '새 카테고리 생성',
      existingLabel: '기존 카테고리',
      selectPlaceholder: '카테고리를 선택하세요',
      key: '카테고리 키',
      name: '카테고리명',
      nameKo: '한국어명',
      nameJa: '일본어명',
      slug: '슬러그',
      sort: '정렬 순서',
      visible: '공개 상태',
      createNow: '카테고리 즉시 생성',
      created: '카테고리 생성 완료',
    },
    product: {
      title: '2단계 — 상품 정보',
      code: '상품 코드',
      name: '상품명',
      description: '설명',
      descriptionPlaceholder: '소재, 특징, 거래 안내에 필요한 설명',
      category: '카테고리',
      material: '소재',
      moq: 'MOQ',
      visible: '공개 상태',
    },
    price: {
      title: '4단계 — 가격',
      market: '시장',
      currency: '통화',
      wholesale: '가격',
      retail: '소비자가',
      moq: 'MOQ',
      minOrderAmount: '최소 문의 금액',
      active: '가격 활성 상태',
    },
    confirm: {
      title: '4단계 — 확인 및 저장',
      category: '카테고리',
      productCode: '상품 코드',
      productName: '상품명',
      market: '시장',
      currency: '통화',
      price: '가격',
      visibility: '공개 여부',
    },
    validation: {
      categoryRequired: '카테고리를 선택하거나 생성하세요.',
      categoryKeyRequired: '카테고리 키를 입력하세요.',
      categoryNameRequired: '카테고리명을 입력하세요.',
      slugRequired: '슬러그를 입력하세요.',
      categoryConflict: '이미 같은 카테고리 키가 있습니다.',
      productCodeRequired: '상품 코드를 입력하세요.',
      productNameRequired: '상품명을 입력하세요.',
      productConflict: '이미 같은 상품 코드가 있습니다.',
      marketRequired: '시장을 선택하세요.',
      currencyRequired: '통화를 선택하세요.',
      priceRequired: '가격은 0보다 커야 합니다.',
      retailPriceInvalid: '소비자가는 비워두거나 0보다 큰 숫자여야 합니다.',
      moqRequired: 'MOQ는 1 이상이어야 합니다.',
    },
    errors: {
      unauthorized: '로그인이 필요합니다.',
      forbidden: '관리자 권한이 없습니다.',
      conflict: '이미 존재하는 항목입니다. 입력값을 확인하세요.',
      server: '서버 오류가 발생했습니다. 잠시 후 다시 시도하세요.',
      network: '네트워크 연결을 확인하세요.',
      unknown: '요청을 처리할 수 없습니다.',
    },
    success: {
      title: '상품 등록이 완료되었습니다.',
      saved: '카테고리, 상품, 가격 등록이 완료되었습니다.',
      viewProduct: '생성된 상품 보기',
      productList: '상품 목록',
      continueAnother: '다른 상품 계속 등록',
    },
    createdResource: '{resource}가 생성되었습니다.',
    productList: '상품 목록',
    previous: '이전',
    next: '다음',
    save: '저장',
    saving: '저장 중...',
    cancel: '취소',
    confirmCancel: '작성 중인 내용이 있습니다. 취소할까요?',
  },
  en: {
    navLabel: 'Add Product',
    title: 'Add Product',
    description: 'Register category, product, and price in one guided flow.',
    note: 'This saves real production catalog data. Review values before saving.',
    progressLabel: 'Product entry steps',
    steps: {
      category: 'Category',
      product: 'Product Info',
      price: 'Price',
      confirm: 'Review and Save',
    },
    category: {
      title: 'Step 1 — Category',
      resource: 'Category',
      useExisting: 'Use existing category',
      createNew: 'Create new category',
      existingLabel: 'Existing category',
      selectPlaceholder: 'Select a category',
      key: 'Category key',
      name: 'Category name',
      nameKo: 'Korean name',
      nameJa: 'Japanese name',
      slug: 'Slug',
      sort: 'Sort order',
      visible: 'Visible',
      createNow: 'Create category now',
      created: 'Category created',
    },
    product: {
      title: 'Step 2 — Product Info',
      code: 'Product code',
      name: 'Product name',
      description: 'Description',
      descriptionPlaceholder: 'Material, features, and trade notes',
      category: 'Category',
      material: 'Material',
      moq: 'MOQ',
      visible: 'Visible',
    },
    price: {
      title: 'Step 4 — Price',
      market: 'Market',
      currency: 'Currency',
      wholesale: 'Price',
      retail: 'Retail price',
      moq: 'MOQ',
      minOrderAmount: 'Minimum inquiry amount',
      active: 'Price active',
    },
    confirm: {
      title: 'Step 4 — Review and Save',
      category: 'Category',
      productCode: 'Product code',
      productName: 'Product name',
      market: 'Market',
      currency: 'Currency',
      price: 'Price',
      visibility: 'Visibility',
    },
    validation: {
      categoryRequired: 'Select or create a category.',
      categoryKeyRequired: 'Enter a category key.',
      categoryNameRequired: 'Enter a category name.',
      slugRequired: 'Enter a slug.',
      categoryConflict: 'A category with this key already exists.',
      productCodeRequired: 'Enter a product code.',
      productNameRequired: 'Enter a product name.',
      productConflict: 'A product with this code already exists.',
      marketRequired: 'Select a market.',
      currencyRequired: 'Select a currency.',
      priceRequired: 'Price must be greater than 0.',
      retailPriceInvalid: 'Retail price must be empty or greater than 0.',
      moqRequired: 'MOQ must be at least 1.',
    },
    errors: {
      unauthorized: 'Login is required.',
      forbidden: 'Admin access is required.',
      conflict: 'This item already exists. Check the input values.',
      server: 'A server error occurred. Try again later.',
      network: 'Check the network connection.',
      unknown: 'Unable to process the request.',
    },
    success: {
      title: 'Product registration is complete.',
      saved: 'Category, product, and price have been saved.',
      viewProduct: 'View created product',
      productList: 'Product list',
      continueAnother: 'Add another product',
    },
    createdResource: '{resource} has been created.',
    productList: 'Product list',
    previous: 'Previous',
    next: 'Next',
    save: 'Save',
    saving: 'Saving...',
    cancel: 'Cancel',
    confirmCancel: 'You have unsaved input. Cancel this entry?',
  },
  jp: {
    navLabel: '商品を登録',
    title: '商品を登録',
    description: 'カテゴリー、商品、価格を一つの画面で順番に登録します。',
    note: '本番カタログデータとして保存されます。保存前に入力内容を確認してください。',
    progressLabel: '商品登録ステップ',
    steps: {
      category: 'カテゴリー',
      product: '商品情報',
      price: '価格',
      confirm: '確認して保存',
    },
    category: {
      title: 'ステップ1 — カテゴリー',
      resource: 'カテゴリー',
      useExisting: '既存カテゴリーを選択',
      createNew: '新規カテゴリーを作成',
      existingLabel: '既存カテゴリー',
      selectPlaceholder: 'カテゴリーを選択してください',
      key: 'カテゴリーキー',
      name: 'カテゴリー名',
      nameKo: '韓国語名',
      nameJa: '日本語名',
      slug: 'スラッグ',
      sort: '並び順',
      visible: '公開状態',
      createNow: 'カテゴリーをすぐ作成',
      created: 'カテゴリー作成済み',
    },
    product: {
      title: 'ステップ2 — 商品情報',
      code: '商品コード',
      name: '商品名',
      description: '説明',
      descriptionPlaceholder: '素材、特徴、取引案内に必要な説明',
      category: 'カテゴリー',
      material: '素材',
      moq: 'MOQ',
      visible: '公開状態',
    },
    price: {
      title: 'ステップ4 — 価格',
      market: '市場',
      currency: '通貨',
      wholesale: '価格',
      retail: '小売価格',
      moq: 'MOQ',
      minOrderAmount: '最小問い合わせ金額',
      active: '価格を有効化',
    },
    confirm: {
      title: 'ステップ4 — 確認して保存',
      category: 'カテゴリー',
      productCode: '商品コード',
      productName: '商品名',
      market: '市場',
      currency: '通貨',
      price: '価格',
      visibility: '公開状態',
    },
    validation: {
      categoryRequired: 'カテゴリーを選択または作成してください。',
      categoryKeyRequired: 'カテゴリーキーを入力してください。',
      categoryNameRequired: 'カテゴリー名を入力してください。',
      slugRequired: 'スラッグを入力してください。',
      categoryConflict: '同じカテゴリーキーがすでに存在します。',
      productCodeRequired: '商品コードを入力してください。',
      productNameRequired: '商品名を入力してください。',
      productConflict: '同じ商品コードがすでに存在します。',
      marketRequired: '市場を選択してください。',
      currencyRequired: '通貨を選択してください。',
      priceRequired: '価格は0より大きい必要があります。',
      retailPriceInvalid: '小売価格は空欄、または0より大きい数値にしてください。',
      moqRequired: 'MOQは1以上で入力してください。',
    },
    errors: {
      unauthorized: 'ログインが必要です。',
      forbidden: '管理者権限が必要です。',
      conflict: 'すでに存在する項目です。入力内容を確認してください。',
      server: 'サーバーエラーが発生しました。しばらくしてから再試行してください。',
      network: 'ネットワーク接続を確認してください。',
      unknown: 'リクエストを処理できません。',
    },
    success: {
      title: '商品登録が完了しました。',
      saved: 'カテゴリー、商品、価格を保存しました。',
      viewProduct: '作成した商品を見る',
      productList: '商品一覧',
      continueAnother: '別の商品を続けて登録',
    },
    createdResource: '{resource}を作成しました。',
    productList: '商品一覧',
    previous: '戻る',
    next: '次へ',
    save: '保存',
    saving: '保存中...',
    cancel: 'キャンセル',
    confirmCancel: '入力中の内容があります。キャンセルしますか？',
  },
  cn: {
    navLabel: '添加产品',
    title: '添加产品',
    description: '在一个页面按顺序登记分类、产品和价格。',
    note: '这会保存为正式运营目录数据。保存前请确认输入内容。',
    progressLabel: '产品登记步骤',
    steps: {
      category: '分类',
      product: '产品信息',
      price: '价格',
      confirm: '确认并保存',
    },
    category: {
      title: '第 1 步 — 分类',
      resource: '分类',
      useExisting: '选择现有分类',
      createNew: '创建新分类',
      existingLabel: '现有分类',
      selectPlaceholder: '请选择分类',
      key: '分类键',
      name: '分类名称',
      nameKo: '韩文名称',
      nameJa: '日文名称',
      slug: 'Slug',
      sort: '排序',
      visible: '公开状态',
      createNow: '立即创建分类',
      created: '分类已创建',
    },
    product: {
      title: '第 2 步 — 产品信息',
      code: '产品代码',
      name: '产品名称',
      description: '说明',
      descriptionPlaceholder: '材质、特点和交易说明',
      category: '分类',
      material: '材质',
      moq: 'MOQ',
      visible: '公开状态',
    },
    price: {
      title: '第 4 步 — 价格',
      market: '市场',
      currency: '货币',
      wholesale: '价格',
      retail: '零售价',
      moq: 'MOQ',
      minOrderAmount: '最低询价金额',
      active: '价格启用状态',
    },
    confirm: {
      title: '第 4 步 — 确认并保存',
      category: '分类',
      productCode: '产品代码',
      productName: '产品名称',
      market: '市场',
      currency: '货币',
      price: '价格',
      visibility: '公开状态',
    },
    validation: {
      categoryRequired: '请选择或创建分类。',
      categoryKeyRequired: '请输入分类键。',
      categoryNameRequired: '请输入分类名称。',
      slugRequired: '请输入 slug。',
      categoryConflict: '已存在相同的分类键。',
      productCodeRequired: '请输入产品代码。',
      productNameRequired: '请输入产品名称。',
      productConflict: '已存在相同的产品代码。',
      marketRequired: '请选择市场。',
      currencyRequired: '请选择货币。',
      priceRequired: '价格必须大于 0。',
      retailPriceInvalid: '零售价可留空，或必须大于 0。',
      moqRequired: 'MOQ 必须大于等于 1。',
    },
    errors: {
      unauthorized: '需要登录。',
      forbidden: '需要管理员权限。',
      conflict: '该项目已存在。请确认输入内容。',
      server: '发生服务器错误。请稍后重试。',
      network: '请检查网络连接。',
      unknown: '无法处理请求。',
    },
    success: {
      title: '产品登记已完成。',
      saved: '分类、产品和价格已保存。',
      viewProduct: '查看已创建产品',
      productList: '产品列表',
      continueAnother: '继续添加其他产品',
    },
    createdResource: '{resource}已创建。',
    productList: '产品列表',
    previous: '上一步',
    next: '下一步',
    save: '保存',
    saving: '保存中...',
    cancel: '取消',
    confirmCancel: '有未保存的内容。确定取消吗？',
  },
}

for (const locale of Object.keys(catalogEntryCopy)) {
  copy[locale].catalogEntry = catalogEntryCopy[locale]
  copy[locale].shell.nav.catalogEntry = catalogEntryCopy[locale].navLabel
  copy[locale].dashboard.addProduct = catalogEntryCopy[locale].navLabel
}

const catalogEntryUnifiedCopy = {
  kr: {
    summaryTitle: '저장 요약',
    retryFailed: '실패한 단계 다시 저장',
    sections: {
      categoryEyebrow: '카테고리',
      productEyebrow: '상품 정보',
      imageEyebrow: '상품 사진',
      priceEyebrow: '가격',
    },
    saveStatus: {
      title: '저장 진행 상태',
      category: '카테고리',
      product: '상품',
      images: '사진',
      price: '가격',
      idle: '대기',
      saving: '저장 중',
      success: '완료',
      error: '실패',
    },
    productActive: '활성 상태',
    categoryNameConflict: '이미 같은 카테고리명이 있습니다.',
    productCodeInvalid: '상품 코드는 영문, 숫자, 점, 하이픈, 밑줄 80자 이내로 입력하세요.',
    imageCopy: {
      title: '3단계 — 상품 사진',
      description: '대표 사진 1장을 포함해 최대 8장까지 등록할 수 있습니다.',
      dropTitle: '사진을 끌어오거나 선택하세요',
      dropDescription: 'JPEG, PNG, WebP만 가능하며 파일당 최대 10MB입니다.',
      choose: '사진 선택',
      photo: '사진',
      primary: '대표 사진',
      setPrimary: '대표 지정',
      moveUp: '위로',
      moveDown: '아래로',
      remove: '삭제',
      altText: 'Alt text',
      altPlaceholder: '비워두면 상품명을 사용합니다',
      previewAlt: '상품 사진 미리보기',
      status: { ready: '준비 완료', uploading: '업로드 중', uploaded: '업로드 완료', error: '업로드 실패' },
    },
    imageValidation: {
      imageRequired: '상품 사진을 최소 1장 추가하세요.',
      imageCount: '상품 사진은 최대 8장까지 등록할 수 있습니다.',
      imageType: 'JPEG, PNG, WebP 파일만 등록할 수 있습니다.',
      imageTooLarge: '사진 1장당 최대 10MB까지 등록할 수 있습니다.',
      imageSignature: '이미지 파일이 손상되었거나 형식이 올바르지 않습니다.',
      imageInvalid: '사진을 확인하고 다시 선택하세요.',
      imageUploadNeedsProduct: '사진 업로드 전에 상품 저장이 필요합니다.',
    },
    imageErrors: {
      tooLarge: '사진 용량이 너무 큽니다. 10MB 이하 파일로 다시 시도하세요.',
      unsupportedImage: '지원하지 않는 이미지 형식입니다.',
    },
  },
  en: {
    summaryTitle: 'Save summary',
    retryFailed: 'Retry failed step',
    sections: {
      categoryEyebrow: 'Category',
      productEyebrow: 'Product information',
      imageEyebrow: 'Product photos',
      priceEyebrow: 'Price',
    },
    saveStatus: {
      title: 'Save progress',
      category: 'Category',
      product: 'Product',
      images: 'Photos',
      price: 'Price',
      idle: 'Ready',
      saving: 'Saving',
      success: 'Done',
      error: 'Failed',
    },
    productActive: 'Active',
    categoryNameConflict: 'A category with this name already exists.',
    productCodeInvalid: 'Use up to 80 letters, numbers, periods, hyphens, or underscores.',
    imageCopy: {
      title: 'Step 3 — Product Photos',
      description: 'Add at least one primary photo and up to eight photos total.',
      dropTitle: 'Drop photos here or choose files',
      dropDescription: 'JPEG, PNG, or WebP only. Maximum 10MB per file.',
      choose: 'Choose photos',
      photo: 'Photo',
      primary: 'Primary photo',
      setPrimary: 'Set primary',
      moveUp: 'Move up',
      moveDown: 'Move down',
      remove: 'Remove',
      altText: 'Alt text',
      altPlaceholder: 'Product name is used when empty',
      previewAlt: 'Product photo preview',
      status: { ready: 'Ready', uploading: 'Uploading', uploaded: 'Uploaded', error: 'Upload failed' },
    },
    imageValidation: {
      imageRequired: 'Add at least one product photo.',
      imageCount: 'Add no more than eight product photos.',
      imageType: 'Only JPEG, PNG, or WebP files are supported.',
      imageTooLarge: 'Each photo must be 10MB or smaller.',
      imageSignature: 'The image appears damaged or the file type is invalid.',
      imageInvalid: 'Check the photos and choose them again.',
      imageUploadNeedsProduct: 'Product must be saved before images can be uploaded.',
    },
    imageErrors: {
      tooLarge: 'The photo is too large. Try a file under 10MB.',
      unsupportedImage: 'This image type is not supported.',
    },
  },
  jp: {
    summaryTitle: '保存内容の概要',
    retryFailed: '失敗したステップを再保存',
    sections: {
      categoryEyebrow: 'カテゴリー',
      productEyebrow: '商品情報',
      imageEyebrow: '商品写真',
      priceEyebrow: '価格',
    },
    saveStatus: {
      title: '保存進行状況',
      category: 'カテゴリー',
      product: '商品',
      images: '写真',
      price: '価格',
      idle: '待機',
      saving: '保存中',
      success: '完了',
      error: '失敗',
    },
    productActive: '有効状態',
    categoryNameConflict: '同じカテゴリー名がすでに存在します。',
    productCodeInvalid: '商品コードは英数字、ピリオド、ハイフン、アンダースコア80文字以内で入力してください。',
    imageCopy: {
      title: 'ステップ3 — 商品写真',
      description: '代表写真を含め、最大8枚まで登録できます。',
      dropTitle: '写真をドロップ、または選択してください',
      dropDescription: 'JPEG、PNG、WebPのみ対応。1ファイル最大10MBです。',
      choose: '写真を選択',
      photo: '写真',
      primary: '代表写真',
      setPrimary: '代表に設定',
      moveUp: '上へ',
      moveDown: '下へ',
      remove: '削除',
      altText: 'Alt text',
      altPlaceholder: '空欄の場合は商品名を使用します',
      previewAlt: '商品写真プレビュー',
      status: { ready: '準備完了', uploading: 'アップロード中', uploaded: 'アップロード完了', error: 'アップロード失敗' },
    },
    imageValidation: {
      imageRequired: '商品写真を1枚以上追加してください。',
      imageCount: '商品写真は最大8枚まで登録できます。',
      imageType: 'JPEG、PNG、WebPのみ登録できます。',
      imageTooLarge: '写真は1枚10MB以下にしてください。',
      imageSignature: '画像が破損しているか、形式が正しくありません。',
      imageInvalid: '写真を確認して再度選択してください。',
      imageUploadNeedsProduct: '写真をアップロードする前に商品保存が必要です。',
    },
    imageErrors: {
      tooLarge: '写真容量が大きすぎます。10MB以下のファイルで再試行してください。',
      unsupportedImage: '対応していない画像形式です。',
    },
  },
  cn: {
    summaryTitle: '保存摘要',
    retryFailed: '重新保存失败步骤',
    sections: {
      categoryEyebrow: '分类',
      productEyebrow: '产品信息',
      imageEyebrow: '产品图片',
      priceEyebrow: '价格',
    },
    saveStatus: {
      title: '保存进度',
      category: '分类',
      product: '产品',
      images: '图片',
      price: '价格',
      idle: '待处理',
      saving: '保存中',
      success: '完成',
      error: '失败',
    },
    productActive: '启用状态',
    categoryNameConflict: '已存在相同的分类名称。',
    productCodeInvalid: '产品代码限 80 个字符，可使用英文字母、数字、点、连字符或下划线。',
    imageCopy: {
      title: '第 3 步 — 产品图片',
      description: '至少添加 1 张主图，最多可添加 8 张图片。',
      dropTitle: '拖入图片或选择文件',
      dropDescription: '仅支持 JPEG、PNG、WebP；单个文件最大 10MB。',
      choose: '选择图片',
      photo: '图片',
      primary: '主图',
      setPrimary: '设为主图',
      moveUp: '上移',
      moveDown: '下移',
      remove: '删除',
      altText: 'Alt text',
      altPlaceholder: '留空时使用产品名称',
      previewAlt: '产品图片预览',
      status: { ready: '已准备', uploading: '上传中', uploaded: '已上传', error: '上传失败' },
    },
    imageValidation: {
      imageRequired: '请至少添加 1 张产品图片。',
      imageCount: '产品图片最多可添加 8 张。',
      imageType: '仅支持 JPEG、PNG、WebP 文件。',
      imageTooLarge: '每张图片必须小于等于 10MB。',
      imageSignature: '图片已损坏或文件类型不正确。',
      imageInvalid: '请检查图片后重新选择。',
      imageUploadNeedsProduct: '上传图片前必须先保存产品。',
    },
    imageErrors: {
      tooLarge: '图片过大。请使用 10MB 以下文件重试。',
      unsupportedImage: '不支持该图片格式。',
    },
  },
}

for (const locale of Object.keys(catalogEntryUnifiedCopy)) {
  const entry = copy[locale].catalogEntry
  const extra = catalogEntryUnifiedCopy[locale]
  entry.summaryTitle = extra.summaryTitle
  entry.retryFailed = extra.retryFailed
  entry.sections = extra.sections
  entry.saveStatus = extra.saveStatus
  entry.images = extra.imageCopy
  entry.product.active = extra.productActive
  entry.confirm.images = extra.imageCopy.photo
  entry.validation.categoryNameConflict = extra.categoryNameConflict
  entry.validation.productCodeInvalid = extra.productCodeInvalid
  Object.assign(entry.validation, extra.imageValidation)
  Object.assign(entry.errors, extra.imageErrors)
}

const catalogEntryPlacementCopy = {
  kr: { newArrival: '신상품 노출', weeklyBest: '주간 추천 표시' },
  en: { newArrival: 'Show in New Arrivals', weeklyBest: 'Mark as Weekly Best' },
  jp: { newArrival: '新商品に表示', weeklyBest: '週間おすすめに表示' },
  cn: { newArrival: '新品區顯示', weeklyBest: '標記為本週推薦' },
}

for (const locale of Object.keys(catalogEntryPlacementCopy)) {
  const entry = copy[locale].catalogEntry
  const placement = catalogEntryPlacementCopy[locale]
  entry.product.newArrival = placement.newArrival
  entry.product.weeklyBest = placement.weeklyBest
}

const catalogEntryMarketPriceCopy = {
  kr: {
    mode: '가격 방식',
    markets: '시장별 가격',
    autoNote: 'KRW 기준 가격과 최신 환율 묶음으로 자동 계산됩니다.',
    unavailableNote: '이 시장 가격은 이번 저장에서 등록하지 않습니다.',
    modes: { fx_auto: '환율 자동', manual_fixed: '고정 가격', unavailable: '미등록' },
    marketModeRequired: '시장별 가격 방식을 확인하세요.',
  },
  en: {
    mode: 'Price mode',
    markets: 'Market prices',
    autoNote: 'Calculated automatically from the KRW source price and the latest FX bundle.',
    unavailableNote: 'This market price will not be registered in this save.',
    modes: { fx_auto: 'FX auto', manual_fixed: 'Manual fixed', unavailable: 'Unavailable' },
    marketModeRequired: 'Check the market price mode.',
  },
  jp: {
    mode: '価格方式',
    markets: '市場別価格',
    autoNote: 'KRW基準価格と最新為替レートで自動計算されます。',
    unavailableNote: 'この市場価格は今回登録しません。',
    modes: { fx_auto: '為替自動', manual_fixed: '固定価格', unavailable: '未登録' },
    marketModeRequired: '市場別の価格方式を確認してください。',
  },
  cn: {
    mode: '价格模式',
    markets: '各市场价格',
    autoNote: '根据 KRW 基准价和最新汇率自动计算。',
    unavailableNote: '本次保存不会登记该市场价格。',
    modes: { fx_auto: '汇率自动', manual_fixed: '固定价格', unavailable: '未登记' },
    marketModeRequired: '请确认各市场的价格模式。',
  },
}

for (const locale of Object.keys(catalogEntryMarketPriceCopy)) {
  const entry = copy[locale].catalogEntry
  const extra = catalogEntryMarketPriceCopy[locale]
  entry.price.mode = extra.mode
  entry.price.modes = extra.modes
  entry.price.autoNote = extra.autoNote
  entry.price.unavailableNote = extra.unavailableNote
  entry.confirm.markets = extra.markets
  entry.validation.marketModeRequired = extra.marketModeRequired
}

const adminAccessConsoleCopy = {
  kr: {
    groups: { overview: '개요', operations: '운영', catalog: '카탈로그', insights: '인사이트', governance: '권한 관리' },
    nav: { team: '관리자 팀', audit: '감사 로그' },
    roles: { operator: '운영자', manager: '매니저', owner: '소유자' },
    currentAdmin: '현재 관리자',
    forbiddenTitle: '권한이 필요합니다',
    forbiddenBody: '이 관리자 화면을 보려면 추가 권한이 필요합니다.',
    team: { eyebrow: '권한 관리', title: '관리자 팀', body: '관리자 역할과 계정 상태를 확인합니다.', empty: '관리자 계정이 없습니다.', email: '이메일', role: '역할', account: '계정' },
    audit: { eyebrow: '권한 관리', title: '감사 로그', body: '민감한 원본 값 없이 최근 관리자 활동을 확인합니다.', empty: '감사 이벤트가 없습니다.', action: '작업', entity: '대상', request: '요청', created: '생성일' },
  },
  en: {
    groups: { overview: 'Overview', operations: 'Operations', catalog: 'Catalog', insights: 'Insights', governance: 'Governance' },
    nav: { team: 'Admin team', audit: 'Audit log' },
    roles: { operator: 'Operator', manager: 'Manager', owner: 'Owner' },
    currentAdmin: 'Current admin',
    forbiddenTitle: 'Permission required',
    forbiddenBody: 'This admin page requires a permission that is not assigned to your account.',
    team: { eyebrow: 'Governance', title: 'Admin team', body: 'Review admin roles and account state.', empty: 'No admin users found.', email: 'Email', role: 'Role', account: 'Account' },
    audit: { eyebrow: 'Governance', title: 'Audit log', body: 'Review recent admin activity without sensitive snapshots.', empty: 'No audit events found.', action: 'Action', entity: 'Entity', request: 'Request', created: 'Created' },
  },
  jp: {
    groups: { overview: '概要', operations: '運用', catalog: 'カタログ', insights: '分析', governance: '権限管理' },
    nav: { team: '管理者チーム', audit: '監査ログ' },
    roles: { operator: 'オペレーター', manager: 'マネージャー', owner: 'オーナー' },
    currentAdmin: '現在の管理者',
    forbiddenTitle: '権限が必要です',
    forbiddenBody: 'この管理画面を表示するには追加権限が必要です。',
    team: { eyebrow: '権限管理', title: '管理者チーム', body: '管理者の役割とアカウント状態を確認します。', empty: '管理者が見つかりません。', email: 'メール', role: '役割', account: 'アカウント' },
    audit: { eyebrow: '権限管理', title: '監査ログ', body: '機密スナップショットなしで最近の管理者操作を確認します。', empty: '監査イベントはありません。', action: '操作', entity: '対象', request: 'リクエスト', created: '作成日' },
  },
  cn: {
    groups: { overview: '概览', operations: '运营', catalog: '目录', insights: '分析', governance: '权限管理' },
    nav: { team: '管理员团队', audit: '审计日志' },
    roles: { operator: '操作员', manager: '经理', owner: '所有者' },
    currentAdmin: '当前管理员',
    forbiddenTitle: '需要权限',
    forbiddenBody: '此管理页面需要账号具备额外权限。',
    team: { eyebrow: '权限管理', title: '管理员团队', body: '查看管理员角色和账号状态。', empty: '未找到管理员。', email: '邮箱', role: '角色', account: '账号' },
    audit: { eyebrow: '权限管理', title: '审计日志', body: '查看最近的管理员活动，不显示敏感快照。', empty: '没有审计事件。', action: '操作', entity: '对象', request: '请求', created: '创建时间' },
  },
}

for (const locale of Object.keys(adminAccessConsoleCopy)) {
  copy[locale].shell.groups = adminAccessConsoleCopy[locale].groups
  copy[locale].shell.roles = adminAccessConsoleCopy[locale].roles
  copy[locale].shell.currentAdmin = adminAccessConsoleCopy[locale].currentAdmin
  copy[locale].shell.forbiddenTitle = adminAccessConsoleCopy[locale].forbiddenTitle
  copy[locale].shell.forbiddenBody = adminAccessConsoleCopy[locale].forbiddenBody
  Object.assign(copy[locale].shell.nav, adminAccessConsoleCopy[locale].nav)
  copy[locale].team = adminAccessConsoleCopy[locale].team
  copy[locale].audit = adminAccessConsoleCopy[locale].audit
}

const adminMemberManagementCopy = {
  kr: {
    groups: { members: '회원' },
    nav: { team: '운영', buyers: '거래처' },
    buyers: {
      loginIdLine: '아이디 {loginId}',
      promoteOperator: '운영자로 지정',
      promoteNeedsEmail: '운영자로 지정하려면 회원 이메일이 필요합니다.',
      promoteConfirm: '{buyer} 회원을 운영자로 지정할까요?',
      promoteSuccess: '운영자로 지정했습니다. 회원 > 운영 메뉴에서 확인할 수 있습니다.',
      promoteFailed: '운영자로 지정할 수 없습니다.',
      promotePermissionNote: '운영자 지정은 최고 관리자 권한이 필요합니다.',
    },
  },
  en: {
    groups: { members: 'Members' },
    nav: { team: 'Operators', buyers: 'Buyers' },
    buyers: {
      loginIdLine: 'ID {loginId}',
      promoteOperator: 'Assign operator',
      promoteNeedsEmail: 'A member email is required to assign an operator.',
      promoteConfirm: 'Assign {buyer} as an operator?',
      promoteSuccess: 'Assigned as an operator. Review it under Members > Operators.',
      promoteFailed: 'Unable to assign operator.',
      promotePermissionNote: 'Only the owner administrator can assign operators.',
    },
  },
  jp: {
    groups: { members: '会員' },
    nav: { team: '運営', buyers: '取引先' },
    buyers: {
      loginIdLine: 'ID {loginId}',
      promoteOperator: '運営者に指定',
      promoteNeedsEmail: '運営者に指定するには会員メールが必要です。',
      promoteConfirm: '{buyer} を運営者に指定しますか？',
      promoteSuccess: '運営者に指定しました。会員 > 運営で確認できます。',
      promoteFailed: '運営者に指定できません。',
      promotePermissionNote: '運営者の指定には最高管理者権限が必要です。',
    },
  },
  cn: {
    groups: { members: '会员' },
    nav: { team: '运营', buyers: '客户' },
    buyers: {
      loginIdLine: 'ID {loginId}',
      promoteOperator: '设为运营',
      promoteNeedsEmail: '设为运营需要会员邮箱。',
      promoteConfirm: '要将 {buyer} 设为运营吗？',
      promoteSuccess: '已设为运营。可在会员 > 运营中确认。',
      promoteFailed: '无法设为运营。',
      promotePermissionNote: '只有最高管理员可以指定运营。',
    },
  },
}

for (const locale of Object.keys(adminMemberManagementCopy)) {
  Object.assign(copy[locale].shell.groups, adminMemberManagementCopy[locale].groups)
  Object.assign(copy[locale].shell.nav, adminMemberManagementCopy[locale].nav)
  Object.assign(copy[locale].buyers, adminMemberManagementCopy[locale].buyers)
}

const adminFxAutoCopy = {
  kr: {
    nav: '자동 환율 가격',
    title: '자동 환율 가격',
    description: 'KRW 기준 가격에서 JP/US/TW 공개 가격을 자동 계산하고 운영 상태를 확인합니다.',
    note: '관리자 승인 draft 없이 5% 이상 차이가 나면 자동 반영합니다. 15% 이상 환율 급변 또는 72시간 초과 환율은 차단됩니다.',
    policy: '가격 정책',
    reviewTitle: '자동 가격 정책',
    deadband: '유지 구간',
    breaker: '급변 차단',
    maxAge: '최대 환율 age',
    lastRun: '마지막 실행',
    schedule: '스케줄',
    scheduleTitle: '환율 수집 및 자동 평가',
    snapshotSchedule: '평일 09:10, 13:10, 17:10 KST',
    autoRule: '5% 미만은 유지, 5% 이상은 자동 반영, 15% 이상은 차단합니다.',
    currentRates: '현재 환율',
    ratesTitle: 'KRW per unit',
    stale: '오래됨',
    fresh: '정상',
    emptyRates: '등록된 환율 snapshot이 없습니다.',
    prices: '자동 가격',
    pricesTitle: '가격 모니터',
    emptyPrices: '표시할 자동 가격 정책이 없습니다.',
    mode: '모드',
    publishedPrice: '공개 가격',
    referencePrice: '참고 가격',
    divergence: '차이',
    lastAutoUpdate: '마지막 자동 변경',
    evaluate: '다시 평가',
    pause: '일시정지',
    resume: '재개',
    pauseReason: '일시정지 사유를 입력하세요.',
    evaluated: '자동 가격을 다시 평가했습니다.',
    paused: '자동 가격을 일시정지했습니다.',
    resumed: '자동 가격을 재개했습니다.',
    marketCurrency: '시장 / 통화',
    modes: { manual_fixed: '고정 가격', fx_auto: '환율 자동' },
    statuses: {
      pending_rate: '환율 대기',
      active: '정상',
      held_deadband: '5% 미만 유지',
      updated: '자동 변경',
      created: '자동 생성',
      blocked_stale: '오래된 환율',
      blocked_spike: '급변 차단',
      paused: '일시정지',
      error: '오류',
    },
  },
  en: {
    nav: 'Auto FX Pricing',
    title: 'Auto FX Pricing',
    description: 'Monitor automatic JP/US/TW prices calculated from the KRW source price.',
    note: 'No approval drafts are used. Prices update automatically at 5% or more divergence, while 15% rate spikes and rates older than 72 hours are blocked.',
    policy: 'Policy',
    reviewTitle: 'Automatic pricing policy',
    deadband: 'Hold band',
    breaker: 'Spike breaker',
    maxAge: 'Max rate age',
    lastRun: 'Last run',
    schedule: 'Schedule',
    scheduleTitle: 'Rate collection and evaluation',
    snapshotSchedule: 'Weekdays 09:10, 13:10, 17:10 KST',
    autoRule: 'Under 5% is held, 5% or more is auto-applied, and 15% or more is blocked.',
    currentRates: 'Current rates',
    ratesTitle: 'KRW per unit',
    stale: 'Stale',
    fresh: 'Fresh',
    emptyRates: 'No FX snapshots are available.',
    prices: 'Auto prices',
    pricesTitle: 'Price monitor',
    emptyPrices: 'No automatic price policies to show.',
    mode: 'Mode',
    publishedPrice: 'Published price',
    referencePrice: 'Reference price',
    divergence: 'Divergence',
    lastAutoUpdate: 'Last auto update',
    evaluate: 'Re-evaluate',
    pause: 'Pause',
    resume: 'Resume',
    pauseReason: 'Enter a pause reason.',
    evaluated: 'Automatic prices were re-evaluated.',
    paused: 'Automatic price paused.',
    resumed: 'Automatic price resumed.',
    marketCurrency: 'Market / currency',
    modes: { manual_fixed: 'Manual fixed', fx_auto: 'FX auto' },
    statuses: {
      pending_rate: 'Pending rate',
      active: 'Active',
      held_deadband: 'Held under 5%',
      updated: 'Updated',
      created: 'Created',
      blocked_stale: 'Blocked stale',
      blocked_spike: 'Blocked spike',
      paused: 'Paused',
      error: 'Error',
    },
  },
  jp: {
    nav: '自動為替価格',
    title: '自動為替価格',
    description: 'KRW 基準価格から JP/US/TW の公開価格を自動計算し、運用状態を確認します。',
    note: '承認用ドラフトは使いません。差分が5%以上なら自動反映し、15%以上の為替急変または72時間超過の為替はブロックします。',
    policy: '価格ポリシー',
    reviewTitle: '自動価格ポリシー',
    deadband: '維持範囲',
    breaker: '急変ブロック',
    maxAge: '最大為替 age',
    lastRun: '最終実行',
    schedule: 'スケジュール',
    scheduleTitle: '為替取得と自動評価',
    snapshotSchedule: '平日 09:10、13:10、17:10 KST',
    autoRule: '5%未満は維持、5%以上は自動反映、15%以上はブロックします。',
    currentRates: '現在の為替',
    ratesTitle: 'KRW per unit',
    stale: '古い',
    fresh: '正常',
    emptyRates: '登録された為替 snapshot がありません。',
    prices: '自動価格',
    pricesTitle: '価格モニター',
    emptyPrices: '表示する自動価格ポリシーがありません。',
    mode: 'モード',
    publishedPrice: '公開価格',
    referencePrice: '参考価格',
    divergence: '差分',
    lastAutoUpdate: '最終自動変更',
    evaluate: '再評価',
    pause: '一時停止',
    resume: '再開',
    pauseReason: '一時停止の理由を入力してください。',
    evaluated: '自動価格を再評価しました。',
    paused: '自動価格を一時停止しました。',
    resumed: '自動価格を再開しました。',
    marketCurrency: '市場 / 通貨',
    modes: { manual_fixed: '固定価格', fx_auto: '為替自動' },
    statuses: {
      pending_rate: '為替待ち',
      active: '正常',
      held_deadband: '5%未満維持',
      updated: '自動変更',
      created: '自動生成',
      blocked_stale: '古い為替',
      blocked_spike: '急変ブロック',
      paused: '一時停止',
      error: 'エラー',
    },
  },
  cn: {
    nav: '自动汇率价格',
    title: '自动汇率价格',
    description: '基于 KRW 价格自动计算 JP/US/TW 公开价格，并查看运行状态。',
    note: '不再使用审批草稿。差异达到 5% 自动更新，汇率波动达到 15% 或汇率超过 72 小时会被阻止。',
    policy: '价格策略',
    reviewTitle: '自动价格策略',
    deadband: '保持区间',
    breaker: '波动阻断',
    maxAge: '最大汇率 age',
    lastRun: '最近执行',
    schedule: '计划',
    scheduleTitle: '汇率采集与自动评估',
    snapshotSchedule: '工作日 09:10、13:10、17:10 KST',
    autoRule: '低于 5% 保持，5% 以上自动更新，15% 以上阻断。',
    currentRates: '当前汇率',
    ratesTitle: 'KRW per unit',
    stale: '过期',
    fresh: '正常',
    emptyRates: '没有可用的汇率 snapshot。',
    prices: '自动价格',
    pricesTitle: '价格监控',
    emptyPrices: '没有可显示的自动价格策略。',
    mode: '模式',
    publishedPrice: '公开价格',
    referencePrice: '参考价格',
    divergence: '差异',
    lastAutoUpdate: '最近自动更新',
    evaluate: '重新评估',
    pause: '暂停',
    resume: '恢复',
    pauseReason: '请输入暂停原因。',
    evaluated: '自动价格已重新评估。',
    paused: '自动价格已暂停。',
    resumed: '自动价格已恢复。',
    marketCurrency: '市场 / 货币',
    modes: { manual_fixed: '固定价格', fx_auto: '汇率自动' },
    statuses: {
      pending_rate: '等待汇率',
      active: '正常',
      held_deadband: '低于5%保持',
      updated: '自动更新',
      created: '自动创建',
      blocked_stale: '汇率过期',
      blocked_spike: '波动阻断',
      paused: '暂停',
      error: '错误',
    },
  },
}

for (const locale of Object.keys(adminFxAutoCopy)) {
  copy[locale].fx = adminFxAutoCopy[locale]
  copy[locale].shell.nav.fx = adminFxAutoCopy[locale].nav
}

copy[taiwanLocale] = toTaiwanTraditional(copy.cn)

const catalogEntryAttributeCopy = {
  kr: {
    colors: '색상 옵션',
    colorsPlaceholder: '골드, 로즈골드, 실버',
    sizes: '사이즈 옵션',
    sizesPlaceholder: '6mm, 8mm, 10mm',
    badge: '배지',
    eyebrow: '상품 속성',
    title: '필터와 상세 정보',
    description: '공개 필터, 상품 상세, 홈 노출에 사용할 운영 속성을 입력합니다.',
    gauge: '게이지',
    length: '길이',
    ballSize: '볼 사이즈',
    barThickness: '바 두께',
    unit: '단위',
    detailHeadline: '상세 제목',
    detailHeadlinePlaceholder: '상품 상세에서 강조할 문장',
    detailBody: '상세 설명',
    detailBodyPlaceholder: '소재, 착용감, 구성, 주의사항을 운영 문구로 입력',
    care: '관리 안내',
    carePlaceholder: '보관 및 세척 안내',
    fit: '착용 안내',
    fitPlaceholder: '착용 위치나 핏 안내',
    decoration: '장식 상세',
    decorationPlaceholder: '큐빅, 진주, 원석 등 장식 설명',
    homePlacement: '홈 노출 관리',
    showInSnap: '상단 스냅',
    showInNewArrivals: '신상품',
    showInWeeklyPick: '주간 추천',
    showInBuyerSelection: '바이어 셀렉션',
    showInPiercing: '피어싱',
    showInSteadySelection: '스테디 셀렉션',
    homeNote: '홈 노출 메모',
    homeNotePlaceholder: '홈 카드 또는 섹션 메모',
    sortPriority: '노출 우선순위',
  },
  en: {
    colors: 'Color options',
    colorsPlaceholder: 'Gold, Rose Gold, Silver',
    sizes: 'Size options',
    sizesPlaceholder: '6mm, 8mm, 10mm',
    badge: 'Badge',
    eyebrow: 'Product attributes',
    title: 'Filters and detail content',
    description: 'Set the operating attributes used by public filters, product detail, and home placement.',
    gauge: 'Gauge',
    length: 'Length',
    ballSize: 'Ball size',
    barThickness: 'Bar thickness',
    unit: 'Unit',
    detailHeadline: 'Detail headline',
    detailHeadlinePlaceholder: 'Headline shown on product detail',
    detailBody: 'Detail description',
    detailBodyPlaceholder: 'Describe material, fit, structure, and handling notes',
    care: 'Care note',
    carePlaceholder: 'Storage and cleaning guidance',
    fit: 'Fit note',
    fitPlaceholder: 'Placement or fit guidance',
    decoration: 'Decoration detail',
    decorationPlaceholder: 'Cubic, pearl, stone, or finish detail',
    homePlacement: 'Home placement',
    showInSnap: 'Top snap',
    showInNewArrivals: 'New Arrivals',
    showInWeeklyPick: 'Weekly Pick',
    showInBuyerSelection: 'Buyer Selection',
    showInPiercing: 'Piercing',
    showInSteadySelection: 'Steady Selection',
    homeNote: 'Home note',
    homeNotePlaceholder: 'Card or section note',
    sortPriority: 'Placement priority',
  },
  jp: {
    colors: 'カラーオプション',
    colorsPlaceholder: 'ゴールド、ローズゴールド、シルバー',
    sizes: 'サイズオプション',
    sizesPlaceholder: '6mm, 8mm, 10mm',
    badge: 'バッジ',
    eyebrow: '商品属性',
    title: 'フィルターと詳細情報',
    description: '公開フィルター、商品詳細、ホーム掲載に使う運用属性を設定します。',
    gauge: 'ゲージ',
    length: '長さ',
    ballSize: 'ボールサイズ',
    barThickness: 'バーの太さ',
    unit: '単位',
    detailHeadline: '詳細見出し',
    detailHeadlinePlaceholder: '商品詳細で強調する見出し',
    detailBody: '詳細説明',
    detailBodyPlaceholder: '素材、着用感、構造、注意事項を入力',
    care: 'ケア案内',
    carePlaceholder: '保管とお手入れの案内',
    fit: '着用案内',
    fitPlaceholder: '着用位置やフィット感の案内',
    decoration: '装飾詳細',
    decorationPlaceholder: 'キュービック、パール、石などの説明',
    homePlacement: 'ホーム掲載管理',
    showInSnap: 'トップスナップ',
    showInNewArrivals: '新商品',
    showInWeeklyPick: '週間おすすめ',
    showInBuyerSelection: 'バイヤーセレクション',
    showInPiercing: 'ピアス',
    showInSteadySelection: 'ステディセレクション',
    homeNote: 'ホーム掲載メモ',
    homeNotePlaceholder: 'カードまたはセクション用メモ',
    sortPriority: '掲載優先度',
  },
  cn: {
    colors: '顏色選項',
    colorsPlaceholder: '金色、玫瑰金、銀色',
    sizes: '尺寸選項',
    sizesPlaceholder: '6mm, 8mm, 10mm',
    badge: '標籤',
    eyebrow: '商品屬性',
    title: '篩選與詳細內容',
    description: '設定公開篩選、商品詳情與首頁露出使用的營運屬性。',
    gauge: '規格',
    length: '長度',
    ballSize: '球尺寸',
    barThickness: '桿厚度',
    unit: '單位',
    detailHeadline: '詳情標題',
    detailHeadlinePlaceholder: '商品詳情要強調的標題',
    detailBody: '詳細說明',
    detailBodyPlaceholder: '輸入材質、配戴感、結構與注意事項',
    care: '保養說明',
    carePlaceholder: '保存與清潔說明',
    fit: '配戴說明',
    fitPlaceholder: '配戴位置或貼合說明',
    decoration: '裝飾細節',
    decorationPlaceholder: '鋯石、珍珠、天然石或表面處理說明',
    homePlacement: '首頁露出管理',
    showInSnap: '頂部形象',
    showInNewArrivals: '新品',
    showInWeeklyPick: '每週推薦',
    showInBuyerSelection: '買家精選',
    showInPiercing: '穿孔',
    showInSteadySelection: '常態精選',
    homeNote: '首頁露出備註',
    homeNotePlaceholder: '卡片或區塊備註',
    sortPriority: '露出優先順序',
  },
}

const catalogEntryAttributeValidationCopy = {
  kr: {
    sortPriorityInvalid: '노출 우선순위는 정수로 입력하세요.',
  },
  en: {
    sortPriorityInvalid: 'Placement priority must be an integer.',
  },
  jp: {
    sortPriorityInvalid: '表示優先度は整数で入力してください。',
  },
  cn: {
    sortPriorityInvalid: '顯示優先順序必須是整數。',
  },
}

for (const locale of ['kr', 'en', 'jp', 'cn', taiwanLocale]) {
  const sourceLocale = locale === taiwanLocale ? 'cn' : locale
  const entry = copy[locale]?.catalogEntry
  if (!entry) continue
  entry.attributes = catalogEntryAttributeCopy[sourceLocale]
  entry.validation.sortPriorityInvalid = catalogEntryAttributeValidationCopy[sourceLocale].sortPriorityInvalid
}

export const adminLocales = supportedLocales
export const adminCopy = Object.fromEntries(supportedLocales.map((locale) => [locale, copy[locale]]))

export function getAdminCopy(locale) {
  return resolveLocaleCopy(copy, locale, 'en')
}

export function useAdminCopy() {
  const { locale } = useLocalePath()
  return getAdminCopy(locale)
}

export function formatAdminCopy(template, values = {}) {
  return String(template || '').replace(/\{(\w+)\}/g, (_, key) => values[key] ?? '')
}

export function getAdminRuntimeKind(runtimeConfig) {
  const label = String(runtimeConfig?.stagingLabel || '').toLowerCase()
  const apiBase = String(runtimeConfig?.apiBaseUrl || '').toLowerCase()
  if (runtimeConfig?.dataMode === 'mock') return 'development'
  if (label.includes('staging') || apiBase.includes('staging')) return 'staging'
  if (runtimeConfig?.isProd || label.includes('production') || apiBase === '/api' || apiBase.includes('noblesse.web.app/api')) return 'production'
  return 'development'
}

export function getAdminStatusLabel(t, status) {
  return t.statuses.inquiry[status] || t.statuses.buyer[status] || t.statuses.quote[status] || t.statuses.visibility[status] || t.common[status] || status
}
